### ISSUE TITLE
Booking Timeout Broken

### ISSUE THREAD

**Issue by bmottershead** [calcom/cal.com#10973] opened 2023-08-26 18:28 UTC
### Issue Summary

There is a period, apparently 5 minutes in length, where after selecting a day and time for a booking, that time is  locked out or "reserved", and not available to be chosen by other users.  Unfortunately, it is also not available to be chosen again by the same user who "reserved" it.   Consequently, having arrived at the "Confirm" page, a user who backs up to reconsider alternative event-types or timeslots will find that their initial timeslot choice is  is now unavailable.   If they try  the same day  with the very same, or another, event-type, the time that they just chose will not be available.   The timeslot doesn't become available again for 5 minutes, for anybody.

This is very confusing.   What happened to that time that was available a few seconds ago?  There is no indication that the availability is only temporarily blocked, and the timeslot will become available again in 5 minutes, perhaps less.   Users will think the booking system is broken.

### Steps to Reproduce

1. Select  an event type.

2. Click a date, then click a time.

3. On the Confirm screen, click "Back".  This will take you back to the screen where you
just picked a time.  (You can also get back to this screen other ways.)  The time you just selected 
will no longer be shown as available, even though you just selected it.   The only way it will be available is if you come back after 5 minutes.

By doing these three steps repeatedly,  picking different events/timeslots each time, it seems to be possible for one user to lock out a lot of timeslots, at least for the timeout period, without actually "Confirming" anything.

### Expected Results

Possibilities:
(1) No reservation/lockout period.  Everybody is in a race to click Confirm first.  If the user clicks "Confirm", there is the possibility that the chosen timeslot, or part of it, has been grabbed by somebody else, especially if the user has been too slow.  Note that the system has to deal with this possibility anyway because the reservation is some fixed time, and after that time, clicking Confirm can fail because someone else grabbed the timeslot, or part of it.

(2) Reservation period, but it doesn't apply against the person who made the reservation.  If someone backs up  from the Confirm screen to reconsider times, days, or other event-types, that user can still get "their" orignally-selected time slot, within the "reservation" limit. 

(3) Reservation period, but the reservation expires if the user who made the reservation navigates
away from the page with the "Confirm" button.   Things are as they were, and the user (or anybody else) can now book that time-slot.

### Actual Results

The reservation expires after 5 minutes, and a user who navigates away from the "Confirm" button
must wait the 5 minutes to be able to get that time again.  During that 5 minutes, the timeslot is not
available again for the event type selected (or any other event-type) to anybody, including the user who initiated the reservation.

**Comment by vijayraghav-io** [comment] 2023-08-28 07:27
Hi @Udit-takkar / anybody who is assigning,
I can work on this, please assign.

**Comment by bmottershead** [comment] 2023-08-30 20:09
Did anyone attempt to reproduce the problem in the embedded UI?   It happens without fail in that context, as far as I can tell, and because of this, I would urge @PeerRich to reconsider the Medium Priority assigned to this issue.   If it would help in making the decision to do that, I could workup a testbed environment where the problem can be reproduced.   But I hazard the guess that you folks have an embedded UI testbed already.

**Comment by vijayraghav-io** [comment] 2023-08-31 06:33
@bmottershead , Yes Now i am able to **exactly** recreate the issue in embed UI.

The root cause is also found - 
In case of embed, the cookies are not set in requests to trpc.
The trpc endpoint "slots.removeSelectedSlotMark" relies on cookies in request to get the uid. And uses this uid to delete the selection mark in db.
Hence for embed case, it's (endpoint) not able to get uid from cookie, and the selection mark is not removed. So the slot is still reserved.

I am working on this and will raise a PR asap (probably in < couple of days).


I also opine that the other issue - "User not clicks on back or confirm button after selecting the slot, but opens a new tab and tries to select in same eventType, finds that not able to select same slot again nor not able to confirm". 
The expected behaviour would be redirect the user to "confirm / back" page/dialog, if reserved slot still exists (i.e user comes here again within 5 mins in a new tab, ). So thereby we are preserving the reservation and also asking for confirmation or reselect the slot, first.
This issue is common across embed/non-embed. May be this can be addressed in other PR.

**Closed** 2023-09-05 10:10 UTC
Labels: 🐛 bug, Medium priority, bookings
