### ISSUE TITLE
[CAL-1910] Segments colour & contrast is off

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9402] opened 2023-06-07 18:12 UTC
* [ ] bg is white
* [ ] active state should bg-emphasis

![CleanShot 2023-06-07 at 19.12.03@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/56cfe8bd-02d7-4d00-9c97-49aae3f2ce87/798a9805-d02f-4529-b68d-509151c32014)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1910](https://linear.app/calcom/issue/CAL-1910/segments-colour-and-contrast-is-off)</sub>

**Comment by Udit-takkar** [comment] 2023-06-09 12:04
duplicate of https://github.com/calcom/cal.com/issues/9403

**Closed by Udit-takkar** 2023-06-09 12:04 UTC
Labels: 🐛 bug
