### ISSUE TITLE
[BUG]:Issue - Incomplete Text Display on viewport of cal.com Homepage

### ISSUE THREAD

**Issue by vivekpanth** [calcom/cal.com#11725] opened 2023-10-06 09:58 UTC
Found a bug? Please fill out the sections below. 👍

### Steps to Reproduce
1. Go to cal.com
2. Observe the text "Scheduling infrastructure for everyone." in the body section on the homepage during the initial page load without scrolling. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The text "Scheduling infrastructure for everyone." is partially visible, and users need to scroll to see the full text.

### Expected Results

- The entire text "Scheduling infrastructure for everyone." should be visible within the viewport without the need to scroll upon the initial page load.
-This issue affects the user experience on the website as users may not immediately see the full message intended by the text.

### Technical details

- Browser: Chrome Version 117.0.5938.134
- Operating System:  Windows 10

### Evidence
![issue-homepage](https://github.com/calcom/cal.com/assets/106002167/e74b3710-0138-4c46-9ae0-d70fb0f4240f)

-.

**Comment by abdulrehmanjaved-1** [comment] 2023-10-06 10:12
I would like to work on this bug. Assign me .

**Comment by Siddharth-2382** [comment] 2023-10-06 11:24
@vivekpanth what's the size of your laptop? I'm using a MacBook Air 13' and the text is completely visible on my device.

**Comment by vivekpanth** [comment] 2023-10-06 14:36
> @vivekpanth what's the size of your laptop? I'm using a MacBook Air 13' and the text is completely visible on my device.

It's 1366*768px
![displaysize](https://github.com/calcom/cal.com/assets/106002167/b04661ea-fb68-4230-a2ff-4bfbe607ab8c)

**Comment by Siddharth-2382** [comment] 2023-10-06 14:43
I don't think this can be a big issue because let's say the issue is fixed by adjusting some padding here and there, we can't be sure if this will not happen to someone else later. Many users don't have the bookmarks bar which may even let the text be visible on your device whilst others may have different preferences. Well that's just my opinion, it totally depends on the project managers.

**Comment by vivekpanth** [comment] 2023-10-06 14:52
> I don't think this can be a big issue because let's say the issue is fixed by adjusting some padding here and there, we can't be sure if this will not happen to someone else later. Many users don't have the bookmarks bar which may even let the text be visible on your device whilst others may have different preferences. Well that's just my opinion, it totally depends on the project managers.

I agree with your opinion. But if the aim is to make a perfect website then I somehow feel, this change is needed because even when I remove the bookmarks bar then also some part of the text is hidden such as the " Y " in the text " everyone ". The rest depends on the Maintainer.

**Comment by PeerRich** [comment] 2023-10-17 10:42
this is fine

**Closed by PeerRich** 2023-10-17 10:42 UTC
Labels: 🐛 bug, 🧹 Improvements
