### ISSUE TITLE
[CAL-2183] Fix sluggish parts of event type overview

### ISSUE THREAD

**Issue by rene-mueller** [calcom/cal.com#9741] opened 2023-06-23 09:06 UTC
### Issue Summary

Using the event type overview is very sluggish. When I select an event type, it takes at least 4 seconds for the event type to load. A skeleton should be used here to give the user direct feedback that something is about to happen.

<sub>[CAL-2183](https://linear.app/calcom/issue/CAL-2183/fix-sluggish-parts-of-event-type-overview)</sub>

**Comment by rene-mueller** [comment] 2023-06-23 09:06
CC @PeerRich

**Comment by PeerRich** [comment] 2023-06-26 20:20
@roae @keithwillcode lets focus on this while looking into that endpoint

**Comment by leog** [comment] 2023-07-19 16:20
@keithwillcode @PeerRich Is this a duplicate of #9944?

**Comment by PeerRich** [comment] 2023-07-19 16:21
yep but #9944 is closed already? is event-type view faster now?

**Comment by leog** [comment] 2023-07-19 18:06
> yep but #9944 is closed already? is event-type view faster now?

@PeerRich I think event-type page feels better yeah

**Comment by satya-nishanth** [comment] 2023-07-20 05:37
> > yep but #9944 is closed already? is event-type view faster now?
> 
> @PeerRich I think event-type page feels better yeah

Yes definitely better and now it also shows progress, which is good feedback for the user.

**Comment by leog** [comment] 2023-07-21 13:34
Tackled by #9944.

**Closed by leog** 2023-07-21 13:34 UTC
Labels: 🧹 Improvements, High priority, event-types
