### ISSUE TITLE
Hide team members from each other

### ISSUE THREAD

**Issue by crazywithluck** [calcom/cal.com#9798] opened 2023-06-26 11:08 UTC
Due to GDPR, we need to hide team members from each other. Only admins/owners should have access to view this. At a minimum, hiding team members’ emails would be great, but ideally we would be able to hide the name as well.

similar to this request: https://github.com/calcom/cal.com/issues/1571

**Comment by PeerRich** [comment] 2023-06-26 12:02
we have this on the roadmap and plan to ship this soon

**Comment by PeerRich** [comment] 2023-06-26 12:02
@sean-brydon you were looking in a chatbox for admins, right?

**Comment by crazywithluck** [comment] 2023-06-26 12:03
Hi,

That’s great news thanks!

Do you have a rough eta on when this would be delivered? As this would be pivotal for us to start using Cal.com in our team

Thanks, Sanju

**Comment by PeerRich** [comment] 2023-06-26 12:04
very soon!

**Comment by PeerRich** [comment] 2023-06-26 12:05
this is a duplicate of https://github.com/calcom/cal.com/issues/8974. closing and assigning someone on the og issue

**Closed by PeerRich** 2023-06-26 12:05 UTC
Labels: ✨ feature

**Comment by crazywithluck** [comment] 2023-06-26 12:09
Would you be able to update me when this is released if possible? Would be easier than checking every day!

Also, is it possible to disable the default ‘reschedule’ and ‘cancel’ emails that are sent to participants? We’ve only been able to do this with the ‘booking’ so far.

Essentially, we need to try and hide attendee and hosts’ emails from each other, but these appear if either party tries to reschedule or cancel. We have set up custom workflows which send emails that hide this information, but the default email is still being sent as well.

Thanks, Sanju
