### ISSUE TITLE
blog is broken?

### ISSUE THREAD

**Issue by mmkal** [calcom/cal.com#11657] opened 2023-10-02 16:11 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Going to "Open Startup" from the `/open` page is erroring with `Application error: a client-side exception has occurred (see the browser console for more information).`

### Steps to Reproduce (edited)

1. Go to https://cal.com/open
2. Click "Open Startup"
3. See bug

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I wanted to read the open startup blog post.

### Actual Results

- 500

### Expected Results

- blog post

### Technical details

- Browser version Chrome Version 117.0.5938.92 (Official Build) (x86_64) but seems like a server error
- Node.js version N/A

### Evidence

<img width="1792" alt="image" src="https://github.com/calcom/cal.com/assets/15040698/686df669-7ebc-4442-8128-437d967b391d">

**Comment by rahulpandey70** [comment] 2023-10-02 16:20
@mmkal this is working fine

**Comment by ErrolFernandes** [comment] 2023-10-02 16:44
This is not working fine.
It is occurring when
1. we click https://cal.com/blog/open-startup
2. click any button
3. go back to the blog (https://cal.com/blog/open-startup)
![Screenshot (3)](https://github.com/calcom/cal.com/assets/83249470/6cfdae5a-8073-44e9-9be8-4db06d959e80)

**Comment by rahulpandey70** [comment] 2023-10-02 17:23
yes, first time I was simply visit this https://cal.com/blog/open-startup, this error occur while we trying go previous page.

**Comment by mmkal** [comment] 2023-10-02 17:35
Yeah my repro steps might have been wrong.

1. Go to https://cal.com/open
2. Click the "Open Startup" link

**Comment by ItIsOHM** [comment] 2023-10-02 18:45
I'd like to work on this issue, if it's alright for a beginner like me 😅
Can someone help me where I should look to fix this? I tried searching for keywords from the article in the codebase but found nothing useful.

**Comment by PeerRich** [comment] 2023-10-05 13:37
cannot reproduce 🤔

**Comment by PeerRich** [comment] 2023-10-05 13:38
ah, yes. when coming from cal.com/open it breaks

**Comment by Siddharth-2382** [comment] 2023-10-06 11:48
Tried on two different browsers and cannot reproduce.

**Comment by PeerRich** [comment] 2023-10-06 11:59
should be fixed now

**Closed by PeerRich** 2023-10-06 11:59 UTC
Labels: 🐛 bug, app-store
