### ISSUE TITLE
[CAL-1098] 50-minute slot not calculated correctly

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7168] opened 2023-02-17 08:33 UTC
Last slot of the day is 40 minutes and is causing the "No available users found"

This user has availability until 18:00 on that day.

17:20 is not supposed to be there

![Screenshot 2023-02-17 at 09.12.15.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/904dec5e-a33d-4788-93f9-020bbd1a2f15/e4216281-ffd8-461b-a6d4-0d8e6f85471c)

![Screenshot 2023-02-17 at 09.13.46.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c14519a2-1222-4e31-a3c3-c162e2d47a94/7a506d9d-62c8-4aad-a5fa-9d476566a583)

![Screenshot 2023-02-17 at 09.28.18.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/043afb7b-2f00-4912-b181-f0352bffa27b/21413d66-485c-44e8-96f4-2d650a613b4f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1098](https://linear.app/calcom/issue/CAL-1098/50-minute-slot-not-calculated-correctly)</sub>

**Comment by Udit-takkar** [comment] 2023-03-03 20:56
duplicate of https://github.com/calcom/cal.com/issues/7167

**Closed by Udit-takkar** 2023-03-03 20:56 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, High priority
