### ISSUE TITLE
[CAL-12233] If i dont give access to my google calender im getting this shown on screen

### ISSUE THREAD

**Issue by lohith-kandibanda** [calcom/cal.com#12233] opened 2023-11-05 10:53 UTC
### Issue Summary

this is my new account and when im signing up in the step 2, when i choose google calender and clicked next then it asked to options i selected neither one and clicked next, i was asked to confirm after clicking conform i got this message on screen(screenshot provided below).

### Steps to Reproduce

1.  try sign up in new account
2. set username timezone
3. 5 steps will be provided for you
4. in step 2 when given calenders option google,outlook,etc.. click only google
5. it will ask for access dont give access and continue 
6. you will get the bug

wheni click on continue
![image](https://github.com/calcom/cal.com/assets/133104253/a0242a37-47e5-40fc-8822-419ba4c752f5)

### Actual Results

![image](https://github.com/calcom/cal.com/assets/133104253/49b9f09a-4ab2-460e-bcda-d1daa7df35c9)

### Expected Results
 it should ask me again for access or choose another calender

**Comment by Udit-takkar** [comment] 2023-12-07 07:39
duplicate of https://github.com/calcom/cal.com/issues/12602

**Closed by Udit-takkar** 2023-12-07 07:39 UTC
Labels: 🐛 bug, Medium priority, calendar-apps
