### ISSUE TITLE
Figure out why "Nameless User" happens

### ISSUE THREAD

**Issue by ThangHuuVu** [calcom/cal.com#2013] opened 2022-03-01 07:24 UTC
### Issue Summary

~~"Nameless User" alt is too long, making it hard to see the rest of the component.~~

Find out why "Nameless User" is shown every now and then

### Steps to Reproduce

1. Log in as a nameless user.
2. Observe the bottom of the navbar.
3. Instead of a proper default image, alt text is shown.

![Screen Shot 2022-03-01 at 10 28 28](https://user-images.githubusercontent.com/31528554/156123242-8f639c49-0e3c-45ab-bb53-1cc1e9d1604d.png)

**Comment by milospuac** [comment] 2022-03-01 08:34
Thank you for reaching out! Our team is on it

**Comment by ThangHuuVu** [comment] 2022-03-01 09:01
@milospuac I'd love to help in the linked PR, if possible :D

**Comment by PeerRich** [comment] 2022-03-02 21:24
"Nameless User" is actually a bug  – a placeholder when a user is not authorized. We should instead find out why this is happening. I think @alishaz-polymath build this?

**Comment by alishaz-polymath** [comment] 2022-03-02 21:32
@PeerRich I have worked on the user image (avatar component) in shell, yes, but I didn't build the logic here. Although, I know why this is happening. The avatar component would work when it is fed a username, and when it isn't, we get the alt which is set to "Nameless User". We can simply create a better(and smaller) alt for this, and it should be fine. In the case above, username is likely not set (or is empty/null)

**Comment by PeerRich** [comment] 2022-03-02 21:57
usernames should never be set to empty/null/undefined in the first place. lets debug why that happened and how we can prevent that

**Comment by alishaz-polymath** [comment] 2022-03-03 05:06
@PeerRich I think I have only seen this when the user session expires and the user is still at the logged in page, the message says "unauthorized" while the Shell's user data says "Nameless User" et al.
The only time when it would say "Nameless User" is when the session data is unavailable, or if someone tinkers with changing the username to blank/null explicitly in the DB (since that is not allowed from the front end/UI)
@ThangHuuVu Can you please suggest if you can create a `nameless user` post the registration process in the production, or if you did this in dev?

**Comment by ThangHuuVu** [comment] 2022-03-03 05:17
@alishaz-polymath I can reproduce this consistently on production ever since I registered a new account without claiming a username. Whenever I log back in, I see "Nameless User". I haven't been able to debug this in dev yet because I don't have a required commercial license 🤔

**Comment by alishaz-polymath** [comment] 2022-03-03 05:29
> @alishaz-polymath I can reproduce this consistently on production ever since I registered a new account without claiming a username. Whenever I log back in, I see "Nameless User". I haven't been able to debug this (the sign up flow) in dev yet because I don't have a required commercial license 🤔 I can only create a user without a username in DB and check the display

Okay, thanks. I'd say the issue in this case would be allowing to not claim a username during the registration process itself. If we are set to allow it, we'd need to update how we handle it, else we should just not allow it in the first place. Thoughts @PeerRich ?

**Comment by PeerRich** [comment] 2022-03-03 07:55
> > @alishaz-polymath I can reproduce this consistently on production ever since I registered a new account without claiming a username. Whenever I log back in, I see "Nameless User". I haven't been able to debug this (the sign up flow) in dev yet because I don't have a required commercial license 🤔 I can only create a user without a username in DB and check the display
> 
> 
> 
> Okay, thanks. I'd say the issue in this case would be allowing to not claim a username during the registration process itself. If we are set to allow it, we'd need to update how we handle it, else we should just not allow it in the first place. Thoughts @PeerRich ?

lets discuss in engineering channel. 

btw. what he's experiencing is on self-hosted, not cal.com

could be many things

**Comment by ThangHuuVu** [comment] 2022-03-03 08:04
> what he's experiencing is on self-hosted, not cal.com

@PeerRich FYI I experienced this on cal.com when I registered, not self-hosted. Sorry for not being clear about it at first.

**Comment by PeerRich** [comment] 2022-03-03 10:13
> > what he's experiencing is on self-hosted, not cal.com
> 
> 
> 
> @PeerRich FYI I experienced this on cal.com when I registered, not self-hosted. Sorry for not being clear about it at first. 

oh! weird

**Comment by agustif** [comment] 2022-03-06 13:40
> > > what he's experiencing is on self-hosted, not cal.com
> > 
> > 
> > 
> > @PeerRich FYI I experienced this on cal.com when I registered, not self-hosted. Sorry for not being clear about it at first. 
> 
> oh! weird

Yeah I was nameless for a while too on cal.com when signing up.

**Comment by PeerRich** [comment] 2022-03-06 18:41
> > > > what he's experiencing is on self-hosted, not cal.com
> > > 
> > > 
> > > 
> > > @PeerRich FYI I experienced this on cal.com when I registered, not self-hosted. Sorry for not being clear about it at first. 
> > 
> > oh! weird
> 
> Yeah I was nameless for a while too on cal.com when signing up.
> 

any clue why? thats a much higher priority than the alt tag

**Comment by agustif** [comment] 2022-03-06 22:26
> > > > > what he's experiencing is on self-hosted, not cal.com
> > > > 
> > > > 
> > > > @PeerRich FYI I experienced this on cal.com when I registered, not self-hosted. Sorry for not being clear about it at first.
> > > 
> > > 
> > > oh! weird
> > 
> > 
> > Yeah I was nameless for a while too on cal.com when signing up.
> 
> any clue why? thats a much higher priority than the alt tag

It's possible I had an old account pre-renaming that had no username? I just was able to signup without choosing one I think. I had to set it up in settings. Will try to reproduce with a fresh new account

**Comment by PeerRich** [comment] 2022-03-09 10:02
renamed ticket to "Figure out why Nameless User" happens

**Comment by alishaz-polymath** [comment] 2022-03-09 10:31
I think @zomars mentioned this being a Normal Behavior
```
It is normal behavior. Primarily because of the premium username workflow:

1. User signups with a premium username
2. The user is created in prisma without the username set to prevent poaching
3. A stripe checkout session is generated with the desired username saved as metadata.
4. If the payment intent is successful, Stripe sends a webhook to our cal.com/api/stripe/webhook endpoint.
5. In the webhook we fetch the paid for username from the Stripe metadata and assign it to the now premium username in Prisma.
```

**Comment by alishaz-polymath** [comment] 2022-03-09 10:33
What we can do to improve this (off the top of my head) is to only allow registration with premium usernames **after** the stripe payment intent is successful, otherwise fail the registration process due to pending payment. But I'm not sure how good of a flow this is, just that the nameless user issue happening because of the above flow would be resolved this way

**Comment by agustif** [comment] 2022-03-09 11:58
I propose to add a verification check for username.

If the user is loggedIn and doesn't have a username setup, we ask him to set up one (either free or premium and pay) I think we wanted to re-implement paying for premium via stripe checkout in-app either way too, so it would be good if in any case where you end up nameless, the webapp prompts you to update it.

I also wonder if we want to limit how many names one can change in a period of time, or I can just change my username everytime I feel like it?

**Comment by alishaz-polymath** [comment] 2022-03-09 12:32
> I propose to add a verification check for username.
> 
> If the user is loggedIn and doesn't have a username setup, we ask him to set up one (either free or premium and pay) I think we wanted to re-implement paying for premium via stripe checkout in-app either way too, so it would be good if in any case where you end up nameless, the webapp prompts you to update it.
> 

I like it 👍

**Comment by PeerRich** [comment] 2022-03-14 23:45
@agustif @alishaz-polymath has this been resolved?

**Comment by agustif** [comment] 2022-03-14 23:52
Not really, should I work on a fix for this? The problem is I don't know the underlying problem, I think I remember @zomars mentioned this being an expected behaviour.

I think the problem is if I ask for premium, but don't pay, I get signup, but without a username.

Btw, on onbarding we ask for the name, but not the username, we could add it there too, but I don't know if it would catch all cases.

Should I work in something more defensive, that checks the session, and if it detects lack of username if shows up a modal asking you to set it up? or redirects to profile settings?

**Comment by PeerRich** [comment] 2022-03-16 20:40
is this still happening sometimes? havent seen it being reported lately

**Comment by alishaz-polymath** [comment] 2022-05-17 08:42
The fallback Avatar is working well, so that's good news. But the Nameless user still happens and one way for that to happen is when a new `Team Member` is invited to a team, but they don't have an account with Cal yet, there is no username information associated with their account. 
The best way to overcome this and any other potential way of having no username is through mandating a username selection during the onboarding process if the user doesn't have a username info in the DB.

**Comment by PeerRich** [comment] 2022-06-10 09:28
looks to be fixed?

**Closed by PeerRich** 2022-06-10 09:28 UTC
Labels: 🐛 bug
