### ISSUE TITLE
Sync existing events / bookings into a new google calendar sync

### ISSUE THREAD

**Issue by ecrode** [calcom/cal.com#12012] opened 2023-10-20 04:10 UTC
### Is your proposal related to a problem?
Events / bookings made prior to google calendar sync being setup do not appear on the google calendar.

### Describe the solution you'd like
After the new calendar is setup, any future bookings would be reevaluated as to be added to the newly setup calendar.

### Describe alternatives you've considered
I've tried to change location of the meeting, hoping the change would trigger a new sync, I may need to edit the time (twice), but that may generate large number of unneeded email notifications.

**Comment by PeerRich** [comment] 2023-10-20 13:50
this is in the making and a duplicate of https://github.com/calcom/cal.com/issues/11524

**Closed by PeerRich** 2023-10-20 13:50 UTC
Labels: ✨ feature, 🚨 needs approval
