### ISSUE TITLE
CalDav (Beta) icon should be inverted in Dark theme

### ISSUE THREAD

**Issue by Shubhdeep12** [calcom/cal.com#8686] opened 2023-05-05 08:19 UTC
Found a bug? Please fill out the sections below. 👍

### CalDav (Beta) icon should be inverted in the Dark theme
![image](https://user-images.githubusercontent.com/43654389/236397460-08f5ec7b-98c4-4fcf-9e5a-36d6e3683004.png)

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Select Dark Theme
2. Go to Apps

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by 9520prashant** [comment] 2023-05-05 08:31
Yes this is valid issue

**Comment by pawanssingh456** [comment] 2023-05-05 10:44
Seems like this issue is already fixed.

<img width="713" alt="Screenshot 2023-05-05 at 4 13 04 PM" src="https://user-images.githubusercontent.com/32010243/236437839-ac1409fe-517a-4c74-b771-662e078a3f8d.png">

**Comment by 9520prashant** [comment] 2023-05-05 12:40
Ohh then no need to fix it please close it

**Comment by rahilansari261** [comment] 2023-05-06 18:20
This issue related to #8111 
And it is resolved as of now 
They have added a condition for caldav app specifically.
![Screenshot_2023-05-06-23-45-57-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/12849916/236640605-51ff0c76-fc0d-4cba-9cb7-f57916fffc7d.jpg)

**Comment by 9520prashant** [comment] 2023-05-06 18:23
But this is not a bug I thing everything is pretty fine

**Comment by rahilansari261** [comment] 2023-05-07 04:57
@9520prashant agreed :)

**Comment by 9520prashant** [comment] 2023-05-07 05:41
Great 👍🏻

**Closed** 2023-05-07 05:40 UTC
Labels: 🐛 bug
