### ISSUE TITLE
No meeting times show up after removing all Availability schedules

### ISSUE THREAD

**Issue by ethanngoh** [calcom/cal.com#6718] opened 2023-01-26 06:39 UTC
### Issue Summary

When no availability schedule exists in your cal.com account, one's calendar is completely broken.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/880610/214772208-e426214a-5d85-4d26-a0f8-483b70af8959.png">

### Steps to Reproduce

1. Log into cal.com account
2. Click Availability tab in left sidebar
3. Delete all availability schedules (including default)
4. Navigate to cal.com/username page to attempt to schedule meeting

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I keep my availability as a separate calendar in Google Calendar and manage it there. I do this because I travel between US and APAC time zones, and my personal calendar is a centralized source of truth for what times I'm likely to be awake.

As a workaround, I had to create an availability schedule that spanned the entire day + week. 

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment] 2023-01-26 11:41
what would you recommend to show there instead? I agree this infinite loading screen is not a good idea. 

(a) should we prevent deleting all availabilities?

(b) should we show an empty screen on the booking page?

**Comment by PeerRich** [comment] 2023-01-26 11:41
i marked this as low because its not common that people have no availability

**Comment by chrisbenti** [comment] 2023-01-28 01:46
Hi Peer, thanks for taking a look. Following along because I'm in a similar boat to Ethan (I hop timezones a lot and prefer to manage my availability within Google calendar).

For example, this is my current availability setup:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/632557/215234822-0cd15cd7-b1a6-4f09-93f8-6e42acd91357.png">

I think there are two major issues here:
## 1: Can there be support for infinite availability*?
*I would define infinite availability as always available when no calendar conflicts exist, without the need for my above solution. 

Either by way of an explicit option OR by assuming infinite availability when all availabilities are removed.

## 2: What happens when you try to delete all availabilities?
The answer to this question is dependent on the answer to the one above, and is the same as the one you asked. 

In either case, I think the best solution is one that prevents the booking page from breaking is the best. So if there's no interest in supporting infinite availability, I would just suggest preventing someone from deleting availabilities that are used by existing events.

**Comment by PeerRich** [comment] 2023-01-28 22:28
copying @emrysal here. I wonder how other scheduling tools do it.

just to get this right: how do you stop people from booking before lets say 12:00 without having an availability? do you have blocking events in your google calendar?

**Comment by chrisbenti** [comment] 2023-01-29 01:58
Exactly, I maintain blocking events in my google calendar:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/632557/215299933-b515e498-852a-40ae-b5b0-62039232b496.png">

I just maintain a separate calendar exclusively for availability that cal.com is configured to consider me busy during, and then I hide that calendar most of the time.

**Comment by PeerRich** [comment] 2023-01-29 09:19
oh wow damn. i havent seen many people do this.

doesnt the 12:00-11:59 approach work?

**Comment by chrisbenti** [comment] 2023-01-29 10:41
Switching to 24h hour time to demonstrate:

The 0:00-23:59 has one issue, in that meetings that straddle 23:59-0:00 minute in your availability timezone cannot be scheduled in my testing of the feature.

I.E if my timezone is set to Singapore, but I will be in NYC during the summer (12 hour difference during NYC DST), people will be unable to schedule meetings that straddle over noon with me. 

This hasn't been a problem for me as the majority of the time I'm scheduling 30 minute calls, but for longer meetings the issue is more exposed.

**Comment by PeerRich** [comment] 2023-01-29 11:42
i think its better to use the current UI as it kinda makes sense already. i think more people will be confused by "infinite availability"

i do think deleting and having no schedule should just enable every time slot, that could be a good fix, @emrysal

**Comment by emrysal** [comment] 2023-07-12 22:37
We no longer support removing all availabilities, if no availability is desired you can turn off all days and achieve this. But in effect this fixes this issue. Behaviour should also be better nowadays for "infinite" availability, but future improvements are possible.

**Closed by emrysal** 2023-07-12 22:37 UTC
Labels: 🧹 Improvements, Low priority, bookings
