### ISSUE TITLE
[CAL-1063] Booking Confirmation Email not Loading Variables

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#7097] opened 2023-02-14 18:35 UTC
![CleanShot 2023-02-14 at 10.30.23@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7e1178cd-d6d1-4879-806e-a0a3629f685c/4cd80f0f-86db-4bf5-a1b3-ed5d90250a51)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1063](https://linear.app/calcom/issue/CAL-1063/booking-confirmation-email-not-loading-variables)</sub>

**Comment by imskr** [comment] 2023-02-14 18:38
Can I work on this?

**Comment by PeerRich** [comment] 2023-02-15 12:50
this is already in review

**Comment by imskr** [comment] 2023-02-15 15:07
No problem. I asked when no one was assigned

**Comment by G3root** [comment] 2023-02-15 16:51
> No problem. I asked when no one was assigned

hey sorry for not communicating while taking up the issue 🙏🏼  . i self assigned this because this was a regression

**Closed** 2023-02-15 17:49 UTC
Labels: 🐛 bug, ✅ good first issue
