### ISSUE TITLE
[CAL-1229] Bug with Apple Calendar

### ISSUE THREAD

**Issue by seem2810** [calcom/cal.com#7619] opened 2023-03-09 08:28 UTC
I've use as primary calendar a nextcloud instance.
To not handle any private entry as duplicate in this nextcloud calendar, I've added my private icloud account to manage it.
I had to enable and disable the calendars in random order and i a lot of tries to get all calendars for blocking checks running..

<sub>[CAL-1229](https://linear.app/calcom/issue/CAL-1229/bug-with-apple-calendar)</sub>

**Comment by PeerRich** [comment] 2023-03-09 22:53
nextcloud is not supported yet

**Comment by PeerRich** [comment] 2023-03-10 20:53
@alishaz-polymath any insights on apple calendar issues?

**Comment by alishaz-polymath** [comment] 2023-03-11 00:34
It does work with apple calendar though, in general at least. @seem2810 could you please provide more information on what's not working, where do you create the events that aren't being understood in the freebusy slots and if there's a consistent theme on what's blocked (if any slot) and what isnt?

Any steps we could take to recreate the issue on our end would be greatly helpful for us to identify the cause of your issues and speed up the fix tremendously 🙏

**Comment by alishaz-polymath** [comment] 2023-03-31 10:26
Fixed in PR #7934 and being improved in functionality in the PR #8031

**Closed by alishaz-polymath** 2023-03-31 10:26 UTC
Labels: 👩‍🔬 needs investigation, linear, Medium priority, 3 points, 1 points

**Comment by seem2810** [comment] 2023-04-24 10:46
> Fixed in PR #7934 and being improved in functionality in the PR #8031

Thanks! 
I'll test as soon it's released

**Comment by alishaz-polymath** [comment] 2023-04-24 10:47
It is released @seem2810 
Please test and confirm🙌
