### ISSUE TITLE
Cant post to bookings endpoint - status 500

### ISSUE THREAD

**Issue by virtcaio** [calcom/cal.com#14226] opened 2024-03-27 11:31 UTC
Using the cal.com website.

Seems that is a bug happened with several others.

**Comment by jonezy35** [comment] 2024-04-11 01:09
Any update on this? I'm having the same issue

**Comment by PeerRich** [comment] 2024-05-16 13:30
can you paste the call that you are making etc.? We need more information

**Comment by PeerRich** [comment] 2024-05-16 13:31
duplicate of https://github.com/calcom/cal.com/issues/14735

**Closed by PeerRich** 2024-05-16 13:31 UTC
Labels: 🐛 bug
