### ISSUE TITLE
Video settings link in the little popover menu is not clickable in the call room

### ISSUE THREAD

**Issue by smakosh** [calcom/cal.com#15397] opened 2024-06-10 17:00 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Video settings link in the little popover menu is not clickable in the call room

### Steps to Reproduce

1. Join a call
2. Click on the video icon to open the popup menu
3. Try clicking on Video Settings

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- It's not clickable while the other items are clickable

### Expected Results

- It should open the video settings modal

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence
![Screenshot 2024-06-10 at 6 54 29 PM](https://github.com/calcom/cal.com/assets/20082141/e6d4e05e-fb40-4a44-8903-732c174e1a7f)

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

**Comment by ubaish01** [comment] 2024-06-10 19:23
![ss](https://github.com/calcom/cal.com/assets/109113347/958d2c8f-53b6-4490-b609-79956fde1100)
Hi @smakosh , Unable to reproduce the issue. Seems like it works as expected. 
I am using brave  browser, windows 11.

**Comment by smakosh** [comment] 2024-06-10 19:47
> ![ss](https://private-user-images.githubusercontent.com/109113347/338315193-958d2c8f-53b6-4490-b609-79956fde1100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDkxMjQsIm5iZiI6MTcxODA0ODgyNCwicGF0aCI6Ii8xMDkxMTMzNDcvMzM4MzE1MTkzLTk1OGQyYzhmLTUzYjYtNDQ5MC1iNjA5LTc5OTU2ZmRlMTEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxOTQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTVlY2YxMTkzNGFmMjRmY2QwZDk0ZjZjZTM5NGYzMmU4ZGI2NjE3MTZkY2MzMzY5ZDM4N2FiNzAzMzYzMGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zt6ycPiCrWCtfQD17vo-aa3paOyB8cYqOKe-k4g6H6M) Hi @smakosh , Unable to reproduce the issue. Seems like it works as expected. I am using brave browser, windows 11.

Hey! it happened on my macbook pro on Chrome

**Comment by PeerRich** [comment] 2024-06-10 20:04
works on my end. closing, feel free to open a new issue with a reproducable loom.com video

**Closed by PeerRich** 2024-06-10 20:04 UTC
Labels: 🐛 bug, cal video

**Comment by smakosh** [comment] 2024-06-10 22:02
Uploading Screen Recording 2024-06-11 at 12.00.25 AM.mov…

Tricky
