### ISSUE TITLE
When giving access to my Google Calendar, it redirects me to undefined/integrations (cal.com)

### ISSUE THREAD

**Issue by gjvalentin** [calcom/cal.com#1971] opened 2022-02-24 11:24 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When connecting my Google Calendar and when I give access to Cal.com, it redirected me to undefined/integrations.
The integration is successful though.

### Steps to Reproduce

1. Go to integrations
2. Click Connect Google Calendar
3. Allow Access to Cal.com
4. And lick Continue
5. It should redirect you to undefined/integrations

**Comment by amvara-adrian** [comment] 2022-02-24 12:45
Yesterday I was working with "cometa" when I discovered the same issue that when connecting Outlook with [cal.com](http://cal.com/) the login redirect returned undefined in the URL

### Steps to reproduce

1. Login on [app.cal.com](http://app.cal.com/)
2. Go to integrations
3. Connect outlook account
4. Login outlook (optional if you are already logged in)
5. Wait for redirect https://undefined/integrations
6. Browser shows: "This site can't be reached"

**Comment by PeerRich** [comment] 2022-02-24 18:21
did you set BASE_URL in .env?

@agustif is there a way to do this without BASE_URL?

**Comment by agustif** [comment] 2022-02-24 18:51
> did you set BASE_URL in .env?
> 
> @agustif is there a way to do this without BASE_URL?

I will check it out. But if this is on cal.com Base url should br available as env var right?

**Comment by PeerRich** [comment] 2022-02-24 19:10
> > did you set BASE_URL in .env?
> > 
> > @agustif is there a way to do this without BASE_URL?
> 
> I will check it out. But if this is on cal.com Base url should br available as env var right?

i think its self hosted no?

**Comment by philippdormann** [comment] 2022-02-28 14:02
can confirm I had the same error 3 days ago.

seems to be fixed now.

**Comment by agustif** [comment] 2022-02-28 16:30
Can you guys @philippdormann @amvara-adrian @gjvalentin  try again if you were experiencing this in cal.com (not self-hosted)

We shipped a couple fixes during the weekend that should have solved this issue. Please do let me know so I can either close it or keep investigating!

Thanks

**Comment by philippdormann** [comment] 2022-02-28 16:36
> seems to be fixed now.

🙂😉

**Comment by amvara-adrian** [comment] 2022-03-01 09:29
@agustif I confirm thats works

**Closed** 2022-03-01 09:49 UTC

**Comment by sw506** [comment] 2022-03-01 12:09
@PeerRich still not working in my self-hosted instance of cal, have installed the latest patches. Still getting redirected to undefined/integrations like amvara-adrian when I add a Outlook-Calender after the MS-Login prompt, even though the calendar is added.

**Comment by PeerRich** [comment] 2022-03-01 12:15
> @PeerRich still not working in my self-hosted instance of cal, have installed the latest patches. Still getting redirected to undefined/integrations like amvara-adrian when I add a Outlook-Calender after the MS-Login prompt, even though the calendar is added.

do you have BASE_URL and NEXT_BASE_URL in env?

**Comment by sw506** [comment] 2022-03-01 13:25
> do you have BASE_URL and NEXT_BASE_URL in env?
Have set BASE_URL, NEXT_PUBLIC_APP_URL like  advised in .env.example

**Comment by agustif** [comment] 2022-03-01 14:09
> > do you have BASE_URL and NEXT_BASE_URL in env?
> 
> Have set BASE_URL and NEXT_PUBLIC_APP_URL like advised in .env.example

Hey sorry there I actually named the new env var NEXT_PUBLIC_BASE_URL, can you try with that one. Maybe we need to change it to the default NEXT_PUBLIC_APP_URL though if it doesn't interfere

**Comment by yederlv** [comment] 2022-05-12 18:24
Hi everyone

someone has solved this issue in the self hosted version ?

**Comment by sw506** [comment] 2022-05-13 08:06
I did a clean reinstall, then it worked
