### ISSUE TITLE
[CAL-419] Intercom app

### ISSUE THREAD

**Issue by leog** [calcom/cal.com#5617] opened 2022-11-21 17:33 UTC
Create an Intercom app similar to Calendly: [https://www.intercom.com/app-store/apps/calendly](https://www.intercom.com/app-store/apps/calendly)

> From [SyncLinear.com](https://synclinear.com) | [CAL-419](https://linear.app/calcom/issue/CAL-419/intercom-app)

**Comment by PeerRich** [comment] 2022-11-21 19:15
duplicate of https://github.com/calcom/cal.com/issues/1490

**Closed by PeerRich** 2022-11-21 19:15 UTC
Labels: 🎨 needs design
