### ISSUE TITLE
Video Call UI Bug 

### ISSUE THREAD

**Issue by dfordp** [calcom/cal.com#16450] opened 2024-09-01 14:29 UTC
### Issue Summary

I was in a meeting today in the cal video meet. I noticed a minor 

### Steps to Reproduce

1. Join any video Call Meeting 
2. The Sheet Doesn't Close Properly and Blocks the Video on/off Switch Button

### Expected behavior

It should not cover the said button.

### Screenshots

![image](https://github.com/user-attachments/assets/f6b27bc2-3425-49af-b5ff-e7ed00a5fe26)

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS: Windoms
- Node: v20.11.1
- npm: 10.2.1
```

**Comment by ThakurAnkitSingh** [comment] 2024-09-02 07:40
I think it should not cover the turn-on/off button and the upper part. Today I will work on it, Let's see I can contribute some...

**Comment by dfordp** [comment] 2024-09-02 07:49
@ThakurAnkitSingh I have raised a pr regarding the same

**Comment by ThakurAnkitSingh** [comment] 2024-09-02 07:55
> @ThakurAnkitSingh I have raised a pr regarding the same

Okay, That's great

**Comment by Udit-takkar** [comment] 2024-09-02 11:59
@dfordp what is your screen size?

**Comment by dfordp** [comment] 2024-09-02 14:50
> @dfordp what is your screen size?

15 inches

**Comment by Amit91848** [comment] 2024-09-17 15:21
Closing it because this issue cannot be reproduced. Please add video proof in case you are still facing it so that we can correctly reproduce and rectify the underlying issue.


https://github.com/user-attachments/assets/3981868a-c0ae-4875-a8de-dd439aeee2da

**Closed by Amit91848** 2024-09-17 15:21 UTC
Labels: 🐛 bug, cal video
