### ISSUE TITLE
Email not dispatched on successful payment

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#11042] opened 2023-08-31 11:06 UTC
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Install stripe app and connect user.
2. Enable stripe in event-type
3. Create a booking for that event-type.

[Video](https://youtu.be/i_C_CYdIa2Q)

**Comment by alannnc** [comment] 2023-09-14 03:59
Hey @shivamklr right now both payment apps (paypal, stripe) require some sort of setup since payments are confirmed via webhook to us.
For stripe we use stripe-cli so you can listen and forward webhooks in your localhost.
And paypal is a simpler one that only requires modifying a line of code so the webhook can be pointed to your url but it has to be a public one you can use ngrok for that.

Happy to record a loom of the setup if required. Just let me know.

In the meanwhile I'll be closing this as I think it's not a bug.

**Closed by alannnc** 2023-09-14 03:59 UTC
Labels: 🐛 bug, High priority, billing, emails

**Comment by staminna** [comment] 2023-10-19 01:44
I am instered in such solution.
@alannnc Can you help or @shivamklr did you manage to find the solution?
I can't actually retrieve the email sent from smtp.example.pt which is nowhere I could find on docker instalation.
