### ISSUE TITLE
[CAL-2683] /event type settings / advanced / add to calendar input has double label & helper text

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#12268] opened 2023-11-07 16:16 UTC
currently

![CleanShot 2023-11-07 at 16.10.51@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3974d7d9-f579-474f-b48b-893f66f23132/7e9a75a5-a3f9-4987-af4c-592ef501f52c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy8zOTc0ZDdkOS1mNTc5LTQ3NGYtYjQ4Yi04OTNmNjZmMjMxMzIvN2U5YTc1YTUtYTNmOS00OTg3LWFmNGMtNTkyZWY1MDFmNTJjIiwiaWF0IjoxNjk5MzczNzY4LCJleHAiOjE2OTk0NjAxNjh9.YHg2NYDfgQHF040OOBIf8qxlHkkiAXKijqaMo_TXhZw)

Should be

![CleanShot 2023-11-07 at 16.13.58@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/abd298bc-523e-4934-8b20-95bae8c0bf17/03638f2f-c566-4eb8-9500-d6d201f47d08?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hYmQyOThiYy01MjNlLTQ5MzQtOGIyMC05NWJhZThjMGJmMTcvMDM2MzhmMmYtYzU2Ni00ZWI4LTk1MDAtZDZkMjAxZjQ3ZDA4IiwiaWF0IjoxNjk5MzczNzY4LCJleHAiOjE2OTk0NjAxNjh9.NsPd0sV-9TcjPEaf5CDcmqCR5GL_dNbY7F0tiZvCyO0)

Looks like it was pasted from the general settings area with an additional label & helper text

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2683](https://linear.app/calcom/issue/CAL-2683/event-type-settings-advanced-add-to-calendar-input-has-double-label)</sub>

**Comment by Udit-takkar** [comment] 2023-11-08 09:15
duplicate of https://github.com/calcom/cal.com/issues/11988

**Closed by Udit-takkar** 2023-11-08 09:15 UTC
Labels: 🐛 bug, ⚡ Quick Wins, ui, 🚨 needs approval
