### ISSUE TITLE
US-based timezone showing 24-hour time by default

### ISSUE THREAD

**Issue by timfee** [calcom/cal.com#4533] opened 2022-09-16 16:49 UTC
This might be similar to #3908 -- but see my URL at https://cal.com/tim/15?date=2022-09-17

As an American on a US IP, I'd expect this to be 12-hour time. It's been like this for awhile.

<img width="1092" alt="Screenshot_2022-09-16_09-09-16_2okMmw1P" src="https://user-images.githubusercontent.com/3246342/190689488-2e7e16f0-1cbc-426c-9b41-5168c4c0a437.png">

**Comment by timfee** [comment] 2022-09-16 16:54
FWIW, this is my configuration as a Cal.com user:

<img width="859" alt="Screenshot_2022-09-16_09-09-56_r1o4JTgh" src="https://user-images.githubusercontent.com/3246342/190690195-2c1acef6-ddb1-43ad-9e3c-1efaeed1318e.png">

**Comment by PeerRich** [comment] 2022-09-16 20:15
i believe this was fixed in 2.1 but not live yet

@baileypumfleet can you check?

**Comment by Kfelts** [comment] 2022-09-26 19:02
I'm experiencing this as well. I just got mine up and running today- and even with saving, refreshing, and opening in an incognito browser to make sure it's not cached, it's still on a 24 hr clock.

**Comment by PeerRich** [comment] 2022-09-28 21:06
we're prioritizing this higher now and trying to find the root cause of this

**Closed** 2022-09-30 12:45 UTC
Labels: 🚨 urgent
