### ISSUE TITLE
Allow multiple availabilities

### ISSUE THREAD

**Issue by pedrorrivero** [calcom/cal.com#1207] opened 2021-11-24 19:25 UTC
### Is your proposal related to a problem?
I would like to have professional events (i.e. weekdays), and social events (i.e. weekends also), however the best I can do right now is change the times for a particular event type.

### Describe the solution you'd like
Allow to save multiple availabilities and choose one on each event type.

### Describe alternatives you've considered
Allow editing days as well on each event type, however this is less versatile and does not favor reusability.

### Additional context
Calendly implements this feature

**Comment by PeerRich** [comment] 2022-02-22 00:17
duplicate of #1651

**Closed by PeerRich** 2022-02-22 00:17 UTC
Labels: ✨ feature
