### ISSUE TITLE
[CAL-762] CSS / Display issues

### ISSUE THREAD

**Issue by Hybes** [calcom/cal.com#6403] opened 2023-01-11 10:42 UTC
### Issue Summary

I found a few CSS issues and issues relating to how the users see's the platform (screenshots to follow)

### Steps to Reproduce

1. Click to an event type editor and see the following broken border:
![image](https://user-images.githubusercontent.com/53020786/211783908-022e4793-d80c-478d-a0b4-c6d53ef15e09.png)

2. Add all the options for selectable durations in the event type options and add stripe payment too and see the following issues:
![image](https://user-images.githubusercontent.com/53020786/211784938-855a59c5-bdc1-4133-bddc-4ccba1e1038b.png)
![image](https://user-images.githubusercontent.com/53020786/211784995-cdf62797-9186-4aeb-a1f5-e1d7bc165e34.png)

3. Set a location in the event type settings, then go to edit the location with the pencil option and see the following broken text (all the other variables are currently hardcoded and should probably be taken from the common.json files):
![image](https://user-images.githubusercontent.com/53020786/211785281-7b1a3418-01c5-46a9-bb56-915971eaed77.png)

4. Create a booking and see the post-booking page, this used to show the user buttons to add to a range of calendars, now it only shows the new signup feature (my text in the screenshot is actually edited a tad, but you get the idea):
![image](https://user-images.githubusercontent.com/53020786/211785827-8a060ba2-cde9-46e4-b145-79fae61cab91.png)

### Technical details

- Chrome 1.46.153
- Node 16

<sub>[CAL-762](https://linear.app/calcom/issue/CAL-762/css-display-issues)</sub>

**Comment by zomars** [comment] 2023-01-11 18:01
Point 2 is a duplicate of https://github.com/calcom/cal.com/issues/6366 and is fixed by https://github.com/calcom/cal.com/pull/6416#issuecomment-1379169428

**Comment by Hybes** [comment] 2023-01-11 18:10
Ah yeah, peer raised my issue from within Slack, the other issues still stand though 👍

**Comment by Udit-takkar** [comment] 2023-01-11 22:05
There is also open PR for point 3

**Comment by Udit-takkar** [comment] 2023-01-11 22:06
https://github.com/calcom/cal.com/pull/6363

**Comment by Hybes** [comment] 2023-01-12 15:56
> 

But we want the non-logged in users to have this? No good for the logged in user as they are already getting the items added to their calendar automatically?

**Comment by zomars** [comment] 2023-01-12 16:36
> <img alt="Screenshot 2023-01-12 at 9 19 44 PM" width="589" src="https://user-images.githubusercontent.com/53316345/212114194-5a4d84f2-ed9b-4aa7-a099-fd0fe491ef72.png">
> 
> 4. it still shows you list of calendars if the person booking in logged in ( has an active session).

This is out of scope @Udit-takkar @Hybes

**Comment by Udit-takkar** [comment] 2023-01-18 15:53
closing this as 2nd and 3rd are fixed , 4th out of scope and there is a ticket already for 1st https://github.com/calcom/cal.com/issues/6527

**Closed by Udit-takkar** 2023-01-18 15:53 UTC
Labels: 🧹 Improvements, linear
