### ISSUE TITLE
[CAL-2390] Add ability for Copy Invite Link to Team to work with not logged in or non cal.com accounts

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#10960] opened 2023-08-25 17:24 UTC
Currently, when using the copy invite link to join team functionality only works when the user is logged in.

Need to add the functionality to:

1) Login into your account and then be navigated to the team you're invited to 

2) Create an account and then be navigated to the team you're invited to 

![CleanShot 2023-08-25 at 07.24.37@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/830813f4-6854-4b2c-9846-19d59845edbf/3f65fd5e-9bdf-475d-9b10-8cc8c62029a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84MzA4MTNmNC02ODU0LTRiMmMtOTg0Ni0xOWQ1OTg0NWVkYmYvM2Y2NWZkNWUtOWJkZi00NzVkLTliMTAtOGNjOGM2MjAyOWE5IiwiaWF0IjoxNjkyOTg0Mjk2LCJleHAiOjE2OTMwNzA2OTZ9.Lw4oAwmoCJ9vlhL0Of5s4LfSQuT_cJVCSjpqEIi_p6A)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2390](https://linear.app/calcom/issue/CAL-2390/copy-invite-link-to-team)</sub>

**Comment by abhijeetsingh-22** [comment] 2023-08-26 21:17
Duplicate of #10974

**Comment by Subhojit-Dey1234** [comment] 2023-08-27 12:52
https://github.com/calcom/cal.com/pull/10974 - PR for this issue.

**Closed** 2023-08-28 12:33 UTC
Labels: ✨ feature, authentication
