### ISSUE TITLE
bug: 404 page acting sus on production

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.com#9933] opened 2023-07-04 21:20 UTC
### Issue Summary

The custom 404 page works in most cases except when one goes to cal.com.404, where the default next error page is shown. But if I try to recreate this locally, it works perfectly. 

### cal.com/404x : 

<img width="600" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/9836ce8f-a6df-4dac-9793-8531109c72ce">

### cal.com/404:

<img width="600" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/b2a018a0-0043-4d0a-ac9c-951fbc2437ac">

### ocalhost:3000/404:

<img width="600" alt="image" src="https://github.com/calcom/cal.com/assets/74819565/be0eaab4-0965-4ee0-994f-b21cb7e533c9">

I am not sure if this intentional or not. Would be curious to know if yes. I can't find the reason, if pointed in the right direction glad to work this!

### Technical details

- Browser version, screen recording, console logs, network requests: Arc
- Node.js version: 18.15.0

**Comment by PeerRich** [comment] 2023-07-05 09:53
duplicate of https://github.com/calcom/cal.com/issues/9925

**Closed by PeerRich** 2023-07-05 09:53 UTC
Labels: 🐛 bug
