### ISSUE TITLE
[CAL-3946] When someone modify the Label in location prepopulated questions it gets bugged

### ISSUE THREAD

**Issue by joseuo94** [calcom/cal.com#16009] opened 2024-07-31 16:50 UTC
If the meeting location is the attendee's phone number and the host modifies the prepopulated booking question {Location} it bugs and every time the attendee tries to introduce their phone number it says invalid input.

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7b2e3b0a-c390-4b13-aebf-9d5cecb5fa8f/691153bb-b263-4272-8141-b35e59aa9a65?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83YjJlM2IwYS1jMzkwLTRiMTMtYWViZi05ZDVjZWNiNWZhOGYvNjkxMTUzYmItYjI2My00MjcyLTgxNDEtYjM1ZTU5YWE5YTY1IiwiaWF0IjoxNzIyNDQ0NjM1LCJleHAiOjE3NTM5ODA2MzV9.TZefhVn1DwituQIeceFJDp_gJe2KeoQpDZZfCU3I4_s)

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c8a4a512-9ebb-4c65-ab7d-045d853cda7e/475abd07-81ae-4536-8159-67a4efdde6ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jOGE0YTUxMi05ZWJiLTRjNjUtYWI3ZC0wNDVkODUzY2RhN2UvNDc1YWJkMDctODFhZS00NTM2LTgxNTktNjdhNGVmZGRlNmFjIiwiaWF0IjoxNzIyNDQ0NjM1LCJleHAiOjE3NTM5ODA2MzV9.acDgyjrkal4qqp-KIloJSRX5dMC10TlN7uaHHl8VB6s)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3946](https://linear.app/calcom/issue/CAL-3946/when-someone-modify-the-label-in-location-prepopulated-questions-it)</sub>

**Comment by TaduJR** [comment] 2024-08-11 20:12
Hey @joseuo94. I think someone fixed it without linking the PR to this issue. Please Close it.

**Comment by anikdhabal** [comment] 2024-08-12 04:53
https://github.com/user-attachments/assets/92e70323-9810-443e-a010-8468f0ae3925

I think the issue is resolved

**Closed by anikdhabal** 2024-08-12 04:53 UTC
Labels: 🐛 bug, Low priority, booking-page, community
