### ISSUE TITLE
[CAL-1401] Routing Form Details Sent to booked Round Robin

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8071] opened 2023-04-03 21:37 UTC
When using a routing form, some times the event points to a round robin and the round robin host selected may not be the person who set up the routing form. They will get booked for the call, but have no context from the form. It would be great to send them the round-robin results as well! 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1401](https://linear.app/calcom/issue/CAL-1401/routing-form-details-sent-to-booked-round-robin)</sub>

**Comment by shirazdole** [comment] 2023-04-03 21:37
cc @PeerRich @hariombalhara

**Comment by hariombalhara** [comment] 2023-04-04 06:03
Duplicate of #8061

**Closed by hariombalhara** 2023-04-04 06:03 UTC
Labels: ✨ feature, routing forms
