### ISSUE TITLE
[CAL-623] /settings/teams/appearance missing the ability to edit the appearance

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#6106] opened 2022-12-19 13:53 UTC
Teams appearance settings don't have the option to add your own brand colours or to change to dark / light mode.

![CleanShot 2022-12-19 at 13.28.09@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ed1a8687-c4bc-4ab2-bb3e-113f9bf1f136/955bc733-7414-41b3-aa7e-911421248dc3)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-623](https://linear.app/calcom/issue/CAL-623/settingsteamsappearance-missing-the-ability-to-edit-the-appearance)</sub>

Acceptance criteria 
- Team admins can see those settings, 
- Team members cannot see the settings
- The settings take effect on the relevant teams public booking pages

**Comment by leventdeniz** [comment] 2022-12-20 10:06
Can I work on this?

**Comment by Jaibles** [comment] 2022-12-20 10:53
> Can I work on this?

Yes please 🙏

**Comment by leventdeniz** [comment] 2022-12-21 17:41
thanks, i'm on it

**Comment by hariombalhara** [comment] 2023-02-19 09:01
This seems like a duplicate of #6079 which is already implemented.

**Closed by hariombalhara** 2023-02-19 09:01 UTC
Labels: ⚡ Quick Wins, 👥 teams
