### ISSUE TITLE
Redirection to localhost while signing out and singing in

### ISSUE THREAD

**Issue by Sreehari78** [calcom/cal.com#8607] opened 2023-05-01 17:06 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Ran into a bug while signing out of the calcom account.
The domain got redirected to http://localhost:3000/

### Steps to Reproduce

1. Login to the domain
2. sign out from the account
3. gets redirected to  http://localhost:3000/

### Screen Recording for your reference

https://user-images.githubusercontent.com/51209834/235493504-c2d3b405-f312-49ef-b1fb-26c98a5efac8.mp4

**Comment by bottercode** [comment] 2023-05-01 17:58
I have reproduced the issue but it works fine in my case!

**Comment by anandchristudas** [comment] 2023-05-01 21:27
@bottercode did you host in any virtual machine, we have been trying to make it work on GCP for the last 3 weeks and it's not working correctly, could you please give us the right step to make it work?

**Comment by anandchristudas** [comment] 2023-05-01 23:18
> I have reproduced the issue but it works fine in my case!

have you used the docker installation or normal installation process to install cal.com

**Comment by bottercode** [comment] 2023-05-02 07:51
> > I have reproduced the issue but it works fine in my case!
> 
> have you used the docker installation or normal installation process to install cal.com

I have used docker for the installation.

**Comment by bottercode** [comment] 2023-05-02 09:48
> > > > I have reproduced the issue but it works fine in my case!
> > > 
> > > 
> > > have you used the docker installation or normal installation process to install cal.com
> > 
> > 
> > I have used docker for the installation.
> 
> what did you do to add the domain or subdomain to it, can you tell me the main steps? I have been trying to do it for a long time and it's not working for me. thanks a lot.

What's the error you are facing. Can you attach a screenshot ?

**Comment by anandchristudas** [comment] 2023-05-02 10:20
> > > > > I have reproduced the issue but it works fine in my case!
> > > > 
> > > > 
> > > > have you used the docker installation or normal installation process to install cal.com
> > > 
> > > 
> > > I have used docker for the installation.
> > 
> > 
> > what did you do to add the domain or subdomain to it, can you tell me the main steps? I have been trying to do it for a long time and it's not working for me. thanks a lot.
> 
> What's the error you are facing? Can you attach a screenshot?

same issue as mentioned by @Sreehari78 when I log out I get redirected to http://localhost:3000/ 
when I sign in also I get redirected to http://localhost:3000/

And in the profile, it's always www.localhost:3000/username not www.cal.example.com/username as shown in the screenshot.

![Screenshot 2023-05-02 154745](https://user-images.githubusercontent.com/95290346/235641378-c302eb06-d9c0-4048-9b51-0a01939e4263.jpg)

**Comment by Vikram125609** [comment] 2023-05-02 10:53
Uploading Screen Recording 2023-05-02 at 4.22.36 PM.mov…

I had reproduce the issue and attached the video but it is working little different in my case

**Comment by Vikram125609** [comment] 2023-05-02 11:19
I think i had fixed the bug  

https://user-images.githubusercontent.com/93823479/235652358-ab5e0a17-55d2-49c9-a73e-b56ef18128e8.mov

**Comment by anandchristudas** [comment] 2023-05-02 11:27
> I think i had fixed the bug . Can you please have a look
> 
>  Screen.Recording.2023-05-02.at.4.48.07.PM.mov

I think this will fix it but how to change www.localhost:3000/username to www.cal.example.com/username

![Screenshot 2023-05-02 154745](https://user-images.githubusercontent.com/95290346/235653500-e717a82a-0868-4ee1-be7d-3e963c838118.jpg)

currently, my username isn't mapped under my domain name. It's under localhost. when that is fixed automatically other one will be fixed.

**Comment by Vikram125609** [comment] 2023-05-02 12:17
Email : vs125609@gmail.com

**Comment by PeerRich** [comment] 2023-05-14 21:29
i think this is due to wrong .env settings. cant reproduce!

**Closed by PeerRich** 2023-05-14 21:29 UTC
Labels: 🐛 bug

**Comment by Marcus1911** [comment] 2024-05-01 05:19
@Vikram125609  Did you solve the issue? 
I couldn't see any further comments about what happened. I'm having the same issue.

**Comment by mnofresno** [comment] 2024-12-13 02:47
Same issue here. Any examples on how to solve it changing the .env?
