### ISSUE TITLE
Availability overrides (vacation time, out-of-office, one-off availabilities)

### ISSUE THREAD

**Issue by matthewlarkin** [calcom/cal.com#3239] opened 2022-07-05 19:52 UTC
### Is your proposal related to a problem?

I can’t seem to express vacation times or one-off availabilities without leveraging an external calendar connection such as Google Calendar.

### Describe the solution you'd like

Would love to express irregular unavailabilities / availabilities within Cal alone (with no use of external calendar connections). In Calendly, these are called date overrides. RFC 5545 (3.8.5.1) calls these Exception Date Times (at least in reference to recurring events).

### Describe alternatives you've considered

I’ve been using Google Calendar for one-off unavailabilities, which is suboptimal. And I don’t see that working for one-off availabilities; to create a one-off availability, I think I’d have to create it’s own availability schedule and/or its own event type, which feels a little clunky.

**Comment by Jaibles** [comment] 2022-08-17 13:36
Closing as it's a duplicate of this: https://github.com/calcom/cal.com/issues/3239
Will link back to this request so we have the details above from @matthewlarkin

**Closed by Jaibles** 2022-08-17 13:36 UTC
Labels: ✨ feature, 🔧 in progress
