### ISSUE TITLE
[CAL-3697] embed: pass in parameters of the parent page

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#15019] opened 2024-05-14 09:08 UTC
if i embed cal.com in cal.com/sales and i do cal.com/sales?email=peer@cal.com the embed does not pre-fill parameters.

can we extend the script to read from the URL and pass it in?

<sub>[CAL-3697](https://linear.app/calcom/issue/CAL-3697/embed-pass-in-parameters)</sub>

**Comment by hariombalhara** [comment] 2024-05-14 10:40
Duplicate of #13459

**Closed by hariombalhara** 2024-05-14 10:40 UTC
Labels: ✨ feature, ⚡ Quick Wins, Medium priority, embed, booking-page

**Comment by GaryGHL** [comment] 2024-05-14 11:50
To add. If the value is set in the embed it works fine, for me its when the url value is dynamic and cannot be know until the wordpress page loads.

So, mydomain.co.uk/mycal/?utmsource=google&utmterm=mortgage

Added to the embed code:
Cal("inline", {
	elementOrSelector:"#my-cal-inline",
	calLink: "ghldirect/mortgage",
	layout: "month_view",
        config: {
          name: "Evie Brett", **//This gets inserted**
          email: "gary@gmail.com", **//This gets inserted**
          utmsource: "", **//This doesnt**
          utmterm: "", **//This doesnt**
          adgroup: "" **//This doesnt**
        }
  });
