### ISSUE TITLE
[CAL-693] Calendar availability is not correct when an "all-day" event is used

### ISSUE THREAD

**Issue by adam-nygate** [calcom/cal.com#2240] opened 2022-03-22 12:43 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I presumed that if there was an "all-day" calendar event (used for things like holidays, vacation etc.) that this would block out availability when using Cal.com to schedule an appointment. It doesn't.

### Steps to Reproduce

1. Create an "all-day" calendar event on a Google Calendar linked to Cal.com
2. Browse for appointment slots using Cal.com during the time of the "all-day" calendar event
3. Book an appointment when the calendar owner is unavailable

### Technical details

- macOS Monterey (version 12.3) running Safari (version 15.4)

<sub>[CAL-693](https://linear.app/calcom/issue/CAL-693/calendar-availability-is-not-correct-when-an-all-day-event-is-used)</sub>

**Comment by soplan** [comment] 2022-03-23 08:55
@adam-nygate You can try out soplan.com which handles all-day events correctly

**Comment by milospuac** [comment] 2022-03-23 09:03
Hi Adam,

I couldn't reproduce the issue. Can you check if the all-day calendar event is set to **Free** or **Busy**? You can toggle between those two here 
<img width="405" alt="Screen Shot 2022-03-23 at 09 54 37" src="https://user-images.githubusercontent.com/97884287/159661825-4ed35ca3-d4e1-41c7-9183-7d8e15a08616.png">

If it's set to **Busy**, this is how it shows in your availability for the day
<img width="1026" alt="Screen Shot 2022-03-23 at 09 58 30" src="https://user-images.githubusercontent.com/97884287/159662068-d401527d-773e-4a25-856a-338694112c2b.png">

vs. when you set it to **Free** 
<img width="1146" alt="Screen Shot 2022-03-23 at 09 58 01" src="https://user-images.githubusercontent.com/97884287/159662139-e039d1ee-33e6-4f8f-adbf-a16f79183eb0.png">

Hope this helps

**Comment by adam-nygate** [comment] 2022-03-23 09:06
@milospuac that was the issue! Thank you :)

**Comment by milospuac** [comment] 2022-03-23 09:07
No worries, glad I could help :)

**Comment by zacchiro** [comment] 2022-04-12 16:33
I'm seeing this issue in reverse: a full day event marked as free (not busy) which inhibits booking any slot during that day.
This is with cal.com hosting and a self-hosted up-to-date nextcloud.
Should I file this as a separate issue?

(FWIW this is my main blocker for embracing cal.com fully. A confirmation that this is supposed to work would be helpful.)

**Comment by jsolly** [comment] 2023-01-05 18:26
I am running into this issue on MacOS ical. Today I have an all-all day event, but cal.com is showing me as available at 4PM
## cal.com
![image](https://user-images.githubusercontent.com/9572232/210852063-82ff3fc1-199d-4c08-99b7-d6c8e0e6be17.png)

## Screenshot of iCal 
### ('🥟 # 2 work' is an all-day event today on the work/school calendar) 

![image](https://user-images.githubusercontent.com/9572232/210852274-5c203a31-3130-463f-881c-9befe270d08f.png)

## Availability
![image](https://user-images.githubusercontent.com/9572232/210853307-b0f0e83b-7fc1-4456-b6c3-62c9545ebcb9.png)


What is strange is that it seems to block all other time slots. It's just the 4PM one that remains.

**Comment by PeerRich** [comment] 2023-01-06 10:56
just noticed, the new issue was posted here: https://github.com/calcom/cal.com/issues/6292

**Closed by PeerRich** 2023-01-06 10:56 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, linear
