### ISSUE TITLE
Cancel booking button in unclickable state

### ISSUE THREAD

**Issue by reachkrishnaraj** [calcom/cal.com#3552] opened 2022-07-27 12:37 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Cancel booking button on a booked event is unresponsive in a certain use-case explained below

### Steps to Reproduce

1. Book any event type
2. Go to the booking as host. Click "Edit Booking". Dont do anything else.
3. Now click "Cancel". Button unresponsive unless a page refresh is done forcefully.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by Toledodev** [comment] 2022-07-27 14:20
Hey @reachkrishnaraj, what happens is that when you click on the "Edit Booking" dropdown you need to click away from it if you want to click anywhere else on the site. I don't think this is a bug
https://www.loom.com/share/f3bbaa800f464c5686b82541ade4935c

**Comment by milospuac** [comment] 2022-07-28 07:28
Hey Raj,

Like Rafael said above, just click away from the dropdown to close it, and then click on Cancel. It's not a bug.

**Closed by milospuac** 2022-07-28 07:28 UTC
