### ISSUE TITLE
Multiple availability schedules

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1447] opened 2022-01-10 21:59 UTC
Implement the UX surrounding schedules which can be found in Ciarán's Figma document. Essentially, the user can create multiple schedules (e.g. Work hours, personal hours) and assign days and times to them, then when creating an event type they can assign that event type to a certain schedule.

**Comment by PeerRich** [comment] 2022-02-22 00:18
duplicate of #1651

**Closed by PeerRich** 2022-02-22 00:18 UTC
Labels: ✨ feature, 🔧 in progress
