### ISSUE TITLE
Overriding "Add to calendar" for individual events not working as expected

### ISSUE THREAD

**Issue by mfts** [calcom/cal.com#12719] opened 2023-12-11 03:26 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I signed up with xyz@gmail.com to cal, I connected two Google Calendar accounts (xyz@gmail.com and xyz@company.com). By default newly booked events go to xyz@gmail.com. In one event, I overrode the "Add to calendar" section in advanced section of the event so that all events scheduled through that link are added to xyz@company.com.

The events are scheduled in the Google Calendar for xyz@company.com, however, the email reply_to and body state the xyz@gmail.com email (which is my user's main cal.com email address).

My expectation is that when I override the calendar that the reply_to and body of the invitation email states the same address where the event is scheduled. 

### Steps to Reproduce

1. Sign up to cal.com with xyz@gmail.com
2. Add a new calendar for xyz@company.com
3. Overwrite a the "Add to calendar" for a specific event https://app.cal.com/event-types/<eventId>?tabName=advanced
4. Schedule event 
5. See that the event is scheduled in xyz@company.com Calendar, however, the body and email show xyz@gmail.com

### Actual Results

- shows xyz@gmail.com instead of xyz@company.com when overriding which calendar the event should save to 

### Expected Results

- should show xyz@company.com instead of xyz@gmail.com in the invitation email when overriding which calendar the event should save to

### Technical details

Cal version: `v.3.5.4-h-2e50625`

### Evidence

Overriding add to calendar

![Screenshot 2023-12-11 at 14 22 51](https://github.com/calcom/cal.com/assets/4049052/87091602-af22-41a9-8aea-1bd4698b4d06)

invite for the event
![Screenshot 2023-12-11 at 14 22 59](https://github.com/calcom/cal.com/assets/4049052/21ed5f1b-ad6b-4f75-8898-a12060c9e51a)

**Comment by PeerRich** [comment] 2023-12-11 03:56
right now we actually always use the email in your settings. I know this has been on @ciaranha's mind for a while

**Comment by PeerRich** [comment] 2023-12-11 03:57
closing as this is a duplicate of a ticket already in work

**Closed by PeerRich** 2023-12-11 03:56 UTC
Labels: 🐛 bug
