### ISSUE TITLE
Rescheduling an appointment does not seem to notify the other party

### ISSUE THREAD

**Issue by masasin** [calcom/cal.com#10704] opened 2023-08-10 15:47 UTC
### Issue Summary

I had a meeting scheduled by someone else on my calendar which did not require confirmation. It conflicted with another event which I had not yet added to my calendar, and I rescheduled it to an hour prior. It showed on my calendar, and I received a confirmation email, but she claims that she did not receive an email and her calendar still had the original time. This caused us to miss the call.

### Steps to Reproduce

1. Have a slot which allows booking without confirmation
2. Have someone else book an event on your calendar
3. Reschedule the event

I would expect us both to receive an email mentioning the rescheduling, so that they are aware or they can reschedule to another time.

### Actual Results

- I received an email and updated calendar entry
- The other party did not receive an email and the calendar entry was not updated

### Expected Results

- We both receive an email, and both our calendars get updated

### Technical details

- Free tier, embedded in a button on my website (jnassar.com)

### Evidence

- I started the call at the rescheduled time, but she did not appear.
- She mentioned later that the call was supposed to be at the original time, according to her schedule.
- I mentioned that the date and time indicated on my rescheduling email, and that she should have received an email as well.
- She said she had not received anything.

**Comment by CarinaWolli** [comment] 2023-08-11 13:36
Works fine for me. @masasin could you try to reproduce that issue and maybe add a screen recording?

**Comment by CarinaWolli** [comment] 2023-08-21 17:24
@masasin is this still an issue for you? Otherwise we will close this issue, as we can't reproduce it

**Closed** 2023-08-22 13:54 UTC
Labels: 🐛 bug, High priority, calendar-apps
