### ISSUE TITLE
[CAL-1127] [CAL-192] "&" symbol and apostrophes don't get rendered properly in the confirmation email title

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#7255] opened 2023-02-21 15:41 UTC
This is the name of the event type

![Screenshot 2022-10-19 at 17.27.54.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/1927ea3f-e004-4c5c-bf9d-e8b396d5445b/0bd61915-b4c1-4c5c-9bfa-2fe03b1aa978)

And this is how it appears in the email

![Screenshot 2022-10-19 at 17.29.45.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/b824eac5-1ca0-4692-8845-fa0603f443ef/c625a4ba-4e5e-4000-8480-31c0d621dc12)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-192](https://linear.app/calcom/issue/CAL-192/and-symbol-and-apostrophes-dont-get-rendered-properly-in-the)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-192](https://linear.app/calcom/issue/CAL-192/and-symbol-and-apostrophes-dont-get-rendered-properly-in-the)</sub>

**Comment by milospuac** [comment] 2023-02-21 15:41
![Screenshot 2022-11-03 at 1.33.47 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9517a12c-a5e3-4e4b-84ff-458c2538290b/007bf7a0-3340-4813-9277-3de12118cb64)

okay so this bug is only on production ( app.cal.com) and not in development. will have to investigate more

**Comment by milospuac** [comment] 2023-02-21 15:41
Can you try chrome or safari?

**Comment by milospuac** [comment] 2023-02-21 15:41
brave browser

**Comment by milospuac** [comment] 2023-02-21 15:41
@Udit-takkar do you use chrome?

**Comment by milospuac** [comment] 2023-02-21 15:41
![perplexed-mystery.gif](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3d36ec81-5709-4ee4-b0fc-0e1b13f75585/9dd0f916-9146-4115-9991-87127944c090)

**Comment by milospuac** [comment] 2023-02-21 15:41
![Screenshot 2022-10-26 at 10.06.04 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/09915b1d-a077-4fb3-8c50-c1ea46f2bf5b/89cd053c-de5b-4df5-b1b3-7e8b9b58a052)

It's also working fine here

**Comment by milospuac** [comment] 2023-02-21 15:41
Also, check the bookings tab once you confirmed the meeting 

![Screenshot 2022-10-26 at 18.32.52.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3d3af639-6f70-48cb-b45b-0940b1b34268/dcbafe34-4d13-4151-8aeb-64a9a4d2b0ab)

**Comment by milospuac** [comment] 2023-02-21 15:41
okay maybe this problem is only in confirmed email

**Comment by milospuac** [comment] 2023-02-21 15:41
![Screenshot 2022-10-26 at 9.59.52 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3b1cd1f9-a4ba-4797-94ec-0cc770116d1f/9860ecb8-14f2-4686-ad47-f7fc19d1fb92)

I have also tested on browser

**Comment by milospuac** [comment] 2023-02-21 15:41
Hey @Udit-takkar it's both gmail and outlook  

Gmail: 

![Screenshot 2022-10-26 at 18.01.31.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ad9d528f-321b-4b67-ad20-28ef402a874b/0926cf01-a6a8-4033-ae05-90c63308d84d)

Outlook: 

![Screenshot 2022-10-26 at 18.00.18.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/f3d272dc-deed-46d1-b53b-5fbdcd61bd4d/332003e9-0109-4284-9927-735fdb18af4d)

I do have to mention that this is in the browser, don't know how it behaves in apps for those platforms.

**Comment by milospuac** [comment] 2023-02-21 15:41
i have tested on gmail, outlook

**Comment by milospuac** [comment] 2023-02-21 15:41
![Screenshot 2022-10-26 at 5.29.55 PM.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6e739c72-30cb-4363-81fb-3e16acb329f3/4856d6a5-596f-4fab-9c5e-ca992182006f)

 i am unable to reproduce this bug. what email provider are you using ?

**Comment by Jaibles** [comment] 2023-02-21 15:42
@Udit-takkar did you get anywhere with this? This is still an issue for me but with forward slash`/`
<img width="428" alt="CleanShot 2023-02-21 at 15 40 19@2x" src="https://user-images.githubusercontent.com/4536123/220391304-15078216-9bfa-4bc7-87e7-61cb14f377b1.png">

You can book here to test if you need to: https://cal.com/ciaran/design

**Comment by Udit-takkar** [comment] 2023-02-21 16:19
@Jaibles yeah it's still pending. just busy with few other things will work on this as soon as i can

**Comment by G3root** [comment] 2023-02-21 16:50
same as  #1961 , #6798 and #3250. for the #3250 i sent a PR , looks like this problem isn't fixed . maybe it's something to do with sendgrid 🤔  ?

**Comment by PeerRich** [comment] 2023-02-22 17:23
very weird

**Comment by PeerRich** [comment] 2023-02-22 17:23
@leog maybe you have an idea?

**Comment by PeerRich** [comment] 2023-02-22 17:23
or @CarinaWolli

**Comment by CarinaWolli** [comment] 2023-02-22 20:05
> maybe it's something to do with SendGrid 🤔 ?

I don't think it has anything to do with SendGrid, I just set up SendGrid locally and everything is still working. 

Some findings I had: 
- Booking title on production db is saved with "Design `&#x2F;` product review" but event title on production is saved as "Design / product review" 
- Locally the booking title is saved as "Design / product review"

Anybody any idea why?

**Comment by leog** [comment] 2023-02-22 20:43
> Anybody any idea why?

@CarinaWolli Different db encodings perhaps?

**Comment by G3root** [comment] 2023-02-23 04:52
@CarinaWolli does wrapping email subject with `decodeURIComponent` fix this  ?

**Comment by CarinaWolli** [comment] 2023-02-23 15:58
> @CarinaWolli does wrapping email subject with decodeURIComponent fix this ?

@G3root No it doesn't 

Another thing I found: If you use your own custom event name (advanced settings - Event name in calendar ) then the special characters are also working fine. So I think the issue is because of this translation: 
![Screenshot 2023-02-23 at 10 53 14](https://user-images.githubusercontent.com/30310907/220959908-6b45840f-28e4-4730-8256-7d86fef85e5a.png)

i18next escapes values, see here: https://www.i18next.com/translation-function/interpolation#unescape
No idea though, why this is not happening locally

**Comment by G3root** [comment] 2023-04-19 09:28
fixed by #7591

**Closed by G3root** 2023-04-19 09:28 UTC
Labels: 🙋🏻‍♂️help wanted, ⚡ Quick Wins, Medium priority
