### ISSUE TITLE
[CAL-3572] Slots API getting a blank response (managed events)

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14802] opened 2024-04-29 13:59 UTC
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3572](https://linear.app/calcom/issue/CAL-3572/slots-api-getting-a-blank-response-managed-events)</sub>

**Comment by Shaik-Sirajuddin** [comment] 2024-05-23 03:21
When creating a managed event type , a template is created and the template is cloned for each assigned user.
The copy assigned to user has availability set and is bookable, the original template is not bookable ( as its a template ).

Slots api returns response accordingly as per user schedule when trying to access a users instance of managed event.
It returns empty response when passing template's eventId.
It seems to be match the expected behaviour .

**Comment by Shaik-Sirajuddin** [comment] 2024-05-23 03:24
/team/pro/managetest

a link to template opens booking page while showing no available slots
I think it should redirect to not found or show list of bookable team members.

**Comment by alishaz-polymath** [comment] 2024-08-19 14:25
There have been reports of empty slots in event types other than managed, including but not limited to multiple duration events

**Comment by alishaz-polymath** [comment] 2024-09-25 11:53
Finally fixed!

**Closed** 2024-09-25 11:53 UTC
Labels: 🐛 bug, Medium priority, api, ❓ needs spec
