### ISSUE TITLE
[CAL-3717] [CAL-3248] Zoom link missing from Round Robin event types when rescheduled

### ISSUE THREAD

**Issue by ciaranha** [calcom/cal.com#13931] opened 2024-02-29 10:31 UTC
If someone schedules a round robin event, when the organizers have Zoom connected, the Zoom link is on the event. If the booker then reschedules the event, the Zoom link is missing from the rescheduled event.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3248](https://linear.app/calcom/issue/CAL-3248/zoom-link-missing-from-round-robin-event-types-when-rescheduled)</sub>

<sub>[CAL-3717](https://linear.app/calcom/issue/CAL-3717/[cal-3248]-zoom-link-missing-from-round-robin-event-types-when)</sub>

**Comment by Udit-takkar** [comment] 2024-02-29 13:19
@ciaranha can't reproduce
<img width="1512" alt="Screenshot 2024-02-29 at 6 48 54 PM" src="https://github.com/calcom/cal.com/assets/53316345/d7fb3478-f06c-43af-8095-7a0f164832bd">

**Comment by ciaranha** [comment] 2024-02-29 13:29
@Udit-takkar did you test on a round robin yea?

**Comment by Udit-takkar** [comment] 2024-03-06 16:03
Closing this issue after discussion with ciaran

**Comment by Udit-takkar** [comment] 2024-03-12 16:59
User reported that link is only missing from email

**Comment by Udit-takkar** [comment] 2024-03-15 10:24
Still not able to reproduce the bug

<img width="617" alt="Screenshot 2024-03-15 at 3 50 28 PM" src="https://github.com/calcom/cal.com/assets/53316345/67d83cc3-fdfd-4921-be18-66393a1e5cf0">

**Comment by CarinaWolli** [comment] 2024-03-18 17:49
> Still not able to reproduce the bug

@Udit-takkar  Maybe because of requires confirmation as mentioned here in https://github.com/calcom/cal.com/issues/14086#issuecomment-1999399473?

**Comment by keithwillcode** [comment] 2024-05-29 14:41
Closing because we cannot reproduce.

**Closed by keithwillcode** 2024-05-29 14:41 UTC
Labels: 🐛 bug, High priority, teams
