### ISSUE TITLE
Show Password - button is not working perfectly 

### ISSUE THREAD

**Issue by mMARUF** [calcom/cal.com#8784] opened 2023-05-09 15:22 UTC
### Issue Summary
**Show Password** - button is not working perfectly in login page

### Steps to Reproduce

1. Visit Cal.com
2. Register
3. Save the username and password in chrome
4. Now visit https://app.cal.com/auth/login
5. Observe that the username and password are already filled in 
6. Now press **Show Password**

### Actual Results
After pressing **Show Password**, we do not see the saved password in chrome

### Expected Results
After pressing **Show Password**, user should see the saved password

### Technical Specifications
Browser: Chrome Version 113.0.5672.63 (Official Build) (arm64)
OS: macOS 13.3.1 (a) 

### Attachment(s)

![show password not working](https://github.com/calcom/cal.com/assets/45368054/49ffcc72-1899-4c13-8a96-bf2da813983f)

**Comment by thebishalniroula** [comment] 2023-05-09 15:23
Hi. I want to work on this. Can you assign this to me?

**Comment by Ratnadeep2k** [comment] 2023-05-09 15:43
can I work on this ? 
I can fix it easily. @Jaibles

**Comment by pranjalg13** [comment] 2023-05-09 16:05
Hey @mMARUF i think this might an browser-related issue since not able to reproduce this.

**Comment by thebishalniroula** [comment] 2023-05-09 16:12
@pranjalg13 is right. I am not being able to reproduce the issue either.

**Comment by PeerRich** [comment] 2023-05-09 16:49
cant reproduce

**Closed by PeerRich** 2023-05-09 16:49 UTC
Labels: 🐛 bug
