### ISSUE TITLE
Calendar description does not have visible scrollbar to indicate more content

### ISSUE THREAD

**Issue by nta-telmore** [calcom/cal.com#16757] opened 2024-09-22 12:35 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In preview mode of calendar, in case the description is too long or have long bullet points list, there is no scrollbar shown initially. That creates confusion for people as they might not know the description continues and there is more content other than the visible part. 

### Steps to Reproduce

1. Go to one of the event types
2. Add some description that has more than 5-10 bullet points
3. Save and open the preview link
4. You will see that description does not have any scrollbar and you might think either description is missing or the visible part is all of it.
5. Unless you scroll on description, users will never know it's scrollable

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- Visible scrollbar or some kind of indication once you open the calendar in case the description is too long to show it all

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

![Screenshot 2024-09-22 at 14 28 08](https://github.com/user-attachments/assets/6830a192-0bfd-4fc3-bebc-022b1072b4a5)

**Comment by naaa760** [comment] 2024-09-23 05:16
Hello @nta-telmore :)

fix: #16757

`
The bug is that the calendar preview does not display a scrollbar when the description exceeds the visible area, confusing users who may think the content is incomplete. Without any indication of additional content, users might not realize they can scroll to view more. This leads to a poor user experience and potential misunderstandings about the event details.
`

**Comment by guptadeepak8** [comment] 2024-09-23 09:34
The issue is that when the width is greater than 568px and less than 765px, the scrollbar is not visible.

**Comment by anikdhabal** [comment] 2024-09-24 12:48
Hey @nta-telmore can't reproduce it on my end. closing it for now

**Closed by anikdhabal** 2024-09-24 12:48 UTC
Labels: 🐛 bug, ui

**Comment by nta-telmore** [comment] 2024-10-15 09:30
Why have you closed it guys? This issue is on Mac and iOS devices. What is your bug reproduction steps? Only in Windows?

This issue is also reported in #16260 , it's a clear issue.
