### ISSUE TITLE
[CAL-1846] brand color picker missing padding

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9263] opened 2023-06-01 11:52 UTC
![CleanShot 2023-06-01 at 12 51 25@2x](https://github.com/calcom/cal.com/assets/8019099/b7bc85cb-4eab-40e6-a8e7-4b725dcb8a8b)

somehow the left one is correct:
![CleanShot 2023-06-01 at 12 51 38@2x](https://github.com/calcom/cal.com/assets/8019099/ffd6a636-ca90-4515-bb1f-e7fcd0bc7c6a)

<sub>[CAL-1846](https://linear.app/calcom/issue/CAL-1846/brand-color-picker-missing-padding)</sub>

**Comment by AyushMainali123** [comment] 2023-06-01 12:18
Hey. It seems this issue is a duplicate of the issue:
https://github.com/calcom/cal.com/issues/9228

**Closed** 2023-06-01 15:08 UTC
Labels: 🧹 Improvements, Low priority, 💎 Bounty, 1 points
