### ISSUE TITLE
[CAL-1313] short blank screen when clicking into event-type

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#7881] opened 2023-03-22 13:36 UTC
https://app.birdeatsbug.com/sessions/ejv-ZbJwr51RBF4hcAmBx-WarXxeWJ640cUjb4KycA2c

<sub>[CAL-1313](https://linear.app/calcom/issue/CAL-1313/short-blank-screen-when-clicking-into-event-type)</sub>

**Comment by joeshajan** [comment] 2023-03-22 16:02
Hey, @PeerRich I would like to fix this bug. Can you assign this to me?

**Comment by PeerRich** [comment] 2023-03-23 11:35
assigned! @joeshajan

**Comment by joeshajan** [comment] 2023-04-08 19:39
@PeerRich I'm not able to reproduce this issue. Is it fixed?

https://user-images.githubusercontent.com/69904519/230739642-f93601fc-77f9-4b8c-8a57-23b14ae58c77.mp4

**Comment by ujjawalkant09** [comment] 2023-05-11 18:40
I think it is fixed , Because I tried to reproduce this issue but that is not happening .

**Comment by joe-shajan** [comment] 2023-07-05 08:21
> It seems that the issue has been resolved as I have attempted to reproduce it but have not encountered the problem again.
> 
>  event-type_issue_cal.mov

yes you are correct this issue is fixed

**Closed** 2023-07-10 19:40 UTC
Labels: 🐛 bug, 🧹 Improvements, Medium priority, 1 points
