### ISSUE TITLE
[CAL-3177] Inline embed already exists. Ignoring this call

### ISSUE THREAD

**Issue by chadimessmer** [calcom/cal.com#13259] opened 2024-01-16 15:12 UTC
Hey there,

I'm using calcom/embed-react inside a NextJs project, and have the following problem : 

At the first load of the page, everything works perfectly.
After navigating away from the page and returning, the calendar fails to display, and an error message appears in the console: "Inline embed already exists. Ignoring this call."

<sub>[CAL-3177](https://linear.app/calcom/issue/CAL-3177/inline-embed-already-exists-ignoring-this-call)</sub>

**Comment by a-kon** [comment] 2024-01-17 20:02
Broken in https://github.com/calcom/cal.com/pull/13048

**Comment by a-kon** [comment] 2024-01-17 20:15
Since this could break a crucial step in our funnel and I have access to `window.Cal`, I came up with a dirty hack which is to call `delete delete window.Cal.instance.inlineEl` on unmounting the component (I use Vue, but it should also work in React and other SPAs). This removes a reference to an element that no longer exists in the DOM at the time the component is unmounted, and after that, you can mount cal.com embed again.

But be careful if you googled this answer - you may break something when the bug is fixed. This method is very dirty and not safe at all.

**Comment by chadimessmer** [comment] 2024-01-18 08:57
> Since this could break a crucial step in our funnel and I have access to `window.Cal`, I came up with a dirty hack which is to call `delete window.Cal.instance.inlineEl` on unmounting the component (I use Vue, but it should also work in React and other SPAs). This removes a reference to an element that no longer exists in the DOM at the time the component is unmounted, and after that, you can mount cal.com embed again.
> 
> But be careful if you googled this answer - you may break something when the bug is fixed. This method is very dirty and not safe at all.

Thanks a lot, this works with NextJs too!

`  useEffect(() => {
    return () => {
      delete window.Cal.instance.inlineEl;
    };
  }, []);`

**Comment by blitzve0** [comment] 2024-01-31 21:37
> > Since this could break a crucial step in our funnel and I have access to `window.Cal`, I came up with a dirty hack which is to call `delete window.Cal.instance.inlineEl` on unmounting the component (I use Vue, but it should also work in React and other SPAs). This removes a reference to an element that no longer exists in the DOM at the time the component is unmounted, and after that, you can mount cal.com embed again.
> > But be careful if you googled this answer - you may break something when the bug is fixed. This method is very dirty and not safe at all.
> 
> Thanks a lot, this works with NextJs too!
> 
> ` useEffect(() => { return () => { delete window.Cal.instance.inlineEl; }; }, []);`

Any issues with this approach, i use context to store some info around this embed
and there a lot of going back and forth between screens and the last screen has this embed
would this break things for me?

**Comment by another-guy** [comment] 2024-01-31 23:18
The `useEffect` with the cleanup did work for me. This is a nasty regression, glad we haven't relied on Embed in production system yet.

**Comment by PeerRich** [comment] 2024-02-20 17:29
didnt see this issue, my bad. i think this is of higher priority and we had the first enterprise customer reporting this too.

we will get this fixed in 3.9! 

thank you all for the patience

**Comment by PeerRich** [comment] 2024-02-20 17:31
there seems to be an open PR https://github.com/calcom/cal.com/pull/13386 that we need to undraft and get merged @hariombalhara

**Comment by keithwillcode** [comment] 2024-02-23 01:13
@Udit-takkar can you please take this over from Hariom.

**Comment by Udit-takkar** [comment] 2024-02-23 12:16
> from the page and retur

Okay checking the PR

**Comment by CarinaWolli** [comment] 2024-03-07 18:35
> Broken in https://github.com/calcom/cal.com/pull/13048

Is this still an issue? I see that this change with the early return and the warning `Inline embed already exists. Ignoring this call` got reverted here: https://github.com/calcom/cal.com/commit/7cffb30daa9a8aa86ed62a8b1dfb82cec3deaa46

**Closed** 2024-03-15 17:37 UTC
Labels: 🐛 bug, High priority, enterprise, embed
