### ISSUE TITLE
Events from CalDAV not taken into consideration when checking availability

### ISSUE THREAD

**Issue by kuba-orlik** [calcom/cal.com#624] opened 2021-09-09 20:05 UTC
### Issue Summary
Appointment selector shows me as available even if I have a single day-long event for a particular date

### Steps to Reproduce

1. Connect a CalDAV server
2. Pick a calendar & confirm
3. In a calendar app, create an event for a given date
4. Open the URL of meeting time picker
5. Select the day containing the event from step 3
6. See that all possible time slots are available, not affected by the event created in step 3

### Technical details
* Browser version: Firefox 92
* Node.js version: 14

**Comment by femyeda** [comment] 2021-09-09 20:38
Fixed in latest commit. Will let you know when deployed.

**Comment by jdaviescoates** [comment] 2021-11-05 22:16
Really looking forward to this being deployed! I'm really loving Cal.com so far, but without CalDAV working properly I can't use it because my Nextcloud CalDAV calendar is my primary calendar.

**Comment by Kovah** [comment] 2021-11-09 21:16
Is there any ETA when this will be deployed? It's basically the only issue holding me back from using Cal right now. :(

**Comment by jdaviescoates** [comment] 2021-11-10 09:13
@Kovah it looks like there are quite a few CalDAV issues that need resolving see #956 - but I'm the same as you, as soon as CalDAV integration actually works I'll start using Cal :)

**Comment by llldar** [comment] 2021-12-13 13:30
cannot repoduce this now.

**Comment by jdaviescoates** [comment] 2021-12-13 14:26
> cannot repoduce this now.

Nor can I. Just tested on cal.com and it does now block out times from my CalDAV calendar!

**Comment by jdaviescoates** [comment] 2022-01-13 12:00
> I just signed up on cal.com and connected my CalDAV Account. This bug is still present.

Works for me using Nextcloud Calendar. What CalDAV are you using @obstschale ?

**Comment by borishinzer** [comment] 2022-01-13 12:41
Same issue here. Tested with Nextcloud 19 and 23

**Comment by obstschale** [comment] 2022-01-13 16:14
I use Synology Calendar. I use CalDav on my MacBook, Android Devices and have no problem at all.

**Comment by amigasoc** [comment] 2022-01-17 07:09
If it's significant, we're seeing this in our logs:

timeZoneName WARN [[lib] caldav_calendar Method not implemented. dateFrom: 2022-02-24T00:00:00+00:00, dateTo: 2022-02-24T23:59:59+00:00, selectedCalendars: [object Object] 

We're connecting to a CalDAV server on Radicale.

**Comment by mathieugp** [comment] 2022-01-17 13:58
I am seeing this problem too. My CalDav compatible server is NextCloud 20.x.

One difference maybe with the other cases above: for some reason, one particular event seems to be taken into account. That event was created by accepting an invitation sent from Google Calendar to my CalDav calendar, while the others were created by me manually. I am using Thunderbird 78.x on Ubuntu 20.04 on the client side.

I will be happy to share any (non personal) information if it can help. :-)

**Comment by KierenB** [comment] 2022-01-23 22:03
Commenting to note that I am also seeing this issue - connecting to Fastmail via caldav.

**Comment by lionux2** [comment] 2022-01-28 19:04
The same issue with Apple Calendar ... tested today, and failing too.

**Comment by ykktrcb7** [comment] 2022-01-31 08:56
Same issue with Baikal server

**Comment by PeerRich** [comment] 2022-01-31 10:50
has this not fixed the bug? https://github.com/calendso/calendso/pull/1649 if not, @natelindev can take a look!

**Comment by jdaviescoates** [comment] 2022-02-04 12:39
I just re-checked and this works fine for me using a Nextcloud calendar. Events on my Nextcloud calendar are taken into consideration are those time slots are not available to book via Cal.com

**Comment by KierenB** [comment] 2022-02-04 16:57
I just checked using cal.com, it's not fixed there yet (not sure if the fix has been deployed there yet or not?)

**Comment by lionux2** [comment] 2022-02-05 09:05
Just checked and not working for me either. Based on jdaviescoates, it works, so maybe his configuration on Nextcloud calendar works. I have multiple ' calendars', such as personal, work, etc... so maybe cal.com does not go through any of them if many exists?

**Comment by PeerRich** [comment] 2022-02-05 09:43
> Just checked and not working for me either. Based on jdaviescoates, it works, so maybe his configuration on Nextcloud calendar works. I have multiple ' calendars', such as personal, work, etc... so maybe cal.com does not go through any of them if many exists?
> 
> 

can you record a loom.com and @natelindev can you take a look?

**Comment by borishinzer** [comment] 2022-02-21 14:01
from our cal server's `/var/log/messages`:
```
Feb 21 14:59:38 cal yarn[3102337]: #033[90m13:59:38.149 timeZoneName #033[39m#033[1m#033[93mWARN#033[39m#033[22m CalendarManager
Feb 21 14:59:38 cal yarn[3102337]: #033[1m#033[97m#033[41m TypeError #033[49m#033[39m#033[22m Only absolute URLs are supported#033[1m#033[4m
Feb 21 14:59:38 cal yarn[3102337]: error stack:#033[24m#033[22m
```
I would guess Nextcloud and Cal timezones are not matching?

**Comment by haccg** [comment] 2022-04-17 20:19
Tried it with Synlogy CalDav-Server.

Works ONLY with the primary calendar.
All other calendars are not working with the collision check.

If you could fix this, it would be very good.

**Comment by jdaviescoates** [comment] 2022-06-08 16:10
> Just checked and not working for me either. Based on jdaviescoates, it works, so maybe his configuration on Nextcloud calendar works. I have multiple ' calendars', such as personal, work, etc... so maybe cal.com does not go through any of them if many exists?

Just to add, I don't have *many* but it is checking again two separate Nextcloud calendars (my primary work and personal calendars). And it's still working nicely for me (just checked again - seems to have got a lot faster too). I'm currently on Nextcloud 24.0.1

**Comment by jdaviescoates** [comment] 2022-06-08 16:58
>  And it's still working nicely for me (just checked again - seems to have got a lot faster too). I'm currently on Nextcloud 24.0.1

Well, it works in that CalDAV events *are* taken into consideration, and appointments created via Cal.com to added to the calendar selected in the options under https://app.cal.com/apps/installed 

However, if I e.g. edit the location of the booking then instead of editing the previously created event a whole *new* event is added to the calendar. I guess I should create a new issue about that...

**Comment by alishaz-polymath** [comment] 2022-07-20 05:09
@jdaviescoates Yes, please create a new issue about that. I'm going ahead and closing this ticket as I have tested that CalDAV events are taken into consideration to block double booking, as you have confirmed as well. 🙏

**Closed by alishaz-polymath** 2022-07-20 05:09 UTC
Labels: 🐛 bug
