### ISSUE TITLE
[CAL-1391] Issue when deleting a date override

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#8055] opened 2023-04-03 08:40 UTC
[https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71](https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71)
[https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71](https://www.loom.com/share/cd0410734b294d3596e600c00fadcb71)

Created via Threads. See full discussion: [https://threads.com/34461164410](https://threads.com/34461164410)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1391](https://linear.app/calcom/issue/CAL-1391/issue-when-deleting-a-date-override)</sub>

**Comment by jacobzukerman** [comment] 2023-04-14 04:24
Ran into the same issue in a self-hosted experience yesterday. It was via the Admin impersonate mode for a Host that had a large number of date overrides created. Glad the bug is captured and it was on my list to try to reproduce it.

**Comment by PeerRich** [comment] 2023-05-14 21:54
@emrysal do you wanna look into this or maybe someone like @CarinaWolli ?

**Comment by PeerRich** [comment] 2023-07-03 08:24
duplicate of https://github.com/calcom/cal.com/issues/8043

**Closed by PeerRich** 2023-07-03 08:24 UTC
Labels: 🐛 bug, 🚧  wip / in the making, ⚡ Quick Wins, Medium priority
