### ISSUE TITLE
[CAL-3483] Private settings of the event disabled after making changes to your event

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#14625] opened 2024-04-17 08:24 UTC
[https://calcom-inc-0470baa6daee.intercom-attachments-3.com/i/o/1023851174/5e8141bfc5c5ca9667fa6789/private+url+button+removed_cut.mp4?expires=1713343770&signature=a9121925c915524966f7c70ed42a884251aafe4510b9376eff6fa6fee63e5b76](https://calcom-inc-0470baa6daee.intercom-attachments-3.com/i/o/1023851174/5e8141bfc5c5ca9667fa6789/private+url+button+removed_cut.mp4?expires=1713343770&signature=a9121925c915524966f7c70ed42a884251aafe4510b9376eff6fa6fee63e5b76)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3483](https://linear.app/calcom/issue/CAL-3483/private-settings-of-the-event-disabled-after-making-changes-to-your)</sub>

**Comment by Udit-takkar** [comment] 2024-04-17 09:49
duplicate of https://github.com/calcom/cal.com/issues/14573

**Closed** 2024-04-22 11:53 UTC
Labels: 🐛 bug, event-types
