### ISSUE TITLE
Copy Link to Event Type

### ISSUE THREAD

**Issue by shivamklr** [calcom/cal.com#10222] opened 2023-07-18 11:41 UTC
### Issue Summary

On the /event-types route there is a runtime error.

### Steps to Reproduce

1. Go to `/event-types`
2. From the list of event types, click on the `Copy Link to Event` button
3. Check console for error logs

Running this in the local environment.
Set NEXT_PUBLIC_WEBAPP_URL='http://app.cal.local:3000' in the .env

### Evidence
![onClickClipboardError](https://github.com/calcom/cal.com/assets/22683064/92861f06-d8ca-4bc3-b1ff-8fb8c3b64408)
![onClickClipboardError2](https://github.com/calcom/cal.com/assets/22683064/b7529dc7-18e7-435e-8024-aaa616a06fb5)

**Comment by Tonie-NG** [comment] 2023-07-18 14:55
Hello @shivamklr I'm interested in this, kindly assign it to me

**Comment by shivamklr** [comment] 2023-07-18 15:03
> Hello @shivamklr I'm interested in this, kindly assign it to me

Feel free to open a PR. Make sure to mention this issue in the PR description.

**Comment by AdityaSingh-02** [comment] 2023-07-18 15:41
Hey @shivamklr This is my first contribution in Cal,
I had a problem, as you mentioned above to set NEXT_PUBLIC_WEBAPP_URL='http://app.cal.local:3000/', and then I updated ORGANIZATIONS_ENABLED=1, then started the server with yarn dx and it is running on localhost:3000 is that okay?
Or should be running on app.cal.local:3000 ?

**Comment by Udit-takkar** [comment] 2023-07-24 15:07
@AdityaSingh-02 you can use localhost:3000

**Comment by bhargavtenali** [comment] 2023-07-25 05:03
Hi @Udit-takkar @shivamklr 
I cant reproduce the issue the above issue by following above steps.
I am not getting any error when I click on `Copy Link to Event` button.
Is the issue fixed ?

**Comment by bhargavtenali** [comment] 2023-07-25 05:14
Hi @Udit-takkar @shivamklr 
The issue seems fixed now.
I cant reproduce it even after following above steps.
Can you check once in local.

**Closed** 2023-07-27 16:41 UTC
Labels: 🐛 bug, ⚡ Quick Wins, Low priority, event-types
