### ISSUE TITLE
changing "add to calendar" in "advanced" event settings leads to a UNAUTHORIZED error

### ISSUE THREAD

**Issue by samuelstroschein** [calcom/cal.com#7227] opened 2023-02-20 13:21 UTC
### Issue Summary

changing "add to calendar" in "advanced" event settings leads to a UNAUTHORIZED error

### Steps to Reproduce

1. Change the default calendar (Google) to a specific calendar (google) 
2. Press save
3. The toast appears

![CleanShot 2023-02-20 at 14 20 41@2x](https://user-images.githubusercontent.com/35429197/220120197-038cefba-5ab9-408c-b571-d62410e5564a.png)

**Comment by PeerRich** [comment] 2023-02-20 14:30
interesting. we will investigate

**Comment by PeerRich** [comment] 2023-02-20 14:37
@Udit-takkar @G3root

**Comment by samuelstroschein** [comment] 2023-02-20 14:38
Maybe related maybe unrelated. Even though the default calendar is my work calendar `@inlang.com`, events are created with my private email and land in both my private google account (which is not my calendar account :O ) and work account. 

![CleanShot 2023-02-20 at 15 37 14@2x](https://user-images.githubusercontent.com/35429197/220135913-28366ac8-fb6c-4823-a140-61986ad8eb3f.png)

**Comment by Udit-takkar** [comment] 2023-02-20 14:54
@samuelstroschein not able to reproduce. can you try going to https://app.cal.com/settings/my-account/calendars and removing and adding calendar again ?

**Comment by samuelstroschein** [comment] 2023-02-20 15:09
Ah yeah, the select value needs to be changed (Step 1). @Udit-takkar are you able to reproduce?

**Comment by Udit-takkar** [comment] 2023-02-20 15:10
https://user-images.githubusercontent.com/53316345/220142745-9b247b0f-237b-4793-aff5-b1a1e293fddc.mov

@G3root working fine for me

**Comment by G3root** [comment] 2023-02-20 15:16
[Screencast 2023-02-20 20:44:41.webm](https://user-images.githubusercontent.com/84864519/220143958-ef53fe8e-72a6-4f89-ae11-603246a2078a.webm)

you have to select the same account.

**Comment by Udit-takkar** [comment] 2023-02-20 15:25
https://user-images.githubusercontent.com/53316345/220145798-fd39ad14-e4f2-4aaa-bf1a-6d3485843840.mov

tried all combinations

**Comment by G3root** [comment] 2023-02-21 10:10
weird though 🤔 . tried locally but not able to reproduce 

[Screencast 2023-02-21 15:38:44.webm](https://user-images.githubusercontent.com/84864519/220315023-97c8d2db-abc2-4fee-b10c-1eeb129f2925.webm)


cc: @emrysal

**Comment by emrysal** [comment] 2023-05-26 11:33
Can no longer reproduce, closing 👍

**Closed by emrysal** 2023-05-26 11:33 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, High priority
