### ISSUE TITLE
[CAL-2054] UI: We need feedback after clicking buttons

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#9799] opened 2023-06-26 11:35 UTC
When you click buttons in our app you don't get any feedback that anything is happening. Sometimes there's a delay of a few seconds and it feels like there is nothing happening.

Our buttons should have a loading state as per designs when clicked and awaiting action

[https://share.cleanshot.com/GBKg9Ttm](https://share.cleanshot.com/GBKg9Ttm)

[View in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=198%3A41491&mode=design&t=Oi0IqR0HMX0kmt7V-1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2054](https://linear.app/calcom/issue/CAL-2054/ui-we-need-feedback-after-clicking-buttons)</sub>

**Comment by kemilbeltre** [comment] 2023-06-26 13:28
@Jaibles Hi, are you suggesting adding something like a progress bar (maybe like the GitHub uses)?

**Comment by ashish1233** [comment] 2023-06-26 18:48
Hi @Jaibles , can we get acess to [SyncLinear.com](https://synclinear.com/) | [CAL-2054](https://linear.app/calcom/issue/CAL-2054/ui-we-need-feedback-after-clicking-buttons) ?

**Comment by Jaibles** [comment] 2023-06-26 18:50
@ashish1233 the linear sync just copies over the content from Linear to Github. There's nothing to access that's not already shown here.

**Comment by kemilbeltre** [comment] 2023-06-26 20:27
@Jaibles please assign this to me. Thanks

**Comment by shammirbaig** [comment] 2023-06-27 10:01
@Jaibles Not able to reproduce it,working fine for me though

**Comment by kemilbeltre** [comment] 2023-06-27 10:33
@Jaibles The loading is already implemented in the button component (see the screenshot), but is probably happening is that in some pages the flat `isLoading` isn't added. Could you please share the pages where you think we're not getting this feedback? Thanks

![image](https://github.com/calcom/cal.com/assets/20250204/20e418f2-a944-4f93-812f-39077d7de5ea)

**Comment by Jaibles** [comment] 2023-06-27 10:43
> @Jaibles The loading is already implemented in the button component (see the screenshot), but is probably happening is that in some pages the flat `isLoading` isn't added. Could you please share the pages where you think we're not getting this feedback? Thanks
> 
> ![image](https://user-images.githubusercontent.com/20250204/249122092-20e418f2-a944-4f93-812f-39077d7de5ea.png)

Thanks @kemilbeltre I'll compile a list.

**Comment by PeerRich** [comment] 2023-06-28 16:41
ideally we address the slowness first, but i am not against more loading states across the app

lets close this and open specific issues for each page

**Closed by PeerRich** 2023-06-28 16:41 UTC
Labels: 🐛 bug, 🧹 Improvements, Medium priority, UI

**Comment by Jaibles** [comment] 2023-06-29 12:57
Yea I'll make separate issues. Pretty sure last time I encountered it was actually on the public booker. But will follow up
