### ISSUE TITLE
Get availability from ics-URL

### ISSUE THREAD

**Issue by mountainsandcode** [calcom/cal.com#2054] opened 2022-03-04 08:40 UTC
### Is your proposal related to a problem?

I would like to be able to share my calendar availability automatically without having to grant full CalDav access.

### Describe the solution you'd like

Many calendar providers offer a URL with free/busy information only, i.e., no details of calendar events. That URL returns an ics-file with events, except that the event details are hidden.

_Example: Fastmail.com_
![Screenshot 2022-03-04 at 09 41 25](https://user-images.githubusercontent.com/26942220/156729337-58ba6c28-9632-4e7b-8667-abe84db93930.png)

Being able to add URL to an .ics/ical file as an Integration for availability. This would be read-only, i.e., confirmed events cannot be scheduled with this integration.

Ideally, it should be possible to add several such URLs (i.e., multiple calendars, e.g., one for private, one for work, etc.)

### Describe alternatives you've considered

CalDav, but this requires me to share all details of the calendar.

### Additional context

Such an approach would also allow integration with some other calendar platforms that are not yet supported but which do support creating a secret URL for an ics-file.

**Comment by milospuac** [comment] 2022-03-04 09:10
Thanks for the suggesition. Our team will have a look into this

**Comment by real-or-random** [comment] 2022-07-18 18:20
semi-duplicate of #3167

**Comment by aspiers** [comment] 2022-08-11 12:32
I'm not sure I understand the above description very well, but isn't it an _exact_ duplicate of #3167?  @mountainsandcode Please can you confirm that you are asking for the ability for cal.com to import availability from ICS feed URLs, rather than for cal.com to export an ICS feed?

**Comment by mountainsandcode** [comment] 2022-08-11 13:18
@aspiers Indeed there is some overlap, though #3167 was raised later so one could say that one is the duplicate ;) In any case, doesn't matter which issue we are tracking this under :) Happy to close this one as the other one is perhaps more active/ documented.

I would fully agree with @real-or-random's suggestion - I think the behaviour should be the same regardless of whether we are considering VEVENTs or VFREEBUSY.

**Comment by aspiers** [comment] 2022-08-28 19:52
Thanks for the clarifications! And I also agree with @real-or-random and @mountainsandcode that imports of `VFREEBUSY` and "normal" ICS files with `VEVENT`s can both be dealt with by the same feature implementation.

Please note that I have proposed #3810 as a request for the "opposite" feature, i.e. cal.com being able to _export_ an aggregated ICS feed (which could be a collection of either `VFREEBUSY` or `VEVENT`) to other systems, in contrast to this and #3167 which are both about cal.com _importing_ an ICS feed.  I see great value in both features, even though they are pretty much exact opposites of each other.

**Comment by xeruf** [comment] 2023-02-11 16:02
I recommend to consider some of the options NC Appointments offers as well :)
https://github.com/SergeyMosin/Appointments

**Comment by penyuan** [comment] 2023-02-11 16:07
> I recommend to consider some of the options NC Appointments offers as well :) https://github.com/SergeyMosin/Appointments

Thank you @xeruf for the suggestion. Just to confirm: is the Nextcloud Appointments app you linked to capable of getting availability from an ICS URL?

**Comment by xeruf** [comment] 2023-02-15 18:26
I don't think so, but it should not make much of a difference in terms of implementation - and weekly template and slots from calendar "FREE" events are also good considerations.

**Comment by lhunath** [comment] 2023-06-17 15:00
given that this capability would unlock automatic integration with a vast array of calendar services without needing to do service-specific integrations (for instance, Proton calendars, and any other calendar host), I think it makes sense to drop the low-priority label on this ticket.

**Comment by alishaz-polymath** [comment] 2023-06-21 10:17
Closing in favor of issue #3167

**Closed by alishaz-polymath** 2023-06-21 10:17 UTC
Labels: ✨ feature, Low priority
