### ISSUE TITLE
buffer before and buffer after meeting as advanced event-types

### ISSUE THREAD

**Issue by baileypumfleet** [calcom/cal.com#1455] opened 2022-01-10 22:11 UTC
must-have feature as seen in all other scheduling tools

**Comment by manjufy** [comment] 2022-01-15 04:16
This is a nice feature to have +1

**Comment by SylvainRamousse** [comment] 2022-02-01 14:13
+1 !

**Comment by PeerRich** [comment] 2022-02-22 00:14
duplicate of #1398

**Closed by PeerRich** 2022-02-22 00:14 UTC
Labels: ✨ feature
