### ISSUE TITLE
Time Frames for Working Hours Time Zone

### ISSUE THREAD

**Issue by chrisspiegl** [calcom/cal.com#10013] opened 2023-07-08 13:31 UTC
### Is your proposal related to a problem?

I travel a lot myself and would like to set specific time zones for certain date ranges in the Availability / Working Hours.

At the moment I can only set one Time Zone and then when I travel to a different location, I have to block the calendar primitively because the "normal working hours" may not work there.

### Describe the solution you'd like

The solution would be that in the Availability / Working Hours I could not only set the Time Zone but also set a certain date range from when to when a certain Time Zone is active.

E.g.:

- Default Time Zone: North America/New York
- 2023-07-08 - 2023-07-24 => Europe/Berlin
- 2023-07-25 - 2023-08-30 => Indonesia/Denpasar
- etc.

This would make it so that the time slots available are always "my working hours" and display accordingly.

Cheers, Chris

**Comment by PeerRich** [comment] 2023-07-08 19:05
this is planned, a duplicate of https://github.com/calcom/cal.com/issues/6790

**Closed by PeerRich** 2023-07-08 19:05 UTC
Labels: ✨ feature, bookings
