### ISSUE TITLE
The Location is not shown when booking a meeting 

### ISSUE THREAD

**Issue by MuriloAmarals** [calcom/cal.com#2923] opened 2022-05-30 13:15 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you add a location to your meeting, it doesn't matter which option of location you choose. I think would be better if it appeared along with the other specs.

### Steps to Reproduce

https://www.loom.com/share/ff551e2f44bd4889aa66cb6a5476c405

**Comment by alannnc** [comment] 2022-05-30 20:23
We've been discussing this recently, and AFAI Location gets hidden as a security measure in that screen. Location it's shared through email later.
We can obviously improve that part on our end with these new options in event page.

- If user wants to share location on booking page.
- Don't share Location till a booking its confirmed/payed.

**Comment by sean-brydon** [comment] 2022-05-31 11:19
Hello - there was actually a feature just merged to give the user the option if they want to enable the location to be shown publicly #2752

**Comment by sean-brydon** [comment] 2022-05-31 17:54
Closing this for now as this has been resolved - please reopen if this was not your intended solution

**Closed by sean-brydon** 2022-05-31 17:54 UTC
