### ISSUE TITLE
Action buttons (ie: Confirm Booking) on bookings page out of view on smaller screen. 

### ISSUE THREAD

**Issue by isaiahdahl** [calcom/cal.com#4712] opened 2022-09-26 18:13 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Buttons to confirm booking are not in view on a smaller screen size.

![CleanShot 2022-09-26 at 11 12 46](https://user-images.githubusercontent.com/23046374/192349979-1a2d7186-9657-4b19-8cd0-4e43fda5aced.png)

![CleanShot 2022-09-26 at 11 09 04](https://user-images.githubusercontent.com/23046374/192349268-32321654-7b5a-428a-9eec-39fc96c3b3ef.png)

I think this is a UX/UI bug. The most important buttons on this page are not in view on a smaller screen size. One of our team members didn't even realize that the event still had to be confirmed because it didn't look any different than the other booked bookings.

Even at a 1200px wide screen size, you still can't see the buttons.  And it's not like it screams at you that it's horizontally scrollable.

In the v2 beta it's not even scrollable so you can't get to them at all.

**Comment by Toledodev** [comment] 2022-09-26 18:44
Hey @isaiahdahl this error did not occur on my machine :+1: 
![Screenshot from 2022-09-26 15-42-50](https://user-images.githubusercontent.com/87545086/192355482-638b4174-caee-4f54-92ec-dbba8077136d.png)

**Comment by isaiahdahl** [comment] 2022-09-26 18:45
I bet you that the shorter title on the event makes that happen. 

What happens if you made the event title long like my examples.

**Comment by Toledodev** [comment] 2022-09-26 23:41
Ok, I will take a look on this :+1:

**Comment by davidtaing** [comment] 2022-09-28 10:41
This seems to be a duplicate of issue [#4445](https://github.com/calcom/cal.com/issues/4445)

**Comment by CarinaWolli** [comment] 2022-09-30 21:06
Already fixed #4769

**Closed by CarinaWolli** 2022-09-30 21:06 UTC
