### ISSUE TITLE
[CAL-1598] new booker has no title (and likely no meta data?)

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8522] opened 2023-04-25 18:57 UTC
![CleanShot 2023-04-25 at 20.57.02@2x.jpg](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/ae9b3feb-e4ea-4fde-b41e-35b7fc416460/53992bcd-52f6-438f-8baa-6e3c7c06b1ee)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1598](https://linear.app/calcom/issue/CAL-1598/new-booker-has-no-title-and-likely-no-meta-data)</sub>

**Comment by ameeetgaikwad** [comment] 2023-04-30 04:18
assign me please!

**Comment by pranjalg13** [comment] 2023-04-30 16:07
Can you please ellaborate the issue @PeerRich ?

**Comment by santosh-kuchetti** [comment] 2023-05-01 11:28
@PeerRich 
Can you please elaborate the bug reproducing steps
And please assign this issue to me. I would love to work on it.

**Comment by zeeshanbhati** [comment] 2023-05-02 23:56
@santosh-kuchetti  @pranjalg13 The issue is about the new booker component which is under development , The title of page and metadata are missing in the new booker component

If you see the URL here it is: ```localhost:3000/user/[type]``` it contains the type name and user name as well as metadata if you hover over it you will find out

![image](https://user-images.githubusercontent.com/53969232/235809059-dfed306b-8f62-45eb-9685-d813fc97b733.png)


on the other hand, if i head to the new-booker component URL which is : ```localhost:3000/new-booker/user/[type]``` the title and metadata is missing

![image](https://user-images.githubusercontent.com/53969232/235809415-98aac08a-471d-4971-b7a9-c8d71c099a8a.png)

**Comment by JeroenReumkens** [comment] 2023-05-11 15:56
Will be fixed by [https://github.com/calcom/cal.com/pull/8697](https://github.com/calcom/cal.com/pull/8697)

**Closed** 2023-05-11 16:25 UTC
Labels: 🐛 bug
