### ISSUE TITLE
[CAL-1596] more misc frontend fixes

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#8519] opened 2023-04-25 17:53 UTC
- [ ] ![CleanShot 2023-04-25 at 19 52 47@2x](https://user-images.githubusercontent.com/8019099/234361029-0d43b688-cd4f-4745-974b-0e85be98da15.jpg)

https://github.com/calcom/cal.com/assets/53316345/6fe0d969-6f15-4b7d-a5d1-b67dfadff024

How to reproduce?

1) go to /settings/my-account/profile
2) This is the premium username input field. 

<sub>[CAL-1596](https://linear.app/calcom/issue/CAL-1596/more-misc-frontend-fixes)</sub>

**Comment by siddanth-6365** [comment] 2023-04-29 16:24
hey whats the issue should i make the star in the middle ? should i add margin from top

**Comment by twi05** [comment] 2023-04-29 18:00
in which file or page it is. I'm unable to find

**Comment by santosh-kuchetti** [comment] 2023-05-01 11:30
@PeerRich
Can you please elaborate the bug-reproducing steps
And please assign this issue to me. I would love to work on it.

**Comment by PeerRich** [comment] 2023-05-08 08:44
ah sorry. this was a ticket for myself but feel free to fix.

the star is not centered

this shows up for premium usernames (i.e. first names)

**Comment by prakhart4** [comment] 2023-05-09 07:38
Found and fixed the alignment.

**Comment by Udit-takkar** [comment] 2023-05-10 09:34
@twi05 @santosh-kuchetti have added the instruction in the description. you can make some changes locally to see the premium input field just have a look at code once

**Comment by santosh-kuchetti** [comment] 2023-05-10 11:19
@Udit-takkar, @PeerRich  Hi, can I get the demo premium user usedetails for quickly checking one issue there

**Comment by prakhart4** [comment] 2023-05-12 10:47
Fixed the margin
![Screenshot from 2023-05-12 15-35-19](https://github.com/calcom/cal.com/assets/27767744/385c3a5a-c217-4b2d-af2d-9cb63e49a7f8)

For non-premium users, the check icon was also not centered
![Screenshot from 2023-05-12 15-37-43](https://github.com/calcom/cal.com/assets/27767744/8ff064a2-bfa0-4be0-ac36-c30a47d71de2)

Fixed that too
![Screenshot from 2023-05-12 15-36-02](https://github.com/calcom/cal.com/assets/27767744/65ea7ed4-1e1e-49bc-9924-7198cd03b252)

Should I create a PR?

**Comment by prakhart4** [comment] 2023-05-12 11:37
When the web app is self-hosted a different text field component is used:

```js
export const UsernameAvailability = IS_SELF_HOSTED ? UsernameTextfield : PremiumTextfield;
```

And it looks like this
![image](https://github.com/calcom/cal.com/assets/27767744/edf89fdf-5375-4897-9e46-5e649ba284b3)

Do you think this should be fixed?

**Comment by santosh-kuchetti** [comment] 2023-05-13 05:57
PR is raised to this issue
https://github.com/calcom/cal.com/pull/8872

@zomars  please look into it

**Closed** 2023-05-14 20:30 UTC
Labels: 🧹 Improvements, ⚡ Quick Wins, Low priority
