### ISSUE TITLE
Able to bypass signin screen in incognito window,  

### ISSUE THREAD

**Issue by riz-like-u** [calcom/cal.com#2826] opened 2022-05-19 20:44 UTC
Login to chrome browser and then open a private window if I navigate to localhost\event-types it let me through

**Comment by Azhariel** [comment] 2022-05-19 23:20
Are you able to reproduce it consistently? Are there any other steps?
It's returning me the expected 401 and redirect

**Comment by gibranlamarca** [comment] 2022-05-20 12:26
I couldn't reproduce the issue either!

**Comment by PeerRich** [comment] 2022-05-20 14:10
@riz-like-u what information is being shown? Can you provide a loom.com video or birdeatsbug.com video? If not, we need to close this as no one of us can reproduce it.

what browser are you using? Maybe your incognito mode is taking cache/cookies from your main browser

**Closed** 2023-01-26 13:13 UTC
Labels: 🐛 bug, 🤔 can't reproduce
