### ISSUE TITLE
[CAL-174] Managed Events — Cal.com Style

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#5054] opened 2022-10-17 17:46 UTC
Managed Events for Organizations which is what Calendly currently offers. When a customer is added to a “Team,” a company can have “templates” set up for various event types.

So when a new employee is added to say the “legal team,” then they get certain event types like docusigning. Also, if the templates are adjusted at the team level, the Admin has the ability to push updates to all the other team members in that team.

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by PeerRich** [comment] 2023-01-27 16:05
potentially a duplicate @Jaibles

**Comment by Jaibles** [comment] 2023-02-02 11:53
Closing. Duplicate of https://github.com/calcom/cal.com/issues/6116 and that has a little more context.

**Closed by Jaibles** 2023-02-02 11:53 UTC
Labels: ✨ feature, 👥 teams
