### ISSUE TITLE
[CAL-248 ]Problem with the integration of a button in react

### ISSUE THREAD

**Issue by flaviomoceri** [calcom/cal.com#5206] opened 2022-10-25 13:45 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Put useEffect in the component
2. Put data-cal-link in a buttton using this url [https://cal.com/team/[your_username]](https://cal.com/team/%5Byour_username%5D)
3. When you try to click this button and then click an event it will appear this url [https://cal.com/team/[slug]/[your_username]/30-minuti-meeting](https://cal.com/team/%5Bslug%5D/%5Byour_username%5D/30-minuti-meeting). The problem is because in the url there is [slug] and obv it will appear cal link doesn't work. Please fix that

**Comment by harshsinghatz** [comment] 2022-10-25 14:38
I didn't quite understand your problem, [Sandbox Link](https://codesandbox.io/s/embed-popup-on-click-of-an-existing-element-demo-react-forked-c5g8lk?file=/src/App.js) maybe this will help!

**Comment by flaviomoceri** [comment] 2022-10-25 14:41
Ok, your example is perfect, now try to put the link of a team, like
team/[team_name], just this
and you will see that when you will click an event it will appear "This
page doesn't exist"

Il giorno mar 25 ott 2022 alle ore 16:39 Harsh Singh <
***@***.***> ha scritto:

**Comment by flaviomoceri** [comment] 2022-10-25 14:44
Because there is this link team/[slug]/[team_name]/[event_name]. the
problem is because in the url there is [slug]. It should be just
team/[team_name]/[event_name]

Il giorno mar 25 ott 2022 alle ore 16:41 Flavio Moceri <
***@***.***> ha scritto:

**Comment by flaviomoceri** [comment] 2022-10-25 14:54
Yes, beacuse you have to do this. Create a team and for this team create an event

**Comment by flaviomoceri** [comment] 2022-10-25 14:55
Now when you will try again to click the button and then you will click the event of the team, the link doesn't work becase there is this term [slug] inside

**Comment by flaviomoceri** [comment] 2022-10-25 14:57
You need to create an event for the team and try to book the event of the team

**Comment by flaviomoceri** [comment] 2022-10-25 15:03
Do you see it?

**Comment by harshsinghatz** [comment] 2022-10-25 15:10
Yeah, now I am able to see 
![image](https://user-images.githubusercontent.com/51085015/197811997-a6784f33-d5e8-4a1b-82a3-3c46062b79f7.png)

**Comment by flaviomoceri** [comment] 2022-10-25 15:11
Finally, please fix it, it is a big problem for me, nobody can book trough the link

**Comment by flaviomoceri** [comment] 2022-10-25 15:53
When the problem will be fixed?

**Comment by harshsinghatz** [comment] 2022-10-25 16:07
I am looking into it, will try to do it asap

**Comment by flaviomoceri** [comment] 2022-10-25 16:15
Thanks, I thought that this error was easy to fix, because the url is corret but there is this term inside [slug] and for this reason the link doesn't work. Please write me when you will fix it

**Comment by Udit-takkar** [comment] 2022-10-25 16:18
closing this because duplicate of https://github.com/calcom/cal.com/issues/5196

**Closed by Udit-takkar** 2022-10-25 16:18 UTC
