### ISSUE TITLE
Unable to add new location to event.

### ISSUE THREAD

**Issue by heyanurag** [calcom/cal.com#7191] opened 2023-02-18 09:03 UTC
### Issue Summary

Previously I used to see a modal asking me the type of location I want to add ([something like this](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1739%3A78022&t=FpoXhi0rABWhdMj2-0)) but now I only see the edit location modal with no other option.

### Steps to Reproduce

1. Go to Edit Event
2. Click on Add location

Recording - https://www.loom.com/share/c7a063dc50f042fd9c54df56435243fe

**Comment by PeerRich** [comment] 2023-02-18 15:31
something is wrong with lazyloading @emrysal @zomars

**Comment by hariombalhara** [comment] 2023-02-18 16:47
This is fixed now.

**Closed by hariombalhara** 2023-02-18 16:47 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, High priority, 📉 regressing

**Comment by harshsinghatz** [comment] 2023-02-18 19:38
@hariombalhara This seem to be caused by a hook added yesterday which gets the mount state and it is referenced in useTheme. 
The RCA for this was that change in ref was not causing re-render due to which even though the ref's current was getting changed, isReady was still holding it's inital value (unchanged) i.e false
