### ISSUE TITLE
[CAL-43] Social cards improved

### ISSUE THREAD

**Issue by sean-brydon** [calcom/cal.com#4919] opened 2022-10-09 12:01 UTC
Currently social cards don’t look the best and could be very off putting to click 

![0FB1982E-86A9-46A5-A83F-7962C841E416.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/3dc6fb90-0c34-4f6f-940d-c770c468f9b7/2f5ad26e-cac4-42a2-a140-b052af532c02)

> From [Linear-GitHub Sync](https://synclinear.com)

**Comment by Udit-takkar** [comment] 2022-10-24 15:20
I will try to fix this issue. 

duplicate of [https://linear.app/calcom/issue/CAL-163/i18n-with-better-defaults](https://linear.app/calcom/issue/CAL-163/i18n-with-better-defaults).

**Comment by sean-brydon** [comment] 2022-10-24 16:32
@udit Im not sure if this got picked up by @jeroen and @peerrich

**Comment by Udit-takkar** [comment] 2022-10-26 12:25
similar to [https://linear.app/calcom/issue/CAL-163/i18n-with-better-defaults](https://linear.app/calcom/issue/CAL-163/i18n-with-better-defaults) . for app store it has been fixed. i will also fix for other pages as well.

**Comment by Udit-takkar** [comment] 2022-10-29 19:23
This has been fixed [https://www.opengraph.xyz/url/https%3A%2F%2Fapp.cal.com%2Fapps](https://www.opengraph.xyz/url/https%3A%2F%2Fapp.cal.com%2Fapps) and sometimes it doesn't load because it is accessing browser cache. try adding a query param and the social card would load completely fine on twitter.

**Comment by PeerRich** [comment] 2022-10-30 20:31
try posting this on twitter tho

**Comment by PeerRich** [comment] 2022-10-30 20:32
![CleanShot 2022-10-30 at 20.32.01@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9774553d-c2b9-43dd-b690-3e92b6977c7f/9839bf56-3a64-4df7-982f-1536117c26e8)

not working

**Comment by Udit-takkar** [comment] 2022-10-30 20:40
@PeerRich the title and description are loading fine. wasn't this the issue ?
and this https://cal.com/og-image.png social card image seem to be deleted .

**Comment by PeerRich** [comment] 2022-10-30 20:51
oh ok yeah title and description are ok, og-image is not loading correctly. we can close this and open another ticket for @jeroen who worked on og-image

**Closed** 2022-10-30 20:51 UTC

**Comment by JeroenReumkens** [comment] 2022-10-31 08:02
The issue was that we have a robots.txt disallowing access to anything behind /api. That indeed caused twitter to not load these images. I've created a PR for that this morning 😄 [https://github.com/calcom/cal.com/pull/5283](https://github.com/calcom/cal.com/pull/5283)
