### ISSUE TITLE
[CAL-985] Make.com App

### ISSUE THREAD

**Issue by bstvairet** [calcom/cal.com#6846] opened 2023-02-02 12:21 UTC
### Is your proposal related to a problem?

Direct integration with Make.com

Automate actions as much as possible but also track time spent online.

### Describe the solution you'd like

A direct integration with Make.com greatly simplifies the implementation of these automations at a very low cost.

### Describe alternatives you've considered

The webhook works, but it's really not very comfortable in terms of handling.

### Additional context

No.

<sub>[CAL-985](https://linear.app/calcom/issue/CAL-985/makecom-app)</sub>

**Comment by PeerRich** [comment] 2023-02-02 12:36
duplicate of https://github.com/calcom/cal.com/issues/1550

**Closed by PeerRich** 2023-02-02 12:36 UTC
Labels: ✨ feature, 🙋🏻‍♂️help wanted, 📱 app, linear
