### ISSUE TITLE
File upload as booking question

### ISSUE THREAD

**Issue by RainerZufall9393** [calcom/cal.com#10378] opened 2023-07-25 17:13 UTC
Can you make it possible to query files as a booking question? For example, PDFs, Google Doc files, etc.

For example, Acuity Scheduling has this capability and I used to use this for intra-company routing of call notes.

**Comment by PeerRich** [comment] 2023-07-27 08:29
already work in progress, duplicate of #6939

**Closed by PeerRich** 2023-07-27 08:29 UTC
Labels: ✨ feature, bookings
