### ISSUE TITLE
[CAL-1711] Add: Default Timezone based on user location while in getting started steps

### ISSUE THREAD

**Issue by harshsinghatz** [calcom/cal.com#5344] opened 2022-11-03 09:06 UTC
### Is your proposal related to a problem?

(Write your answer here.)

![image](https://user-images.githubusercontent.com/51085015/199682009-4fe406e7-7167-4963-af64-5096623461dc.png)

### Describe the solution you'd like
1. User should be able to get timezone according to his location
2. Getting the geolocation and selecting appropriate dropdown options

<sub>[CAL-1711](https://linear.app/calcom/issue/CAL-1711/add-default-timezone-based-on-user-location-while-in-getting-started)</sub>

**Comment by harshsinghatz** [comment] 2022-11-03 09:09
I would like to pick this task, if this is something we can apply @Jaibles

**Comment by harshsinghatz** [comment] 2022-11-04 08:48
@PeerRich Can I implement this?

**Comment by Jaibles** [comment] 2022-11-04 10:36
Are we not doing this based on the browser already?

**Comment by MatheusBeniniF** [comment] 2022-11-04 10:45
@Jaibles, I saw this issue and realized that the timezone of some users is auto-set when it is created, I made a change and now we always get the timezone directly from the browser with dayjs, do you want me to open PR?

**Comment by harshsinghatz** [comment] 2022-11-04 10:52
@Jaibles Currently we give an option to the user to adjust the timezone according to their location but that only happens after the getting started step. 
This issue is for adjusting the timezone while creating the step.

**Comment by harshsinghatz** [comment] 2022-11-04 10:57
> @Jaibles, I saw this issue and realized that the timezone of some users is auto-set when it is created, I made a change and now we always get the timezone directly from the browser with dayjs, do you want me to open PR?

@MatheusBeniniF You're talking about the getting started step right?

**Comment by MatheusBeniniF** [comment] 2022-11-04 10:58
@harshsinghatz yes

**Comment by Jaibles** [comment] 2022-11-04 11:01
So to clarify, currently in the Getting Started step we are not getting the timezone directly from the browser... we need to make a change to make it so that we do?

**Comment by harshsinghatz** [comment] 2022-11-04 11:02
@Jaibles yep thats right

**Comment by harshsinghatz** [comment] 2022-11-04 11:04
@MatheusBeniniF has already done the changes, @Jaibles do you think this is something we should implement?

**Comment by Jaibles** [comment] 2022-11-04 11:16
I think getting the time directly from the browser in the Getting Started step is something we should implement, yes.

**Comment by harshsinghatz** [comment] 2022-11-04 11:23
@Jaibles cool, @MatheusBeniniF you can create the PR!

**Comment by niteshsingh1357** [comment] 2022-11-04 11:36
Hey @Jaibles I believe this was previously implemented [here](https://github.com/calcom/cal.com/pull/3677), not sure why it got reverted

**Comment by PeerRich** [comment] 2023-05-17 20:28
has this been merged @MatheusBeniniF ?

**Comment by MatheusBeniniF** [comment] 2023-05-18 12:07
Hey @PeerRich, yes, the issue has already been solved, take a look: https://www.loom.com/share/9682b2cb4d554b49995a582cca80f88b

my current hour: 
![image](https://github.com/calcom/cal.com/assets/88898100/1d40684d-e933-464a-9339-4497694b9c28)

**Comment by keithwillcode** [comment] 2023-06-09 15:36
Closing because @MatheusBeniniF confirmed this is fixed.

**Closed by keithwillcode** 2023-06-09 15:36 UTC
Labels: ✨ feature, 👩‍🔬 needs investigation, High priority
