### ISSUE TITLE
[CAL-3705] Rescheduling a booking with a broken calendar integration prevents rescheduled emails from being sent.

### ISSUE THREAD

**Issue by joeauyeung** [calcom/cal.com#15034] opened 2024-05-14 20:01 UTC
When a booking is made with a broken calendar integration we still create the booking reference without a `uid`.

When `updateEvent()` is called under the calendar manager, we throw an error when the `uid` isn't present, thus stopping the execution of code that sends rescheduling emails.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3705](https://linear.app/calcom/issue/CAL-3705/rescheduling-a-booking-with-a-broken-calendar-integration-prevents)</sub>

**Comment by jkdowdle** [comment] 2024-07-22 16:17
Any update here? I ran into an issue the other day, I noticed that after I disconnected and reconnected my calendar that it corrupted the existing booking I can. As the guest I was no longer to go through the full flow to reschedule - While it seemed like a new booking was created, the original was not removed and an error was thrown. 

Would this issue solve this problem?

https://files.slack.com/files-pri/T06CGBR8P6D-F07D6FE5AMS/image.png

**Comment by emrysal** [comment] 2024-09-27 23:14
Hi @jkdowdle @joeauyeung - update here.

I tested through the entire logic / connected calendar, disconnected calendar, with requiresConfirmation & without - there's slightly different flows here. My conclusion is even though the calendarReference.uid is not set (and there's a useless reference there) it does still sent email communications as expected. I was not able to reproduce the behaviour described in this issue.

@jkdowdle We recently fixes an issue with booking reference that does resemble the issue you are describing (although I'm unable to access your image as the slack server is behind an auth wall).

@joeauyeung as email sending continues to function; I will close this; but will create a follow up issue because we shouldn't be creating references at all in this situation, and we are.

**Closed by emrysal** 2024-09-27 23:14 UTC
Labels: 🐛 bug, linear, High priority, core, calendar-apps, foundation
