### ISSUE TITLE
Unable to modify any option in the `Advanced` section of Event Types

### ISSUE THREAD

**Issue by avinal** [calcom/cal.com#6779] opened 2023-01-30 08:32 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I am trying to modify a few options in the Advanced section of Event Types like requiring confirmation. But when I click on save it says `UNAUTHORIZED`

### Steps to Reproduce

1. Go to **Event Types**
2. Choose any event
3. Go to the **Advanced** settings
4. Change any options
5. Click on **Save**

![image](https://user-images.githubusercontent.com/74113200/215424920-bfdeae7a-b3c0-424b-8eca-b31695d887a8.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

As per [pricing](https://cal.com/pricing) page there is no mention that advanced settings cannot be changed.  Some options may require but they are already mentioned by a badge.

### Technical details

- Firefox 109.0
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o574544.ingest.sentry.io/api/4504055091625984/envelope/?sentry_key=a1ea40f454a84538876a4b18e1c360d4&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.20.0. (Reason: CORS request did not succeed). Status code: (null). 2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o574544.ingest.sentry.io/api/4504055091625984/envelope/?sentry_key=a1ea40f454a84538876a4b18e1c360d4&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.20.0. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o574544.ingest.sentry.io/api/4504055091625984/envelope/?sentry_key=a1ea40f454a84538876a4b18e1c360d4&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.20.0. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o574544.ingest.sentry.io/api/4504055091625984/envelope/?sentry_key=a1ea40f454a84538876a4b18e1c360d4&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.20.0. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o574544.ingest.sentry.io/api/4504055091625984/envelope/?sentry_key=a1ea40f454a84538876a4b18e1c360d4&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.20.0. (Reason: CORS request did not succeed). Status code: (null).
XHRPOSThttps://app.cal.com/api/trpc/viewer.eventTypes.update?batch=1
[HTTP/2 401 Unauthorized 1449ms]

 << mutation #34 viewer.eventTypes.update  
Object { input: {…}, result: TRPCClientError, elapsedMs: 1493, context: {} }
_app-dd4f97ab00da7eda.js:2:15536
```
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment] 2023-01-31 17:10
can you log out and log in again? seems like a session error

**Comment by avinal** [comment] 2023-01-31 17:23
[Screencast from 2023-01-31 22-49-47.webm](https://user-images.githubusercontent.com/74113200/215835554-3f1d2d14-1d05-4b88-86d7-09e4446bfad2.webm)
I tried re-logging. Doesn't work. Tried a different browser(chrome) and an incognito tab too.

**Comment by PeerRich** [comment] 2023-01-31 22:15
@Udit-takkar @G3root can someone of you investigate this?

**Comment by PeerRich** [comment] 2023-01-31 22:16
> As per [pricing](https://cal.com/pricing) page there is no mention that advanced settings cannot be changed. Some options may require but they are already mentioned by a badge.

this is unrelated

**Comment by Udit-takkar** [comment] 2023-02-01 01:24
@PeerRich i have seen this error before it is because of some migration problem in the prod database where event type owner is null

**Comment by avinal** [comment] 2023-02-01 06:16
One more detail I wanted to add is, if I delete an event and create a new one, it works fine. Only the events that existed since default are giving this error. I think it broke after some version upgrade.

**Comment by PeerRich** [comment] 2023-02-01 09:00
oh interesting. I think that could be a broken migraton indeed. if its fixed with a new event-type i will close this because i cant reproduce it

**Closed by PeerRich** 2023-02-01 09:00 UTC
Labels: 🤔 can't reproduce

**Comment by avinal** [comment] 2023-02-01 10:16
That is okay, It would be nice to reflect this in any of the docs. So that users can migrate their events themselves. Thanks
