### ISSUE TITLE
Change background color so text wont disappear(UI improvement)

### ISSUE THREAD

**Issue by RayAsh37** [calcom/cal.com#8816] opened 2023-05-10 11:24 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Hovering over the button makes the text disappear completely in dark mode(unsure about light mode)
[improve UI.webm](https://github.com/calcom/cal.com/assets/70441807/d13d14b5-4578-4f53-a3c4-7d738b878b50)

### Steps to Reproduce

1. Go to cal.com/availability/[any one]
2. hover over the set to default
3. watch the text disappear

**Comment by Udit-takkar** [comment] 2023-05-10 11:24
duplicate of https://github.com/calcom/cal.com/issues/8628

**Closed by Udit-takkar** 2023-05-10 11:24 UTC
Labels: 🐛 bug
