### ISSUE TITLE
Wrong Time when scheduling

### ISSUE THREAD

**Issue by bhopmann** [calcom/cal.com#2714] opened 2022-05-10 07:08 UTC
### Issue Summary
When scheduling, a wrong time is shown (2h offset), although the correct timeslot is booked.

### Steps to Reproduce

1. Schedule an event
2. See last booking page

![Bildschirmfoto 2022-05-10 um 06 29 22](https://user-images.githubusercontent.com/2770597/167568701-36170bcf-ead7-4d63-8aca-c02bf03cf756.jpg)

![Bildschirmfoto 2022-05-10 um 06 29 31](https://user-images.githubusercontent.com/2770597/167568724-47dd8eb0-a658-416b-bdcf-a29748ae746c.jpg)

### Technical details

- Browser version: Firefox 100.0
- Node.js version: v14.19.1
- cal.com selfhosted ([v1.5.4](https://github.com/calcom/cal.com/commit/4099a477d16646d7c524fb8c249110f51c264c44))

**Comment by MuriloAmarals** [comment] 2022-05-10 12:46
Hey @CarinaWolli and @bhopmann I will start working on this issue.

**Comment by MuriloAmarals** [comment] 2022-05-10 12:53
I tried to reproduced the bug but in my application it works properly.

![Captura de tela de 2022-05-10 09-50-18](https://user-images.githubusercontent.com/87545137/167632956-b26e2a66-648c-4f62-b068-bcf313974ddd.png)

![Captura de tela de 2022-05-10 09-50-18](https://user-images.githubusercontent.com/87545137/167632975-f3c8c69e-b65b-474d-9fbc-15470eab3236.png)

**Comment by MuriloAmarals** [comment] 2022-05-10 12:56
I tried to reproduce the bug but in my application it works properly.

![Captura de tela de 2022-05-10 09-50-18](https://user-images.githubusercontent.com/87545137/167633384-4331d4de-87b3-4c61-97f6-521dca6826e7.png)

![Captura de tela de 2022-05-10 09-50-30](https://user-images.githubusercontent.com/87545137/167633439-85740259-3064-4fcc-9574-3b552b45bf59.png)

**Comment by manuelgu** [comment] 2022-05-10 17:56
I can reproduce the issue as described in the OP.

**Comment by Thiagomn1** [comment] 2022-05-17 14:42
Hello, any updates on this? I was able to reproduce the bug as described and would like to work on it

**Comment by Jaibles** [comment] 2022-05-18 18:59
@Thiagomn1 this was supposed to be resolved in https://github.com/calcom/cal.com/issues/2714. Can you confirm you're still experiencing this issue?

**Comment by Thiagomn1** [comment] 2022-05-18 19:46
@Jaibles I just gave it another test and seems to be working properly now

**Comment by Jaibles** [comment] 2022-05-18 19:47
Great! Closing as resolved.

**Closed by Jaibles** 2022-05-18 19:47 UTC
Labels: 🐛 bug
