### ISSUE TITLE
[CAL-2269] Weekly view offset

### ISSUE THREAD

**Issue by milospuac** [calcom/cal.com#10433] opened 2023-07-28 08:55 UTC
Created via Threads. See full discussion: [https://threads.com/34515697121](https://threads.com/34515697121)

![Screenshot 2023-07-28 at 10.50.34.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/7409b655-2c6d-4b4e-98d2-7f78923ad41f/cfd82f78-1067-42d5-8345-03d108409a0b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy83NDA5YjY1NS0yYzZkLTRiNGUtOThkMi03Zjc4OTIzYWQ0MWYvY2ZkODJmNzgtMTA2Ny00MmQ1LTgzNDUtMDNkMTA4NDA5YTBiIiwiaWF0IjoxNjkwNTM0NTIzLCJleHAiOjE2OTA2MjA5MjN9.v0kUYyePnRC4vVobBOCh84krJrFAF-Mz-re6-v_O2CQ)

![Screenshot 2023-07-28 at 10.43.33.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/d066784e-b095-403b-8858-64f6e81eeacc/f1fb42ad-6fb4-4342-8c9d-311ce7fa45c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9kMDY2Nzg0ZS1iMDk1LTQwM2ItODg1OC02NGY2ZTgxZWVhY2MvZjFmYjQyYWQtNmZiNC00MzQyLThjOWQtMzExY2U3ZmE0NWMyIiwiaWF0IjoxNjkwNTM0NTIzLCJleHAiOjE2OTA2MjA5MjN9.YT_VRNbg2kNpdSJTtUL5eseKAyzZnGyN7GdiWXSaeCA)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2269](https://linear.app/calcom/issue/CAL-2269/weekly-view-offset)</sub>

**Comment by prasadsawant7** [comment] 2023-07-30 11:01
Can you elaborate the issue please!

**Comment by greipfrut** [comment] 2023-08-01 14:29
> Can you elaborate the issue please!

I believe this is a duplicate of #10428 --the bookings appear on the wrong day when in Weekly View.

i.e. Monday-to-Friday bookings show up in the Weekly View under Tuesday-to-Saturday.

**Closed** 2023-08-01 14:30 UTC
Labels: 🐛 bug
