### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by asharabu** [calcom/cal.com#1583] opened 2022-01-21 08:55 UTC
Hi,
I have deployed calendo docker version as per the [link ](https://github.com/calendso/docker). I have also created user via prisma studio but while trying to login it is not getting success,
![image](https://user-images.githubusercontent.com/42669995/150496825-0f110c37-c6ee-4a2a-96f7-ffbc51839ff9.png)

I am also getting below error in the calendso container logs,

> prisma:query SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."plan", "public"."users"."brandColor" FROM "public"."users" WHERE "public"."users"."email" = $1 LIMIT $2 OFFSET $3
[next-auth][warn][jwt_auto_generated_signing_key]
https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
(node:198) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:333:9)
    at hkdf_extract (/app/node_modules/futoin-hkdf/hkdf.js:77:57)
    at hkdf (/app/node_modules/futoin-hkdf/hkdf.js:147:17)
    at hkdf (/app/node_modules/next-auth/dist/lib/jwt.js:130:32)
    at getDerivedSigningKey (/app/node_modules/next-auth/dist/lib/jwt.js:143:18)
    at Object.encode (/app/node_modules/next-auth/dist/lib/jwt.js:40:86)
    at Object.callback (/app/node_modules/next-auth/dist/server/routes/callback.js:318:37)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 38)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

>

**Comment by milospuac** [comment] 2022-01-25 06:01
Thanks for sending this! Our team will have a look at it.

**Comment by 7d916724** [comment] 2022-01-29 20:38
@asharabu - can you confirm that the `JWT_SECRET` environment variable is defined in the docker container? This error appears to match the github issue here - https://github.com/calendso/calendso/issues/856#issuecomment-935540636

**Comment by AshnaSabu123** [comment] 2022-02-01 06:57
I have the environment variable JWT_SECERT in the .env file, but not able to login.

**Comment by baileypumfleet** [comment] 2022-02-28 13:04
Closing this as we are unable to reproduce, and is likely an issue solely occurring with your environment

**Closed by baileypumfleet** 2022-02-28 13:04 UTC
Labels: 🐛 bug
