### ISSUE TITLE
[CAL-1574] Avatar not Loading after New Account Setup

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#8448] opened 2023-04-21 15:26 UTC
![CleanShot 2023-04-21 at 23.25.31@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/099cb25d-4963-4732-b55b-cbde91fb6299/44c65235-5019-4313-9b21-49b863218ebf)

This is a dumby account, but the avatar isn't loading after it's been set in settings (granted username has not been paid for)

![CleanShot 2023-04-21 at 23.26.30@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/9875c598-fc64-4c79-8696-38e863d3cc85/3b7d1bef-d81e-46da-a1c7-76344210906b)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1574](https://linear.app/calcom/issue/CAL-1574/avatar-not-loading-after-new-account-setup)</sub>

**Comment by vaibhav135** [comment] 2023-04-22 10:11
Hi, can I take this up.

**Comment by vaibhav135** [comment] 2023-04-22 12:29
@shirazdole  can I take this one.

**Comment by vaibhav135** [comment] 2023-04-22 12:32
@shirazdole I am not able to reproduce this problem. Can you please give more info.

**Comment by ExplorerAadi** [comment] 2023-04-25 22:14
Hey @shirazdole I dug into this issue and found the cause. It seems to be an issue of browser caching.
Everything is updating fine but because the image url stays the same, the browser caches it and hence does not update unless that component re-renders.

I am attaching a drive link with a video where I reproduced the issue:
https://drive.google.com/file/d/1Nu7u2lYYZqTZkqN90rwnqq77o8JV0bnr/view?usp=sharing

**Comment by ExplorerAadi** [comment] 2023-04-28 19:26
Hey @sean-brydon Could you please suggest a workaround for dealing with this caching of image issue? I have explained the issue in my comment and also attached a video.

The major problem seems to be components not re-rendering after image update and I cannot just do a force refresh after update because that will be a terrible user experience.

**Comment by Keyurkd** [comment] 2023-04-29 23:42
@shirazdole @sean-brydon Review & accept my PR.

**Comment by Keyurkd** [comment] 2023-04-30 16:07
Hi @shirazdole 
I raised the PR which resolves this issue.

**Comment by Vikram125609** [comment] 2023-05-02 07:19
Hello @shirazdole,
This issue is only with the Side Bar Right ?

**Comment by keithwillcode** [comment] 2023-07-14 14:34
Closing because PR was merged.

**Closed by keithwillcode** 2023-07-14 14:34 UTC
Labels: 🐛 bug, ✅ good first issue, 🙋🏻‍♂️help wanted, 🚧  wip / in the making, performance
