### ISSUE TITLE
[CAL-1547] UI: Long text event type descriptions are not truncating

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#8426] opened 2023-04-21 06:43 UTC
![CleanShot 2023-04-21 at 08.43.20@2x.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/dd3c9e7a-a3ae-4d79-a54c-bd40df5e3cf0/c1db208a-d32a-4ec6-9104-da696101a212)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1547](https://linear.app/calcom/issue/CAL-1547/ui-long-text-event-type-descriptions-are-not-truncating)</sub>

**Comment by vaibhav135** [comment] 2023-05-06 14:09
@Jaibles can you explain a bit more, because we already are getting scrolling for these kinds of things. 

https://user-images.githubusercontent.com/39329182/236628952-7e64d087-413c-4e2a-be86-c48c2c09597e.mov

**Comment by JeroenReumkens** [comment] 2023-05-08 12:13
Hey @vaibhav135 This issue was created for our new booker (soon!!). The issue is however also fixed recently in the new booker, so I'm gonna close this issue for that reason 😁

**Closed by JeroenReumkens** 2023-05-08 12:13 UTC
Labels: 🐛 bug

**Comment by vaibhav135** [comment] 2023-05-09 03:53
@JeroenReumkens thanks for the info. Btw is there any Jira board or something to get update on "todo", "inprogess" and "done".

**Comment by JeroenReumkens** [comment] 2023-05-15 07:32
> 

@vaibhav135  Unfortunately that board is only internal. But there are only a few issues left there!
