### ISSUE TITLE
[CAL-1612] Dark mode bugs availability

### ISSUE THREAD

**Issue by Udit-takkar** [calcom/cal.com#8628] opened 2023-05-02 19:48 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

1) set as default on hover 

<img width="1185" alt="Screenshot 2023-05-03 at 1 12 28 AM" src="https://user-images.githubusercontent.com/53316345/235768998-b4971a5d-98b0-40d9-b9de-ab9f26dbfec3.png">

2) delete icon on hover

<img width="353" alt="Screenshot 2023-05-03 at 1 12 52 AM" src="https://user-images.githubusercontent.com/53316345/235769101-1af9111d-7aea-4678-b7a0-12c3d1cc5382.png">

should be like this
<img width="503" alt="Screenshot 2023-05-03 at 1 18 13 AM" src="https://user-images.githubusercontent.com/53316345/235770164-fede18fa-34c3-42c6-a9d6-1ab14cea5fe4.png">

3) Delete icon on hover should be red

<img width="503" alt="Screenshot 2023-05-03 at 1 13 43 AM" src="https://user-images.githubusercontent.com/53316345/235769275-980ad6af-b1bb-46eb-b945-5dbc1e813069.png">

### Steps to Reproduce

1) go to http://localhost:3000/availability
2) Open any availability item

<sub>[CAL-1612](https://linear.app/calcom/issue/CAL-1612/dark-mode-bugs-availability)</sub>

**Comment by Udit-takkar** [comment] 2023-05-02 19:56
@MaheshB77

**Comment by Adithya2907** [comment] 2023-05-02 19:56
If available, can I work on this issue?

**Comment by MaheshB77** [comment] 2023-05-02 19:59
> @MaheshB77 you can work on this

Sure @Udit-takkar Please assign this to me, will fix this

**Comment by Udit-takkar** [comment] 2023-05-02 20:00
@Adithya2907 you can look for any other issue or just use app.cal.com and look for any responsive or dark mode ui bugs and create an issue for it

**Comment by Adithya2907** [comment] 2023-05-02 20:03
@Udit-takkar sure, I'll try looking to other issues to fix. Thank you!

**Comment by Udit-takkar** [comment] 2023-05-04 17:32
@skushagra9 no that's a different page. go to /availability and open any availability item

**Comment by skushagra9** [comment] 2023-05-04 17:50
@Udit-takkar see this
![image](https://user-images.githubusercontent.com/120712705/236287477-1be2f5b0-c7be-4ff8-ad84-8c0f8748d6ba.png)

**Comment by skushagra9** [comment] 2023-05-04 17:51
@Udit-takkar see this
![image](https://user-images.githubusercontent.com/120712705/236287708-546b77d7-f54e-4ecd-a0db-82d097de22fd.png)

**Comment by Ksh1t1j** [comment] 2023-05-08 00:17
Hi!! is this issue still open?

**Comment by Saga-sanga** [comment] 2023-05-09 16:19
@Udit-takkar for the second issue the colour seems to be that way for a disabled button. If there are multiple schedules, the delete button is active and works as intended. So my question is this, would it be better to have a different style for an inactive button or is the current one good enough?

**Comment by RayAsh37** [comment] 2023-05-10 11:30
So I tried running an instance locally and the "set to default" under /availabilty seems to have been fixed but is not visible in production.

https://github.com/calcom/cal.com/assets/70441807/57c6a8d4-a4bd-462b-9d69-11c0d1b9b95c

**Comment by Udit-takkar** [comment] 2023-05-10 11:30
@RayAsh37 ok someone must have merged the PR

**Closed** 2023-05-14 18:08 UTC
Labels: 🐛 bug, ✅ good first issue, 🙋🏻‍♂️help wanted
