### ISSUE TITLE
TypeError: getClassNames is not a function

### ISSUE THREAD

**Issue by wassimbj** [calcom/cal.com#6783] opened 2023-01-30 11:42 UTC
### Issue Summary
I'm just trying to contribute to this project, i followed the setup steps in the readme, everything works fine, created a user, logged in, but when i got redirected to the getting-started page i get an error

```bash
Server Error
TypeError: getClassNames is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
getStyleProps
file:///home/wassim/opensource/cal.com/node_modules/react-select/dist/index-5b950e59.cjs.dev.js (112:98)
SelectContainer
file:///home/wassim/opensource/cal.com/node_modules/react-select/dist/index-5b950e59.cjs.dev.js (749:40)
```
### Steps to Reproduce

1. Login
2. Get reditected to the `/getting-started` page
3. the error pops up

The issue is actually coming from the the `TimeZoneSelect` Component in here [#L84](https://github.com/calcom/cal.com/blob/6c23813192ee01d28d7cd7b2edaaec29b6fdd68e/apps/web/components/getting-started/steps-views/UserSettings.tsx#L84), cause when i wrap it in a comment everything works perfectly.
### Technical details

- Browser: Google Chrome, console.log is above
- Node.js version: v18.12.1
- Already mentioned above

**Comment by PeerRich** [comment] 2023-01-30 11:51
can you yarn clean and yarn again? looks like a dependency issue

**Comment by wassimbj** [comment] 2023-01-30 12:39
Just tried that, it didn't work. I will try to investigate more in this and let you know

**Comment by PeerRich** [comment] 2023-02-01 09:04
i cant reproduce this. seems to be a dependency issue

**Comment by wassimbj** [comment] 2023-02-01 09:46
I'm actually using node 18.x,  on WSL Ubuntu. I had some issues with ubuntu on wsl lateley, so i  just switched to Debian and installed node 19.x which is the latest and i will be trying again

**Comment by wassimbj** [comment] 2023-02-01 09:53
Try creating a new account, and then login. at first it redirected me to `/event-types` route, then I get redirected to `/getting-started` page and the error pops up. i created the account by adding it manually in the prisma studio by the way.

**Comment by PeerRich** [comment] 2023-02-01 10:20
wait but that means the original error doesnt show anymore?

**Comment by wassimbj** [comment] 2023-02-01 11:12
No no, just now started testing it in the new environment

**Comment by PeerRich** [comment] 2023-02-01 12:14
ok perfect. lemme close this, can you reopen the other issues you find in new tickets?

**Closed by PeerRich** 2023-02-01 12:14 UTC
Labels: 🐛 bug, 🤔 can't reproduce, Low priority, self-hosting

**Comment by wassimbj** [comment] 2023-02-01 12:18
Alright! I will

**Comment by wassimbj** [comment] 2023-02-01 14:25
Looks like it was actually a dependency issue, its working fine on the new environment, Debian 11 on WSL with node 18.x, i had to switch cause, the package.json only support between 16 and 18. everything works fine now
