### ISSUE TITLE
you cant scroll on mobile after opening a dialog or dropdown

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#2328] opened 2022-03-31 09:08 UTC
https://user-images.githubusercontent.com/8019099/161019695-1f97eea2-881a-49b1-b82c-eedf07c0526c.MOV

in order to scroll again, you need to change the focus. as long as the button that opened the dialog or dropdown has focus, you can't scroll

**Comment by miguelnietoa** [comment] 2022-04-05 15:31
I can confirm this behavior, I'm going to take a look at it to see if I can find a way to fix it.

**Comment by miguelnietoa** [comment] 2022-04-07 14:51
I still haven't found a way to solve this, can anyone come up with any ideas? 🤔

**Comment by Dueen** [comment] 2022-04-09 17:16
Taking a guess here: But, this might have to do with the use of [RemoveScroll](https://www.npmjs.com/package/react-remove-scroll) in [radix-ui's DialogOverlay](https://github.com/radix-ui/primitives/blob/main/packages/react/dialog/src/Dialog.tsx#L208) or the implementation in [Menu (used by the DropDown Primitive)](https://github.com/radix-ui/primitives/blob/main/packages/react/menu/src/Menu.tsx#L537). Happy to give this a shot and see if it's something that can be fixed without a PR to the library itself.

**Comment by PeerRich** [comment] 2022-04-09 17:54
that would be great @Dueen, thank you!

**Comment by Dueen** [comment] 2022-04-14 20:48
The issue is currently being worked on by Radix-UI radix-ui/primitives#1241

I'm assuming it's better to wait for them to close this issue and then bump the radix components

**Comment by Aarbel** [comment] 2022-07-25 14:03
Will radix be stable some day and perform mobile / touch device e2e tests ?

**Closed** 2022-12-12 19:31 UTC
