### ISSUE TITLE
[CAL-333] Meeting link as a dynamic text variable in workflows

### ISSUE THREAD

**Issue by CarinaWolli** [calcom/cal.com#5421] opened 2022-11-08 15:40 UTC
Currently {LOCATION} only shows the meeting type like 'Zoom Video'. We want to show the meeting link instead

> From [SyncLinear.com](https://synclinear.com)

**Comment by JohanForngren** [comment] 2022-11-08 18:56
I think it would be nice to have both {LOCATION} and something like {LINK} or {URL}. One use case of the former would be to  include the location in the email subject. More options is better 😃

**Comment by CarinaWolli** [comment] 2022-11-09 07:19
Yes makes sense, I will add a new variable 👍

**Comment by JohanForngren** [comment] 2022-11-28 18:39
Duplicate of #4733?

**Comment by CarinaWolli** [comment] 2022-11-29 09:44
@JohanForngren Thank you it is a duplicate indeed. I am currently working on it, PR is coming soon

**Closed** 2022-12-18 02:04 UTC
Labels: linear
