### ISSUE TITLE
[CAL-1175] Not possible to select a custom duration on public event page

### ISSUE THREAD

**Issue by Timmer2021** [calcom/cal.com#7471] opened 2023-03-02 16:40 UTC
I want to revisit this bug as it doesn't seem to be resolved and the issue was closed.. 

https://github.com/calcom/cal.com/issues/7090

Please see my comments at the bottom of the page regarding issue 7090.

Thanks.

<sub>[CAL-1175](https://linear.app/calcom/issue/CAL-1175/not-possible-to-select-a-custom-duration-on-public-event-page)</sub>

**Comment by Udit-takkar** [comment] 2023-03-03 18:28
@Timmer2021 not able to reproduce the bugs that you mentioned. you can check https://cal.com/udit/7471

you can see multiple duration and attendee location

<img width="220" alt="Screenshot 2023-03-03 at 11 57 50 PM" src="https://user-images.githubusercontent.com/53316345/222799018-e7742084-aba5-461f-9be5-381e195c429c.png">

**Comment by keithwillcode** [comment] 2023-06-22 13:10
Closing since we can't reproduce this.

**Closed by keithwillcode** 2023-06-22 13:10 UTC
Labels: 🐛 bug, 🚧  wip / in the making, 🤔 can't reproduce, 3 points
