### ISSUE TITLE
Required fields are empty

### ISSUE THREAD

**Issue by peseotni** [calcom/cal.com#2902] opened 2022-05-27 06:46 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Added required question fields, but clients can just fill out their name and email and submit without filling out those fields.

### Steps to Reproduce

1. fresh install and database
2. created event type and added additional inputs and made them required.
3. clients fill out the form and can submit it without filling out the required additional inputs.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The client shouldn't be able to submit the form without filling out all the required inputs.

### Technical details

- Browser version 101.0.4951.67
- Node.js 14.19.3
- even though I added 'agree' to the .env file in the NEXT_PUBLIC_LICENSE_CONSENT, it still asks me to insert it.

**Comment by hariombalhara** [comment] 2022-05-30 05:28
Duplicate of https://github.com/calcom/cal.com/issues/2660

**Closed by hariombalhara** 2022-05-30 05:28 UTC
