### ISSUE TITLE
Profile language cannot be updated

### ISSUE THREAD

**Issue by rafael-c-alexandre** [calcom/cal.com#7994] opened 2023-03-28 22:58 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

It appears that profile's language cannot be updated. I could update it before but not anymore.

### Steps to Reproduce

1. Go to "Settings"
2. In the "My account" section, choose "General"
3. Change the language setting and click "Update"
4. Refresh page and check that the language was not updated

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I expected the language to be updated.

### Technical details

- I originally verified this behavior on Firefox but could confirm it also happens on Safari and Chrome.
- Note that all other settings appear to be working fine when updated.

**Comment by CarinaWolli** [comment] 2023-03-29 05:23
here is PR to fix that #7981

Closing because it's a duplicate of https://github.com/calcom/cal.com/issues/7976

**Closed by CarinaWolli** 2023-03-29 05:23 UTC
Labels: 🐛 bug
