### ISSUE TITLE
Navigating screens is delayed by 1-2 seconds

### ISSUE THREAD

**Issue by JoeyFenny** [calcom/cal.com#2541] opened 2022-04-18 16:37 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1) Deploy to Heroku (Hobby Dyno - $7/month - no sleeping for inactivity)
2) Create user, event type, etc then pretend to book a call on the calendar you've just created
- Click on an event type
- Click on a timeslot availability

Notice that moving between pages event type -> availability and availability -> confirm booking page has a 1-2 second delay between the time you click the button and the time you are directed to the next page. There is no acknowledgment during the waiting period. There is no loading indicator. The user sits there in silence for a second or two wondering why nothing is happening, then finally they get redirected.

**Comment by gabriellferreira-dev** [comment] 2022-05-19 13:20
I will check this situation

**Comment by PeerRich** [comment] 2022-06-03 19:11
I can't reproduce this

**Comment by zomars** [comment] 2022-07-01 16:50
Closing until proper demo/reproduction is provided since we can't replicate.

**Closed by zomars** 2022-07-01 16:50 UTC
Labels: 🐛 bug
