### ISSUE TITLE
Prevent reschedule / cancel when too closed from the event

### ISSUE THREAD

**Issue by bst1n** [calcom/cal.com#15158] opened 2024-05-22 14:51 UTC
### Is your proposal related to a problem?

Prevent reschedule / cancel when too closed from the event

### Describe the solution you'd like

A custom limit of time from events settings and prevent to reschedule and/or cancel

### Describe alternatives you've considered

No alternative.

### Additional context

I want to count an appointment in my database as completed if the person hasn't cancelled far enough in advance, and therefore prevent them from cancelling and rescheduling.

### Requirement/Document

No.

**Comment by anikdhabal** [comment] 2024-05-23 02:59
similar to this #14742

**Comment by ciaranha** [comment] 2024-07-16 14:59
Duplicate of https://github.com/calcom/cal.com/issues/15647

**Closed by ciaranha** 2024-07-16 14:59 UTC
Labels: ✨ feature, 🎨 needs design, linear, Low priority, 2 points, bookings
