### ISSUE TITLE
[CAL-398] New booking layout - Weekly view

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#5590] opened 2022-11-19 10:44 UTC
We're adding a new layout option for the public booking page, a weekly view.

[2. Weekly - Cal - New Features (Figma)](https://www.figma.com/file/UajFu4M1APhn2AywAEJkJr/Cal---New-Features?node-id=451%3A65668&t=pgAbFenXbJx7vDAK-1)

> From [SyncLinear.com](https://synclinear.com) | [CAL-398](https://linear.app/calcom/issue/CAL-398/new-booking-layout-weekly-view)

**Comment by xeruf** [comment] 2023-03-06 13:03
Duplicate of https://github.com/calcom/cal.com/issues/4006 ?

**Closed** 2023-06-16 09:41 UTC
Labels: ✨ feature, Medium priority
