### ISSUE TITLE
Showing blank notification box and negative numbers for recurring events

### ISSUE THREAD

**Issue by ericrommel** [calcom/cal.com#9604] opened 2023-06-17 19:58 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When there are 5 or less than that, it's showing 0 or the difference between 5 and the recurring numbers. Also, an empty/blank notification box is shown.

### Steps to Reproduce

1. Set a recurring event type with 3 events recurring (issue is between 5 and 1)
2. Copy the event link and open it in another tab
3. Set a day and time
4. Check the list of events. You can see a "-2" together with "+ more" 
5. Mouse over that list to see the blank box notification 

Tested on Vercel preview (https://cal-5luk9i0hk-cal.vercel.app/event-types)

### Technical details

- Tested on Chrome v114.0.5735.134
- Windows 11 PRO

![image](https://github.com/calcom/cal.com/assets/10250819/190d82b0-eb8b-43a6-98ef-2c008199ef46)

![image](https://github.com/calcom/cal.com/assets/10250819/09f3c65f-98c1-4eb8-935d-fd68350451b3)

![image](https://github.com/calcom/cal.com/assets/10250819/a78b2304-f3b1-4b5d-99df-b36705cf58dc)

![image](https://github.com/calcom/cal.com/assets/10250819/a0b74042-4e34-4b00-ad6f-a1ed8f1f0916)

![image](https://github.com/calcom/cal.com/assets/10250819/c7352cd2-b450-4758-a428-1972a4297cfd)

**Comment by kemilbeltre** [comment] 2023-06-18 11:04
@ericrommel  could you assign this to me? Thanks

**Comment by kemilbeltre** [comment] 2023-06-18 12:44
Hey, @ericrommel checking the code above, it seems to be not possible to reproduce this error:
```
{!rescheduleUid && eventType?.recurringEvent?.freq && recurringStrings.length > 5 && (
                        <div className="flex">
                          <Tooltip
                            content={recurringStrings.slice(5).map((timeFormatted, key) => (
                              <p key={key}>{timeFormatted}</p>
                            ))}>
                            <p className=" text-sm">
                              + {t("plus_more", { count: recurringStrings.length })}
                            </p>
                          </Tooltip>
                        </div>
                      )}
```

Do you think I'm missing something?

**Comment by kemilbeltre** [comment] 2023-06-18 12:49
In order to avoid negative length we can use the `+`  to convert a string representation of a number to a number.

**Closed** 2023-06-25 15:09 UTC
Labels: 🐛 bug, Low priority
