### ISSUE TITLE
My-Account/Calendar is stuck in loading

### ISSUE THREAD

**Issue by jarich123** [calcom/cal.com#4538] opened 2022-09-16 18:34 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. (for example) Went to ... https://app.cal.com/settings/my-account/
2. Clicked on... Calendars
3. ... It is stuck on the loading screen

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

**Comment by PeerRich** [comment] 2022-09-19 01:09
is this still happening? can you record a video? I cant reproduce this

**Comment by jarich123** [comment] 2022-09-19 14:52
https://www.loom.com/share/8a3601b799b946e29d6330a1dd2faf3b

Yep! Here

**Comment by PeerRich** [comment] 2022-09-28 20:52
closing unless @jarich123 reports its not working still

**Closed by PeerRich** 2022-09-28 20:52 UTC
Labels: 🐛 bug

**Comment by jarich123** [comment] 2022-10-11 08:13
There we go! Works now.

Thanks!
