### ISSUE TITLE
[CAL-3476] Rescheduled events are not updated on (outlook) calendars

### ISSUE THREAD

**Issue by jkdowdle** [calcom/cal.com#14558] opened 2024-04-12 20:14 UTC
### Issue Summary

Rescheduled events are not being updated on the calendar.

After a user schedules an appointment with an internal employee through the hosted [cal.com](http://cal.com) ui the employee gets an email for the meeting invite and it shows up on the calendar (outlook in this case). This is perfect

However, if the user then goes back to the hosted [cal.com](http://cal.com) ui and reschedules the appointment then there is no email about the meeting being updated and the calendar still shows the original times.

I would expect that the calendar invite would reflect the new time based on when the user rescheduled and likely get an email saying that the meeting changed.

**Edit:** As mentioned above, this was tested using outlook calendar integration - but I would suspect that other calendars would have the same issue.

Our webhooks listen for the rescheduled event and updated some internal data, so that seems to be working just fine.

### Steps to Reproduce

1. Get an original booking with someone.
   * Note that an email was received about the meeting and is reflected on the calendar
2. Reschedule the booking to be a different time
   * Note that no new email came through and the calendar reflects the original times

Expected behavior: calendar stays in sync with changes as the meeting is rescheduled. Indeed, this is what the rescheduled ui messaging says in the [cal.com](http://cal.com) hosted ui

> We sent an email with a calendar invitation with the details to everyone.

*Edit*

A related and similar issue with canceling.

1. Cancel an original booking through hosted [cal.com](http://cal.com) ui
   * Note that no new email comes through nor does the calendar update

### Actual Results

* No email or calendar change to reflect the new time

### Expected Results

* Calendar stays in sync and users get an alert through email that the event changed

### Technical details

* using hosted [cal.com](http://cal.com) ui to schedule meetings
* using webhooks to update the rescheduled times on internal data (seems to be working fine)

### Evidence

| Step 1: original booking | Step 2: Reschedule | Calendar Invite still has original time |
| -- | -- | -- |
| ![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/48c79606-7673-4eb6-9ee8-68a161123624/bb24d1bd-12d8-4bff-9dcb-e66caece72f6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80OGM3OTYwNi03NjczLTRlYjYtOWVlOC02OGExNjExMjM2MjQvYmIyNGQxYmQtMTJkOC00YmZmLTlkY2ItZTY2Y2FlY2U3MmY2IiwiaWF0IjoxNzEzMjcwNzMyLCJleHAiOjE3MTMzNTcxMzJ9.AXyguTZQ2HWFQYmyqmrJG8SCVpw1fiLJ4tNSJ2SK9Rs) | ![image (2)](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/89d6fe75-dd69-4522-b9f0-fea1f6e979b3/0395bf3f-85c7-4e91-b82f-71405cfb15fc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy84OWQ2ZmU3NS1kZDY5LTQ1MjItYjlmMC1mZWExZjZlOTc5YjMvMDM5NWJmM2YtODVjNy00ZTkxLWI4MmYtNzE0MDVjZmIxNWZjIiwiaWF0IjoxNzEzMjcwNzMyLCJleHAiOjE3MTMzNTcxMzJ9.sWtw88bQdWDsc3S0Q3GLHrvOf0AaL3cD9Yl7q4ti0HQ) |  |

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3476](https://linear.app/calcom/issue/CAL-3476/rescheduled-events-are-not-updated-on-outlook-calendars)</sub>

**Comment by jkdowdle** [comment] 2024-04-12 20:25
I just tested canceling that appointment, the calendar invite has not updated nor is there an email alert about the change

**Comment by jkdowdle** [comment] 2024-04-15 15:52
I wanted to confirm that the hosts ui on the up coming bookings view https://app.cal.com/bookings/upcoming updated, and saw that that is working as expected

**Comment by Amit91848** [comment] 2024-04-24 06:52
Couldn't reproduce it, received rescheduled email and the booking was updated in outlook calendar after rescheduling.


https://github.com/calcom/cal.com/assets/74371312/9ea15d2a-7a89-4e08-9acd-73b89727c8b3

**Comment by hariombalhara** [comment] 2024-04-24 10:39
I tested it locally as well. It works fine in rescheduling scenario. I feel something wrong in the hosted setup of yours. Do you see something weird in your logs?

**Comment by hariombalhara** [comment] 2024-04-24 10:53
Also, could it be that the original booking was on a different calendar? and then you switched calendar before rescheduling. In that case it could happen.

**Comment by jkdowdle** [comment] 2024-04-25 18:03
@hariombalhara 

> I tested it locally as well. It works fine in rescheduling scenario. I feel something wrong in the hosted setup of yours. Do you see something weird in your logs?

We use the hosted cal.com instance - nothing is self hosted, which is where this was reproduced. or are you suggesting we might have some missing config / options for on our host accounts? For what its worth, it was first reported by our production Host who deals with customers and then I was able to reproduce it 

>Also, could it be that the original booking was on a different calendar? and then you switched calendar before rescheduling. In that case it could happen.

I've only ever setup one calendar, I could double check with our host, but I can reproduce it every time I try - never touching any calendar config and within moments (a minute or so) of the booking / rescheduling events happening. I could try giving some space between them though?

**Comment by jkdowdle** [comment] 2024-04-25 18:11
@joeauyeung 

> @jkdowdle can you confirm if this is happening in a round robin event?

I will try to double check here soon, but this is the params we use on the event type. we create an event type per appointment we want scheduled to power our scheduling flow through cal.com and we do set `schedulingType: 'ROUND_ROBIN'`

```
const { data: result } = await this.client.post<EventTypeCreateResponse>(
      '/event-types',
      {
        length: 45,
        afterEventBuffer: 15,
        metadata: {},
        title,
        slug,
        hidden: true,
        teamId,
        schedulingType: 'ROUND_ROBIN',
        hosts: [
          {
            userId: hostUserId,
            isFixed: true,
          },
        ],
        locations: [
          {
            type: 'conferencing',
          },
        ],
      },
    );
```
```

**Comment by jkdowdle** [comment] 2024-04-25 18:18
@Amit91848 

thank you for looking

**Comment by jkdowdle** [comment] 2024-04-25 18:23
@hariombalhara are you saying that round robin is meant to behave this way? Seems like it is a bug to me, especially since through the calendar integration the host has no way of knowing the event was moved or canceled - even if by some priority reasons it ended up being sent to some other host?

**Comment by jkdowdle** [comment] 2024-04-25 18:40
sounds good - thank you

**Comment by swain** [comment] 2024-05-06 15:23
Just checking back in -- any update on this issue?

**Comment by joeauyeung** [comment] 2024-05-09 16:52
@swain is this still happening? I could reproduce this bug before but now I can't. When I reschedule a round robin event the Outlook event gets updated to the new organizer calendar and the emails are being sent to the old and new organizer. 

If this is still happening can you email me at joe@cal.com with your username so I dig into your event type config some more.

**Comment by joeauyeung** [comment] 2024-05-09 19:46
@jkdowdle can you email me at joe@cal.com with your username so I can dig into this some more?

**Comment by jkdowdle** [comment] 2024-05-09 21:01
@joeauyeung sent, thank you!

**Comment by joeauyeung** [comment] 2024-05-14 20:03
Closing as it was discovered that it was a broken calendar integration that was causing the issue. Created a new issue with more details. 

Thanks again for the details @jkdowdle 

https://github.com/calcom/cal.com/issues/15034

**Closed by joeauyeung** 2024-05-14 20:03 UTC
Labels: 🐛 bug, High priority, bookings, emails, calendar-apps, consumer
