### ISSUE TITLE
Invalid `callbackUrl` after sign up

### ISSUE THREAD

**Issue by thecmdrunner** [calcom/cal.com#11258] opened 2023-09-09 11:17 UTC
### Issue Summary

The callbackUrl for website signup is improperly parsed with a single slash after "https:" resulting in an invalid URL format and a 404.

![image](https://github.com/calcom/cal.com/assets/38887390/fc7ab407-f979-4591-9efd-618d7dba447f)
![image](https://github.com/calcom/cal.com/assets/38887390/1e75f12a-b88b-46c1-be8f-196982e2c82f)

### Steps to Reproduce

1. Click on "I dont have an account" on the signin page.
2. Enter information for signup.
3. Observe the generated `callbackUrl` (in the screenshots above)

### Actual Results

The `callbackUrl` is parsed as "https:/app.cal.com" with a single slash after "https:" which is an invalid URL.

### Expected Results

The callbackUrl should be parsed as "https://app.cal.com", which is the correct Dashboard URL.

### Technical details

- Browser version [Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)](https://brave.com/latest/)

- Screen recording: 

https://github.com/calcom/cal.com/assets/38887390/72aeb274-b629-418f-a10d-a90474f121fc

### Evidence

- How was this tested?

I just signed up for a business and noticed that it parsed the url wrong.

**Comment by rishuraj1** [comment] 2023-09-09 11:33
Hey, I really wanna help you with this, can you please assign me to this issue. Thanks : )

**Comment by janvi01** [comment] 2023-09-09 15:03
Hey, I would like to work on this.

**Comment by keshavjha018** [comment] 2023-09-09 15:03
Hey @thecmdrunner ,
In my local machine, after I enter information for signup & click on "Sign Up", It redirects me to URL: "http://app.cal.local:3000/auth/login" & there seems no issue.

Will you please throw some more light on your issue.

<img width="608" alt="image" src="https://github.com/calcom/cal.com/assets/78548130/51963867-0b85-40a5-92c1-da406be75cb9">

**Comment by keshavjha018** [comment] 2023-09-09 15:12
Also, this issue is a duplicate of [https://github.com/calcom/cal.com/issues/11218](https://github.com/calcom/cal.com/issues/11218)

**Comment by JunedKhan101** [comment] 2023-09-09 15:13
Yeah, I tried this too it seems to be working fine.

I think the issue is on signup of cal.com which might be a different app than app.cal.com (not sure as I'm not that familiar with cal yet)

**Comment by thecmdrunner** [comment] 2023-09-10 05:34
@keshavjha018 yes this is a duplicate of #11218! Sorry for not noticing, you can close this issue

**Closed** 2023-09-12 20:58 UTC
Labels: 🐛 bug

**Comment by emrysal** [comment] 2023-09-12 21:44
Hi @thecmdrunner this is now fixed (if you could confirm that'd be appreciated, but not needed) - thank you for reporting 💯
