### ISSUE TITLE
Bug: Booking Buttons doesn't display text

### ISSUE THREAD

**Issue by g4rry420** [calcom/cal.com#2758] opened 2022-05-14 19:08 UTC
### Issue Summary
After booking is confirmed, when I clicked on `Back to bookings` link and navigated to `/bookings` then the button doesn't display the text.

A summary of the issue. This needs to be a clear detailed-rich summary.
This bug is discussed over here: https://calendso.slack.com/archives/C01NXDSRY9W/p1652320905257769

### Steps to Reproduce

1. Confirm a booking with any user and Wait for `This meeting is Scheduled` display
2. Clicked on `Back to bookings` link and you will be navigated to `/bookings` page.
3. See the buttons in this page doesn't display text.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
The buttons should display text.

### Technical details

- Browser version, screen recording, console logs, network requests: Any
- Node.js version: Any
- Anything else that you think could be an issue.

![Screenshot 2022-05-07 122304](https://user-images.githubusercontent.com/61521805/168445230-183c138b-85d0-4e40-875e-4b27221aae38.png)

**Comment by MuriloAmarals** [comment] 2022-05-16 11:10
Hey @g4rry420 , I'm already trying to reproduce this problem.

**Comment by MuriloAmarals** [comment] 2022-05-16 11:14
In my application the buttons have display text.

![Captura de tela de 2022-05-16 08-12-39](https://user-images.githubusercontent.com/87545137/168580822-7281fb61-1159-4961-aef9-e9eebf4fb3b5.png)

**Comment by Toledodev** [comment] 2022-05-16 15:59
![Screenshot from 2022-05-16 12-57-37](https://user-images.githubusercontent.com/87545086/168634802-7fbd3651-ed9d-47e8-9b65-f82dbad4e9fb.png)
Please look at the Brand color

**Comment by Toledodev** [comment] 2022-05-16 15:59
Could be inverted

**Comment by Azhariel** [comment] 2022-05-18 21:43
The steps I did to reproduce consistently are:
1. Accept upcoming booking
2. Click Reschedule -> edit booking
3. Make any changes and confirm reschedule
4. On "this meeting is scheduled" page, click the last link, "back to bookings"
5. Button text won't display

> Could be inverted

I agree, will look into this. Also, refreshing the /bookings page goes back to expected behaviour.

**Comment by Mitchell-Moore** [comment] 2022-05-18 23:31
I think it is something to do with tailwind setting dark mode on bookings page then when you go "back to bookings" the document class is still set to dark.

![Screen Shot 2022-05-18 at 8 08 08 PM](https://user-images.githubusercontent.com/47459168/169171871-22840b72-8af8-4137-b741-4419fc00d20b.png)

**Comment by Azhariel** [comment] 2022-05-18 23:44
Might be related to this that pops after clicking Reschedule:
`index.js?874c:9 You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

I've recorded a video with the fastest way to reproduce the bug: simply click "back" after going to the Reschedule page.
https://www.loom.com/share/105113b860dd4fa2abd48b4ec3577586

Currently looking into what causes @emotion/react to reload after it's already loaded.

**Comment by Azhariel** [comment] 2022-05-19 22:59
I still haven't made much progress at adressing the root cause of the issue, but have found a way to brute force a fix.
At `apps\web\components\BookingsShell.tsx`, add line 31:
![image](https://user-images.githubusercontent.com/9439404/169416752-14718797-9e06-454d-939e-8b347e7f379b.png)
This doesn't seem to break anything right now, but WILL break later implementations of themes.

At the time, it seems the app isn't supporting dark mode at the dashboard level? So there are no checks as there are on the public pages, but tailwind's dark props are carrying over. I reckon implementing dark mode/themes everywhere should fix it, but until then, I'm not sure where to go from here. 

Also should be noted that if it's not adressed by refreshing the page or the brute force fix, this bug carries over to other pages such as Apps, making the "Add" buttons there appear invisible (white on white).

**Comment by Azhariel** [comment] 2022-05-25 14:44
I think I found the root of the issue, but I can think of some possible solutions and would like some guidance or discussion on which to pursue.

## The problem
This is an unintended side effect of [apps\web\lib\hooks\useTheme.tsx](https://github.com/calcom/cal.com/blob/07aa2e88a1d9dea6f2c8618c1e8012c72fe8152f/apps/web/lib/hooks/useTheme.tsx)  `applyThemeAndAddListener` function. This function is called when using the component `<Theme />`, which is only mounted on select public pages (e.g. [AvailabilityPage.tsx](https://github.com/calcom/cal.com/blob/07aa2e88a1d9dea6f2c8618c1e8012c72fe8152f/apps/web/components/booking/pages/AvailabilityPage.tsx#L169). It either gets a theme as string (light | dark) or null. If null - which is what always happens - it checks for the user's MediaQuery [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), which is set at browser/system level and doesn't usually change (so mediaQueryList.onchange doesn't trigger when browsing through pages). 

So, **TL;DR:** going to public pages that mount `<Theme />` can trigger dark mode being set based on MediaQuery, which is not unset: first, because prefers-color-scheme doesn't change, and second because `<Theme />` isn't even mounted on private pages. 

## Solutions
### Mounting `<Theme />` on _app
This would make using Theme more consistent across the board, but more coding is needed to make it work.

### useTheme check for URL changes
Another solution is modifying useTheme to check for URL changes (e.g. using `Router.events.on("routeChangeStart", handleRouteChange);`, where handleRouteChange could check the outgoing url) to see if it should force load light theme or do its usual logic/check;

### useTheme dismount
Yet another approach is reverting to light theme when the `<Theme />` component dismounts (return function), setting it to light theme.

**Comment by joeauyeung** [comment] 2022-07-13 16:39
Not able to reproduce so closing issue for now.

**Closed by joeauyeung** 2022-07-13 16:39 UTC
Labels: 🐛 bug
