### ISSUE TITLE
User Profile Image Uploader UI issues

### ISSUE THREAD

**Issue by fancymithun** [calcom/cal.com#10316] opened 2023-07-22 11:56 UTC
### Issue Summary

Cancel and Save buttons are out in upload avatar profile section. Need to update this with margin bottom 16px.

### Steps to Reproduce

1. Go to settings
2. My account
3. Profile
4. Click Change Avatar

### Actual Results

- Close and Save buttons are touching border with no margin in bottom

### Expected Results

- Need to have margin bottom to look good feel of UI

### Technical details

- Chrome Browser(https://birdeatsbug.com/).](https://cal.com/settings/my-account/profile)

### Evidence

- Please have a look at screenshot

![cal-image-uploader](https://github.com/calcom/cal.com/assets/68776547/72517780-8113-4f68-9d25-ea4585b75717)

**Comment by fancymithun** [comment] 2023-07-22 11:56
I will work on this issue.. I am new contributor to cal.com

**Comment by puru-khedre** [comment] 2023-07-23 03:31
@fancymithun You have created a PR to merge the code into main branch your own forked Repository. Please open a PR to merge code into cal.com's main branch.

**Comment by Udit-takkar** [comment] 2023-07-23 08:17
duplicate of https://github.com/calcom/cal.com/issues/10309

**Comment by Noezor** [comment] 2023-09-16 10:17
@Udit-takkar would you consider re-opening this issue? 
![image](https://github.com/calcom/cal.com/assets/8218350/034d2219-25fa-4cdf-acb1-663a803a1b3a)
The Upload/Save button component is out of the bigger component on small devices when there is an image.

**Comment by Udit-takkar** [comment] 2023-09-16 20:52
@fancymithun the buttons are inside the modal 

<img width="748" alt="Screenshot 2023-09-17 at 2 21 40 AM" src="https://github.com/calcom/cal.com/assets/53316345/1ed07a66-73e9-48bb-8f30-4ece8adc8383">

**Comment by Noezor** [comment] 2023-09-16 21:00
I promise they are not. Look at the image. You can also try to resize your
browser. The image you are showing does not replicate my case, there is way
too much space at the bottom.

**Comment by PeerRich** [comment] 2023-09-18 19:37
maige don't use the "needs design" label

**Closed** 2023-10-06 12:34 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, Low priority, ui
