### ISSUE TITLE
bug: i18n switches between multiple languages

### ISSUE THREAD

**Issue by juliusmarminge** [calcom/cal.com#7088] opened 2023-02-14 10:20 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I noticed today when browsing through my settings that the i18n kept on changing, below you can see i navigate around some tabs and the language switches between Swedish, Norwegian and English.

https://user-images.githubusercontent.com/51714798/218705766-001c2673-56f8-4f18-89a8-38fe27f15a26.mp4

### Steps to Reproduce

Not sure what the best repro is here since it's likely dependent on some settings I have? My system is in English so not sure why it even wants anything else?

I generally just browse around `app.cal.com` and see the sidebar titles change which is kinda annoying tbf. Also no clue where Norwegian comes from?

### Technical details

```
Browser: Arc 0.89.0, Safari 16.3
OS: MacOS Ventura 13.2
```

**Comment by juliusmarminge** [comment] 2023-02-14 10:25
Now on my booking page its showing russian/ukraine or something...

https://cal.com/juliusm/60min?date=2023-02-14

<img width="1058" alt="CleanShot 2023-02-14 at 11 25 01@2x" src="https://user-images.githubusercontent.com/51714798/218708496-b213a0d5-4cad-4388-8984-9db43edf2d9c.png">

**Comment by juliusmarminge** [comment] 2023-02-14 10:29
Okay this is annoying... random languages keeps on getting selected for some reason - can't get rid of the Russian now

<img width="1242" alt="CleanShot 2023-02-14 at 11 28 23@2x" src="https://user-images.githubusercontent.com/51714798/218709271-ab12e766-fd7f-4ded-b677-32ff3881bb05.png">

**Comment by PeerRich** [comment] 2023-02-14 10:36
oh dear that sucks. lemme ping @AaronPresley to focus on it. he is our inhouse i18n expert now

**Comment by PeerRich** [comment] 2023-02-14 10:38
cant reproduce this on my end. very odd

**Comment by PeerRich** [comment] 2023-02-14 10:38
btw english is the first entry here: 
![CleanShot 2023-02-14 at 11 38 47@2x](https://user-images.githubusercontent.com/8019099/218711644-26375c97-e973-40a5-be1e-b654116a0d66.jpg)

**Comment by juliusmarminge** [comment] 2023-02-14 10:40
> btw english is the first entry here: ![CleanShot 2023-02-14 at 11 38 47@2x](https://user-images.githubusercontent.com/8019099/218711644-26375c97-e973-40a5-be1e-b654116a0d66.jpg)

updated the above where i change the language but the russian just pops back after refreshing the page https://github.com/calcom/cal.com/issues/7088#issuecomment-1429491554

**Comment by juliusmarminge** [comment] 2023-02-14 10:41
(you can see its english and then flashes to russian immediately)

checked my local storage and cookies and whatnot but can't see anything that tells what language it should use?

**Comment by juliusmarminge** [comment] 2023-02-14 10:46
idk this is very strange and seems to happen on random pages.

no longer able to reproduce the norwegian/swedish/english bug since i touched the language toggle though it seems like... 🤔 now it's just the russian thing that pops up on some tabs


https://user-images.githubusercontent.com/51714798/218713325-de272a57-1cd7-44c1-8856-0af8f454c0b9.mp4

**Comment by PeerRich** [comment] 2023-02-14 12:51
https://github.com/calcom/cal.com/pull/6823 this could be related

**Comment by PeerRich** [comment] 2023-02-14 12:52
maybe it returns the cache of someone else

**Comment by krzyzanowskim** [comment] 2023-02-14 13:06
I can confirm on my side. Reproducible in Safari and Firefox on my end.

https://user-images.githubusercontent.com/758033/218747266-6322fd2c-a061-4324-bb01-a13bd98d32bf.mov

**Comment by PeerRich** [comment] 2023-02-14 13:25
well today is international language learning day it seems, time to brush up my danish skills

**Comment by zomars** [comment] 2023-02-14 17:38
Fixed in latest release 🙏

**Closed by zomars** 2023-02-14 17:39 UTC
Labels: 🐛 bug, 🙋🏻‍♂️help wanted, 👩‍🔬 needs investigation, 🤔 can't reproduce, Urgent, 📉 regressing

**Comment by PeerRich** [comment] 2023-02-15 18:43
thank you so much @juliusmarminge for reporting
