### ISSUE TITLE
CalDAV availability checking is slow (30+ seconds)

### ISSUE THREAD

**Issue by kuba-orlik** [calcom/cal.com#479] opened 2021-08-17 10:43 UTC
### Issue Summary

I've set up CalDAV integration with a few calendars from my Nextcloud server. Now, when scheduling a call, loading availability for a given day takes very long (up to 30s):

![image](https://user-images.githubusercontent.com/2697916/129711941-6ace8850-b945-4c43-bf13-0edfc8f88e2d.png)

When using the "troubleshoot availability" option for a given date, the view contains event from 2 years ago:

![image](https://user-images.githubusercontent.com/2697916/129712111-18d8f073-594d-4fd5-ba7a-178a3157e6f8.png)

This leads me to suspect that calendso downloads and checks all the events in the calendar, not only those affecting a given day, making it quite slow.

### Steps to Reproduce
1. Connect CalDAV calendars with a lot of events
2. Open the call scheduling form
3. Click on a date
4. wait...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
* Browser version: Firefox 91 (dev edition)
* Node.js version: 14

**Comment by kuba-orlik** [comment] 2021-08-17 10:44
(Loading the calendars list is also slow, takes 5-10 seconds)

**Comment by barrydegraaff** [comment] 2021-08-17 11:44
I can confirm this issue.

On the intial set-up it seemed to be fast, but after rebooting calendso there is a 30-60 second delay. I check the logs on the CalDAV server (Zimbra) and I do not see a request incoming for 30 or so seconds, so there is a significant delay before calendo even asks for calendar data.

**Comment by PeerRich** [comment] 2021-08-17 11:46
hey you three. thank you for reporting. We'll look into this asap and see how we can get loading time down drastically

**Comment by kuba-orlik** [comment] 2021-08-17 13:46
Currently time-range filters are not set up:

https://github.com/calendso/calendso/blob/9eb12703e333ff293ea58fdc9399c9a86cca6c37/lib/integrations/CalDav/CalDavCalendarAdapter.ts#L248

`tsdav` supports filtering by date range, but it was broken, as it didn't accept dates in the ISO 8601 format. I've created a PR to `tsdav` that addresses that: 

https://github.com/llldar/tsDAV/pull/4

Once it's merged, the fetched events can be filtered with 

```js
const objects = await client.fetchCalendarObjects({
  calendar: calendar,
  timeRange: { start: '2021-08-26T00:00:00Z', end: '2021-08-27T00:00:00Z' },
});
```

**Comment by lcx** [comment] 2021-08-19 12:07
omg there's a fix for this already? this is awesome 👏  thank you!
can't wait for it to be merged :)

**Comment by lcx** [comment] 2021-09-23 07:58
ok I might have been to quick with my comment. This still seems to be an issue even though according to this it has been merged or am I reading this wrong?

**Comment by wetneb** [comment] 2021-12-23 16:36
Slowness of availability checking is still a problem for me, using a CalDAV integration. The requests to the backend take about 5 seconds when switching to another month, with no indication that anything is happening, so as a user I click on the "next month" button multiple times, and end up farther in the future than I originally would like to.

**Comment by PeerRich** [comment] 2021-12-23 18:48
we are changing the entire system of how we check availability and move to a monthly caching model so all requests will be super snappy. please be patient, we hope to launch it in Q1

**Comment by alishaz-polymath** [comment] 2022-07-20 05:20
@kuba-orlik Hi, can you please confirm if the CalDAV availability checking has improved for you now? How long is it taking for you now?

**Comment by alishaz-polymath** [comment] 2022-07-25 06:03
Closing this as the CalDAV availability checking has improved according to our benchmark tests. It isn't perfect yet, and there is certainly a room for improvement, but it isn't specific to CalDAV. Please feel free to re-open it if you struggle with CalDAV availability checking being super slow again.

**Closed by alishaz-polymath** 2022-07-25 06:03 UTC
Labels: 🐛 bug
