### ISSUE TITLE
[CAL-2980] Adding a date override requires two clicks

### ISSUE THREAD

**Issue by steven-tey** [calcom/cal.com#13140] opened 2024-01-10 03:21 UTC
Surprised this is required since when you click on "Add override", the toast says "Override added", but then if you refresh the page it disappears. You need to click on the general "Save" button for it to work.

![CleanShot 2024-01-09 at 19 19 45](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/99b7e4e2-1281-4f6f-a38e-249965afa717/d5942166-4632-425f-bb49-696c9a645f65?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy85OWI3ZTRlMi0xMjgxLTRmNmYtYTM4ZS0yNDk5NjVhZmE3MTcvZDU5NDIxNjYtNDYzMi00MjVmLWJiNDktNjk2YzlhNjQ1ZjY1IiwiaWF0IjoxNzA1NzU3NTI5LCJleHAiOjE3MDU4NDM5Mjl9.s43HxNitMFRuhgfWrVOWbqs-TmUVOJIVBXZDm-sZMqQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2980](https://linear.app/calcom/issue/CAL-2980/adding-a-date-override-requires-two-clicks)</sub>

**Comment by adityaDev100** [comment] 2024-01-10 06:49
want to solve this

**Comment by Piyush-Kumar-Ghosh** [comment] 2024-01-10 07:47
Hey @steven-tey, I believe some clarification from a Core member would be beneficial here. It seems like the **Add Override** functionality specifically updates the UI content upon clicking the button, with success messages displayed. However, it appears that this new data modifies the frontend value only. To make these changes permanent, the **Save** button is utilized to transmit the updated data to the backend for the actual update. Looking forward to insights from the Core team on this! 🚀

**Comment by PeerRich** [comment] 2024-01-10 18:22
i agree. adding an override should also save the new availability without extra clicking "Save"

**Comment by Piyush-Kumar-Ghosh** [comment] 2024-01-10 19:16
Hi @PeerRich, I would like to attempt it.

**Comment by DariusPirvulescu** [comment] 2024-02-27 11:29
After adding an override and navigating away, there wasn't a warning about losing the override. After adding many overrides, I got caught up with that and lost all my progress. That was confusing/annoying. 
If not saving the override after modal close, can we at least get a warning when navigating away?

**Comment by CarinaWolli** [comment] 2024-09-24 15:24
Closing, because it's a duplicate of https://github.com/calcom/cal.com/issues/11191

**Closed by CarinaWolli** 2024-09-24 15:24 UTC
Labels: linear, Low priority, ui, community
