### ISSUE TITLE
[CAL-1226] event scheduled at wrong time(zone)

### ISSUE THREAD

**Issue by Dieterbe** [calcom/cal.com#7599] opened 2023-03-08 19:15 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Hi, I'm in eastern european standad time (utc+2)
that's what I have set up in my profile.
I noticed that when i book an event, i have to make sure to select the timezone there too, it doesn't seem to just apply the timezone from my profile. also, cal.com keeps asking if i want to update my timezone to UTC. I don't, and i don't see why it would ask that, as my system is definitely set to EEST, and other apps in browser show it correctly (e.g. google calendar)
i use firefox developer edition

so anyway, once i book a meeting, it confirms that it booked what i wanted:
![image](https://user-images.githubusercontent.com/20774/223817000-755bab1a-9fb2-4c83-a009-51800e44bf64.png)
but then on my calendar, it shows up 2 hours too late:
![image](https://user-images.githubusercontent.com/20774/223818233-4ec64800-5b12-4c8d-9fcb-d18a836c6a8d.png)

<sub>[CAL-1226](https://linear.app/calcom/issue/CAL-1226/event-scheduled-at-wrong-timezone)</sub>

**Comment by kemilbeltre** [comment] 2023-06-20 21:18
@PeerRich I would like to take this one. Thanks

**Comment by CarinaWolli** [comment] 2023-07-11 14:00
Hi @Dieterbe, is this still an issue for you? I am not able to reproduce it

**Comment by keithwillcode** [comment] 2023-07-17 14:35
Moving to v3.3 since labeled as Medium priority

**Comment by CarinaWolli** [comment] 2023-08-08 14:19
Issue is most likely already fixed. @Dieterbe feel free to reopen the issue if you are still experiencing that 🙏

**Closed by CarinaWolli** 2023-08-08 14:19 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, Medium priority, 3 points, bookings
