### ISSUE TITLE
[CAL-741] accept booking: "invalid_type in userId": Required

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#6420] opened 2023-01-11 22:31 UTC
![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/6e9cf88a-9b5f-44aa-89fd-f9060577fe9d/ee2e8220-61ca-4eae-8466-dae13d48db70)

when clicking

![image.png](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4930b098-b372-4029-aaae-f19c6aee03da/dd279a7d-7886-4dfe-9c2c-3614545ca70f)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-741](https://linear.app/calcom/issue/CAL-741/accept-booking-invalid-type-in-userid-required)</sub>

**Comment by PeerRich** [comment] 2023-01-11 22:31
duplicate of [https://linear.app/calcom/issue/CAL-756/approval-email-click-on-accept-leads-to-an-error](https://linear.app/calcom/issue/CAL-756/approval-email-click-on-accept-leads-to-an-error)

**Comment by zomars** [comment] 2023-01-11 22:31
duplicate of [https://linear.app/calcom/issue/CAL-756/approval-email-click-on-accept-leads-to-an-error](https://linear.app/calcom/issue/CAL-756/approval-email-click-on-accept-leads-to-an-error)

**Closed by zomars** 2023-01-11 22:31 UTC
Labels: Urgent

**Comment by zomars** [comment] 2023-01-11 22:38
continued in #6340
