### ISSUE TITLE
[CAL-3022] UI doesn't load properly on "Teams" Dashboard

### ISSUE THREAD

**Issue by nil2022** [calcom/cal.com#13392] opened 2024-01-24 15:50 UTC
### Issue Summary

I recently created account on [**Cal.com**](http://Cal.com) and found a **UI render problem** on teams dashboard. When I'm on the ***Teams*** tab, after clicking on ***Create Team*** button, I land on ***Create a new team*** Dashboard. Then I clicked on ***Cancel*** button (suppose I don't wanna create team right now), the UI doesn't render properly and the side navigation bar shifts to right side!. After I manually refresh the page by clicking reload button, it comes to original UI state when it was on ***Teams*** Dashboard.  
NOTE:- I have seen on [***Cal.com***](http://Cal.com) official website where i created account and also I forked repo and build locally and found same bug there also.

### Steps to Reproduce

1. Let's suppose we're on the ***Teams*** Dashboard page.
2. Now click on ***Create Team*** button
3. Now the ***Create a new team*** Dashboard loads....
4. Now press the ***Cancel*** button
5. You can notice abnormal UI rendering.

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/4e9544f2-a438-449e-8908-ffd6ec66d2d6/c4bf134f-03f7-4d1d-b566-d5068fb28a50?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy80ZTk1NDRmMi1hNDM4LTQ0OWUtODkwOC1mZmQ2ZWM2NmQyZDYvYzRiZjEzNGYtMDNmNy00ZDFkLWI1NjYtZDUwNjhmYjI4YTUwIiwiaWF0IjoxNzA2MTc1NDg2LCJleHAiOjE3MDYyNjE4ODZ9.BEtc5OOvteZEXwVaxdc1ap0WIBvCmHNBdIA9ixQUsBo)

### Actual Results

* Abnormal rendering of UI after pressing ***Cancel*** button on ***Create a new team*** Dashboard page.

### Expected Results

* The UI should show actual ***Teams*** Dashboard page when we see before creating any team after pressing the ***Cancel*** button (below image for reference)

![image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/c346cb3b-258c-4744-af24-8de3cad1d4b8/60a5690a-8af5-4c55-9e02-d0549947de56?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9jMzQ2Y2IzYi0yNThjLTQ3NDQtYWYyNC04ZGUzY2FkMWQ0YjgvNjBhNTY5MGEtOGFmNS00YzU1LTllMDItZDA1NDk5NDdkZTU2IiwiaWF0IjoxNzA2MTc1NDg2LCJleHAiOjE3MDYyNjE4ODZ9.m2LMPTK03aNie8Tjzd_2Ia7KO_HVuBrIILlSN1NvCRw)

### Technical details

* I'm using Chrome ver. 120.0.6099.225 (Official Build) (64-bit)
* Screen Recording to show the bug ->

[https://github.com/calcom/cal.com/assets/105872070/d38dccc1-1009-4c35-bdce-158dacd846f7](https://github.com/calcom/cal.com/assets/105872070/d38dccc1-1009-4c35-bdce-158dacd846f7)

### Evidence

* I have noticed the UI render bug on [cal.com](http://cal.com) website after logging with my credentials, also I forked repo and build locally and found same bug there also.
* Below is the screen recording with logs in VSCode when checking locally ->

[https://github.com/calcom/cal.com/assets/105872070/c2f4fa5c-2772-4a27-a58b-0c85f4762b68](https://github.com/calcom/cal.com/assets/105872070/c2f4fa5c-2772-4a27-a58b-0c85f4762b68)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3022](https://linear.app/calcom/issue/CAL-3022/ui-doesnt-load-properly-on-teams-dashboard)</sub>

**Comment by PeerRich** [comment] 2024-01-25 09:38
does this also happens on production?

**Comment by nil2022** [comment] 2024-01-25 09:48
I have seen this abnormal rendering of UI in **_Cal.com_**(so may in production also) and I also uploaded a screen recording of that! I thought this needs to be fixed so I raised the issue.

**Comment by Rksingh090** [comment] 2024-01-25 16:00
Please assign this task to me

**Comment by Udit-takkar** [comment] 2024-01-29 15:31
can't reproduce this bug locally or on production.

**Comment by nil2022** [comment] 2024-01-29 16:27
did u check it on cal.com website ? @Udit-takkar

**Comment by Udit-takkar** [comment] 2024-01-30 07:43
> did u check it on cal.com website ? @Udit-takkar

yes

**Closed** 2024-02-08 18:58 UTC
Labels: 🐛 bug, 🤔 can't reproduce, Medium priority, teams, ui, community, consumer
