### ISSUE TITLE
[CAL-660] Can't Book Appt after March 12th Daylight Savings date - No available user found

### ISSUE THREAD

**Issue by grapeslush** [calcom/cal.com#6217] opened 2022-12-29 23:55 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Unable to book any appointments after March 12 when Daylight Savings Time takes effect in the US.

### Steps to Reproduce

1. Choose any appointment, and try to schedule a date after March 12
2. Enter required details and submit
3. Prompted with an error that indicated 'No Users Available'

I have tried changing availability times to open them up wider to see if that would allow things to bypass this problem and it does not appear to. I can however book an appointment with a test booking of only 15 minutes in the middle of the day. However we're utilizing this tool to book a single appointment once per day.

### Technical details

<img width="863" alt="image" src="https://user-images.githubusercontent.com/113303741/210022100-9b8aaeaa-85ea-4878-9076-d2fba557a518.png">

<sub>[CAL-660](https://linear.app/calcom/issue/CAL-660/cant-book-appt-after-march-12th-daylight-savings-date-no-available)</sub>

**Comment by grapeslush** [comment] 2022-12-31 14:25
I have tried many workarounds at this point. I've attempted moving the appointment in the synced Google calendar manually. It does cause an update email to be sent to the client telling them the time has changed, but within the cal.com site it still shows the old date. 

Please let me know if there is any other info you need or any other workaround anyone can think of. Again, we schedule only 1 appointment a day and they are typically either 4 hours or 6 hour appointments.

**Comment by PeerRich** [comment] 2023-01-01 13:04
@Udit-takkar can you investigate this?

**Comment by grapeslush** [comment] 2023-01-02 02:23
Thank you all very much for the attention on this. I was an Incident Manager for many years, so seeing a company respond to single user bug reports is really awesome.

Thanks again, hope you all had a good New Years.

**Comment by Udit-takkar** [comment] 2023-01-02 09:10
<img width="638" alt="Screenshot 2023-01-02 at 2 39 51 PM" src="https://user-images.githubusercontent.com/53316345/210212009-de017fa5-704f-4121-9b65-21eb04560700.png">

@PeerRich can't reproduce this.

**Comment by grapeslush** [comment] 2023-01-02 11:25
@Udit-takkar I mentioned above, but this seems to be specific to when an appointment covers the entire availability. We only schedule 1 appointment per day and it's 6 hours and covers the entire 6 hours of availability. Also we are trying to book in America/Eastern Time. 

Please see my screenshots of our availability and other appointment settings. I'll also link to calendar if you would like to try yourself.

Booking Link: https://cal.com/bookwithmar/full-day

<img width="531" alt="image" src="https://user-images.githubusercontent.com/113303741/210224790-61c624c8-5c52-4f64-9064-a81a1386b147.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/113303741/210224850-c467f06a-4381-4c5e-b39c-5304a659bc61.png">

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/113303741/210224882-46bf3019-f238-482c-877a-06183242536d.png">

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/113303741/210224943-308de94c-64fd-495e-a1c3-61066bb1b215.png">


Nothing reoccurring, no apps, and 2 workflows to send SMS Reminders.

Please let me know if you need more information.

**Comment by dgalindez** [comment] 2023-01-03 20:43
@Udit-takkar we have https://github.com/calcom/cal.com/issues/6047 open, we think this might be the same issue
We can get fairly consistent repros on this, with self-hosted cal.
Would it be useful to have a chat and give you access to our cal? Maybe that can shed some light on the issue

**Comment by dgalindez** [comment] 2023-01-03 20:49
Also we are pretty sure November/March are the ones that tend to fail (the DST switch is when things seem to fail)

**Comment by jacobzukerman** [comment] 2023-01-04 01:01
@Udit-takkar, following up to @dgalindez comment with more details. 

We have a Cal event setup that schedules 24 occurrences every two weeks for our users. If a user picks the first time slot or one with less than an hour of availability before the event, it will fail and will get the above error. When scheduling the 24 occurrences, the invites will fail either in November or March, when daylight savings changes happen in the US. The first set of invites before the failure date will still get sent out. 

If I go into the availability preferences and add at least an hour of buffer, the event will schedule fine.

**Comment by grapeslush** [comment] 2023-01-04 01:04
@jacobzukerman Are you thinking in my case, I should extend my availability by an hour and then set a 1hr buffer to force the meeting to start at the right time?

**Comment by grapeslush** [comment] 2023-01-04 01:08
I did try the 1hr buffer, and it gave me the same error. No available users found.

**Comment by Udit-takkar** [comment] 2023-01-04 15:44
okay thanks for reporting this @grapeslush @dgalindez @jacobzukerman . we are investigating this issue.

**Comment by grapeslush** [comment] 2023-01-10 18:14
Hello @Udit-takkar just looking to see if we have any updates on this matter? I have some significant work ahead of me to get schedules corrected. Thanks :)

**Comment by Udit-takkar** [comment] 2023-01-10 18:20
@emrysal is working on a fix for this issue.

**Comment by grapeslush** [comment] 2023-01-11 16:05
Thank you!

**Comment by mrkirchner** [comment] 2023-01-24 17:43
any updates on this @Udit-takkar

**Comment by Udit-takkar** [comment] 2023-01-24 17:48
@mrkirchner this PR  https://github.com/calcom/cal.com/pull/6538 would fix the issue  . some work is still left

**Comment by ajorg** [comment] 2023-02-19 22:47
I see similar issues and it seems clearly to be caused by DST handling. I set up my account with only one half hour of availability per week (12:30pm), and then browsed the calendar. Every week showed the correct available time, except March 12 and November 5. March 12 shows 11:30am, and November 5 shows 1:30pm.

Then the reason the booking fails seems likely to be because I don't have availability at 11:30am or 1:30pm.

It could be something subtle, to do with localization on the UI vs DST handling on the backend. I notice that the booking URL has `date=2023-11-05T13` for November 5, `date=2023-11-05T11` for March 12, and `date=2023-11-05T12` for everything else.

**Comment by cpunnelliehealth** [comment] 2023-02-27 00:28
Having this issue as well, still present on cal version 2.6.6. Steps to reproduce:

1) Set working schedule limits e.g., 9am-5pm M-F. Timezone America/Toronto (or New_York)
2) Try to schedule a time that crosses the daylight savings time period, e.g., current date Feb 26, 2023 and attempting to book March 16, 2023 at 9am, which is at the earliest possible time of Availability.
3) Get this error message:

<img width="771" alt="Screen Shot 2023-02-26 at 7 26 10 PM" src="https://user-images.githubusercontent.com/126418022/221446995-d2356907-3700-40ec-82a0-f72ea4d57cc0.png">

I suspect this is due to the shift in DST not being accounted for in the Availability, so it may appear as if I'm trying to book an 8am timeslot but in fact it is 9am because of DST.

**Comment by grapeslush** [comment] 2023-03-01 03:56
Yes this seems to still be a problem. We've had to manually book clients all the way out to July. None of them are now getting email alerts or sms etc. That's been the only solution we've been able to come up with. I've tried all the settings possible to make it work including shifting around working hours etc.

**Comment by elmerohueso** [comment] 2023-03-01 04:48
I think this may be the same issue at [CAL-863](https://github.com/calcom/cal.com/issues/6622#issuecomment-1449324922)

**Closed** 2023-03-04 16:38 UTC
Labels: 🐛 bug, 👩‍🔬 needs investigation, linear

**Comment by roae** [comment] 2023-03-04 16:40
Fixed in #7462
