### ISSUE TITLE
[CAL-2113] merge all PR related github workflows into one file

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#9966] opened 2023-07-06 16:33 UTC
is it possible to merge:

- Validate PRs / Validate PR title (pull_request_target) 
- Assign PR team labels / team-labels (pull_request) 
- Pull Request Labeler / labeler (pull_request_target) 

into one workflow:
- Adding relevant data to PR

<sub>[CAL-2113](https://linear.app/calcom/issue/CAL-2113/merge-all-pr-related-github-workflows-into-one-file)</sub>

**Comment by ouwargui** [comment] 2023-07-06 16:57
I think it's only possible to have multiple jobs in one workflow, but on the UI it will look like this


<img width="849" alt="image" src="https://github.com/calcom/cal.com/assets/44242141/9d4c9eba-86cc-41f8-b049-e6c636807fb4">

**Comment by PeerRich** [comment] 2023-07-06 22:11
so not possible to combine these into one workflow in the UI?

**Comment by ayush-AI** [comment] 2023-07-07 08:45
I think adding little info about the expected outcome after accomplishing this merge(means the motivation behind creation of this issue) in issue description will help in finding the appropriate solution to this problem.

**Comment by avinal** [comment] 2023-07-07 19:08
It should be possible, I will take a look by Monday and let you know.

**Comment by avinal** [comment] 2023-07-13 08:06
@PeerRich There is only one way of doing it that is converting each job into steps rather than a workflow. It may or may not be better than the present config. The biggest downside is, the tasks will run one-after-the-other, making the overall workflow slow.

As @ouwargui mentioned, we can put all related workflow as jobs in a single file, it will retain all the functionality but reduce the number of files as well as group similar checks in one. But it will still show as different checks on UI. 

I will recommend the second option.

**Comment by shyamtawli** [comment] 2023-07-29 12:28
Hey I am new to this but what I have understand is that the issue is about mergering 3 wrokflows into single file, that is `pr-assign-team-label.yml`, `labeler.yml` and `semantic-pull-requests.yml`. Am I right or I am missing something? 

I want to explore it and resolve it as first issue.

**Comment by julycrystal** [comment] 2023-08-12 01:47
Hi @PeerRich 
It is possible to aggregate those three workflows into one file, with one job per workflow.
We can use if statements with `github.event_name` and `github.event.action` to filter events.

Please assign this issue to me so that I can resolve it.
Best

**Comment by zomars** [comment] 2023-10-17 00:50
> The biggest downside is, the tasks will run one-after-the-other, making the overall workflow slow.

I think this is enough reason to not pursue this further. Will close for now.

**Closed by zomars** 2023-10-17 00:50 UTC
Labels: ✨ feature, ✅ good first issue, 🙋🏻‍♂️help wanted, Low priority, ci
