### ISSUE TITLE
Duplicate booking spam: Sending 100 emails vs 1 email

### ISSUE THREAD

**Issue by Illyism** [calcom/cal.com#13852] opened 2024-02-25 15:46 UTC
<img width="362" alt="image" src="https://github.com/calcom/cal.com/assets/304283/fe34d0e7-4338-48ea-a05c-6565fd2efbf6">

**Comment by keithwillcode** [comment] 2024-02-25 15:54
So sorry for the irritation with this. We are actively working to fix this ASAP

**Comment by Illyism** [comment] 2024-02-25 17:39
<img width="412" alt="image" src="https://github.com/calcom/cal.com/assets/304283/de2feb26-0c17-49eb-98a3-70c365bf6f58">

The initial email (invite confirmation) was sent 100 times. The client reached out.

Then a few hours later, another 100 emails were sent with the reminder to confirm...

I can't "reject" manually the invitations. It's not only the emails. It was 100 invitations on the Cal.com dashboard!

There is no option to bulk delete.

I can't have it keep sending emails to the guy.

I had to completely disable and delete my account...

https://twitter.com/illyism/status/1761735453252743207

**Comment by Pritam-sd-dev** [comment] 2024-02-26 03:59
@keithwillcode 
is anyone working on this, please clear once so that i can pick this issue.

**Comment by PeerRich** [comment] 2024-02-26 09:50
yes we are working on this with highest priority!

**Comment by emrysal** [comment] 2024-02-26 10:53
Hi @Illyism Please get in contact with support if this happens before our fix is in place, we'll remove the bookings from your account so you don't have to delete. We can't reproduce this behaviour through the UI but our pending fix is serverside.

**Comment by Illyism** [comment] 2024-02-26 11:03
> Hi @Illyism Please get in contact with support if this happens before our fix is in place, we'll remove the bookings from your account so you don't have to delete. We can't reproduce this behaviour through the UI but our pending fix is serverside.

Hi, after sending out 100 emails twice to the same person, I had to delete my account. I already did this and moved to something else. There was no way I was going to wait (now almost 20h later) to have it happen again and again or to multiple people.

**Comment by Illyism** [comment] 2024-02-26 13:13
> Hi @Illyism Please get in contact with support if this happens before our fix is in place, we'll remove the bookings from your account so you don't have to delete. We can't reproduce this behaviour through the UI but our pending fix is serverside.

<img width="603" alt="image" src="https://github.com/calcom/cal.com/assets/304283/d66fdc2b-e054-4293-a368-c62ddada6f07">

Support just woke up

**Comment by PeerRich** [comment] 2024-02-26 13:59
hey man i am not the one implementing the fix

here are two PRs being tested:

https://github.com/calcom/cal.com/pull/13865

https://github.com/calcom/cal.com/pull/13839

it is really hard to debug because not everyone is experiencing this (otherwise you would see more issues here) and we have to pinpoint down why it's affecting your account

thanks for asking about my personal priorities, right now they are curing my 39 degree fever ![image](https://github.com/calcom/cal.com/assets/8019099/bbf831a9-21d8-4407-a795-67f36cfdba51)

![image](https://github.com/calcom/cal.com/assets/8019099/83cc02ff-c7d9-4f2d-baa4-73b9633c37f0)

and memes on twitter at least help a bit

**Comment by carlosvirreira** [comment] 2024-02-26 14:06
> hey man i am not the one implementing the fix
> 
> here are two PRs being tested:
> 
> #13865
> 
> #13839
> 
> it is really hard to debug because not everyone is experiencing this (otherwise you would see more issues here) and we have to pinpoint down why it's affecting your account
> 
> thanks for asking about my personal priorities, right now they are curing my 39 degree fever ![image](https://private-user-images.githubusercontent.com/8019099/307817250-bbf831a9-21d8-4407-a795-67f36cfdba51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTY2NTAsIm5iZiI6MTcwODk1NjM1MCwicGF0aCI6Ii84MDE5MDk5LzMwNzgxNzI1MC1iYmY4MzFhOS0yMWQ4LTQ0MDctYTc5NS02N2YzNmNmZGJhNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTQwNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJhNTFmODkzNTYwZjgxMGJmMjFhNTI1N2U1Zjc5NTM3NzhiNGE0MGMyMDMxN2JhYzE0OTYwNDgyY2JhNWZmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1nw6XMA0IDfmT1QiRALTT63HOJOCkKfyP3YWec3ymyU)
> 
> ![image](https://private-user-images.githubusercontent.com/8019099/307817295-83cc02ff-c7d9-4f2d-baa4-73b9633c37f0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTY2NTAsIm5iZiI6MTcwODk1NjM1MCwicGF0aCI6Ii84MDE5MDk5LzMwNzgxNzI5NS04M2NjMDJmZi1jN2Q5LTRmMmQtYmFhNC03M2I5NjMzYzM3ZjAuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE0MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NzgzZTk3ZWQwNzFhY2YzZTVhYmJhNDc1ZmQ0YjFiMjQ5NDJiNjRhYWU0MjI4M2IyZTIxMzA5YjdlYTczMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fZB4VVTAC8Fi26setkyn7b1TOIzFMoxwdzmPbHXkqlU)
> 
> and memes on twitter at least help a bit

Get well soon!!

**Comment by PeerRich** [comment] 2024-02-26 14:11
thank you @Illyism 🙏

put me in touch with the guests who have received too many emails and i‘ll personally apologise, so it doenst look bad on you 

peer@cal.com

**Comment by shyamtawli** [comment] 2024-02-26 14:21
Get well soon sir 💙

**Comment by Pritam-sd-dev** [comment] 2024-02-26 15:57
@PeerRich sir please take care of your health,
My god please recover peerRich sir.

**Closed** 2024-02-27 03:18 UTC
Labels: 🐛 bug, Urgent, 📉 regressing, emails
