### ISSUE TITLE
[CAL-771] bug: new lines not working in workflow email

### ISSUE THREAD

**Issue by HelloAlexPan** [calcom/cal.com#6395] opened 2023-01-11 08:48 UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

New lines are not saved in the workflow email editor
<img width="801" alt="image" src="https://user-images.githubusercontent.com/53453555/211759850-d483ff4d-9b57-4c6a-b17a-67f53d9a3695.png">

### Steps to Reproduce

1. Open a workflow
2. Create a new line  (`Enter`) in the workflow email
3. Click save
4. Refresh page
5. All text is saved a single line string

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-771](https://linear.app/calcom/issue/CAL-771/bug-new-lines-not-working-in-workflow-email)</sub>

**Comment by CarinaWolli** [comment] 2023-01-12 21:34
I can't reproduce that. @HelloAlexPan could you maybe provide a loom so I can see what's happening on your side and how to reproduce that?

**Comment by zomars** [comment] 2023-01-20 22:21
Closing until proper reproduction is available

**Closed by zomars** 2023-01-20 22:21 UTC
Labels: 🧹 Improvements, 👩‍🔬 needs investigation, 🤔 can't reproduce, linear
