### ISSUE TITLE
Please make Event Description allow for HTML code  OR LINKS

### ISSUE THREAD

**Issue by geoffjohnsonphoto** [calcom/cal.com#7076] opened 2023-02-13 18:49 UTC
### Is your proposal related to a problem?

Within the description field you give one bar and the formatting is all pushed together.  This is very difficult to read.  There is also no support for code here or links so this looks very messy.

### Describe the solution you'd like

I would love to see a description section that is more similar to the ABOUT section so it allows for formatting, Links, line breaks, etc.
### Describe alternatives you've considered

I tried to add code into this area but it doesn't work.

### Additional context

[(Write your answer here.)]

(https://cal.com/lumierestudio/book?type=179415&date=2023-02-28T10%3A00%3A00-06%3A00&slug=2-hours-studio-rental&count=)

**Comment by CarinaWolli** [comment] 2023-02-13 20:27
We are planning to implement our `<Editor/>` component (already used for bio) for the event type description. Closing, a duplicate of #5764

**Closed by CarinaWolli** 2023-02-13 20:27 UTC
