### ISSUE TITLE
Sync changes from google calendar back to the cal.com

### ISSUE THREAD

**Issue by ecrode** [calcom/cal.com#11860] opened 2023-10-12 14:28 UTC
### Is your proposal related to a problem?

There is a problem in that, should event be moved / rescheduled from within google calendar (potentially others as well), than cal.com is unaware of the change besides the fact that the new time is now unavailable for new appointments.

### Describe the solution you'd like

During calendar sync, detect changes to the schedule, identify even moves / reschedules, and update the corresponding cal.com event details.

### Describe alternatives you've considered

Using the reschedule / cancel link within event details. This works but adds additional steps which would otherwise be quicker by just rescheduling within the calendar.

### Additional context

Primarily the issue is that any links to reschedule from cal.com sent to the client still has the old time, even after the event was moved and a separate notification potentially sent from the calendar.

**Comment by PeerRich** [comment] 2023-10-12 15:34
afaik this is in progress

**Comment by PeerRich** [comment] 2023-10-17 11:11
duplicate of https://github.com/calcom/cal.com/issues/11524

**Closed by PeerRich** 2023-10-17 11:11 UTC
