### ISSUE TITLE
Text is not changing as we hover over the icon

### ISSUE THREAD

**Issue by skushagra9** [calcom/cal.com#8676] opened 2023-05-04 17:52 UTC
This is the Set to default button

![image](https://user-images.githubusercontent.com/120712705/236288218-80a52ff9-02ca-49eb-b5b5-60f6294d26d0.png)

As we hover over it , the text color doesn't changes

![image](https://user-images.githubusercontent.com/120712705/236288370-a8d63633-c710-442f-93f5-72e8eab05273.png)

Go to http://localhost:3000/availability/

**Comment by Udit-takkar** [comment] 2023-05-05 07:11
duplicate of https://github.com/calcom/cal.com/issues/8628

**Closed by Udit-takkar** 2023-05-05 07:11 UTC
Labels: 🐛 bug
