### ISSUE TITLE
misleading error message on Login page

### ISSUE THREAD

**Issue by 0verread** [calcom/cal.com#9474] opened 2023-06-12 18:34 UTC
### Issue Summary
The login page asks for the email address. if we try to log in with the wrong creds, the error message says `Username or password is incorrect.` which is misleading and can confuse users.

### Steps to Reproduce

1. Went to the Login page ( click on login)
2. put the wrong credentials 
3. Click Login. you will get the error message here.

![Screenshot 2023-06-12 at 2 25 47 PM](https://github.com/calcom/cal.com/assets/97605913/027c5a2f-1df6-4af9-8dcd-e1df63124924)

**Comment by headshigh** [comment] 2023-06-13 01:13
i am working on it

**Comment by headshigh** [comment] 2023-06-13 01:20
this seems to be intentional since the comment in the code says "Don't leak information on wether a email is registered or not". I guess you can close this issue

**Comment by N-NeelPatel** [comment] 2023-06-13 04:27
@0verread - this is expected behavior.

**Comment by ujwalkumar1995** [comment] 2023-06-13 15:46
I think this is intentional to stop brute force attack on password and is the correct behaviour.

**Closed** 2023-06-26 21:01 UTC
Labels: 🐛 bug
