### ISSUE TITLE
[CAL-3810] Allow ORG Owners the Ability to Turn off Confirmation Emails without Active Workflow

### ISSUE THREAD

**Issue by shirazdole** [calcom/cal.com#15212] opened 2024-05-28 03:05 UTC
Give org owners ability to handle emails purely via webhooks so that emails can come from their domain with their styling. 

I understand there's a risk here as it's a core part of the product experience, but we should be able to get it to a point that the owner understands the risk from a UI perspective. Also, if it's only limited to org owners of org customers, it's a much smaller group of customers to provide customer support for 

cc @peer @keithwillcode 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3810](https://linear.app/calcom/issue/CAL-3810/allow-org-owners-the-ability-to-turn-off-confirmation-emails-without)</sub>

**Comment by ciaranha** [comment] 2024-05-28 07:06
@shirazdole this is a duplicate of https://github.com/calcom/cal.com/issues/12920 which is already in the current milestone.

**Comment by ciaranha** [comment] 2024-05-28 07:08
@shirazdole would this be covered under this https://github.com/calcom/cal.com/issues/12920 if I'm not mistaken?

**Closed** 2024-05-28 07:09 UTC
Labels: ✨ feature, webhooks, organizations, emails
